image: gcc:latest

build:
    stage: build
    script:
        - cd test/
        - git clone https://github.com/Snaipe/Criterion.git
        - cd Criterion/
        - mkdir build/
        - cd build/
        - apt-get update
        - apt-get install -y cmake
        - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
        - cmake --install .
        - make install
        - cd ../..
        - make
        - ./test
