server-tests:
    image: python:3.5
    stage: test
    script:
        - pip install -r Server/requirements.txt
        - pip install -e Server
        - initialize_test_db Server/tests.ini
        - pytest Server/makahiya/tests.py -q

project-build:
    image: rfc1149/rose-dev
    stage: build
    script:
        - make -C Project

<<<<<<< HEAD
project-test:
    image: rfc1149/rose-dev
    stage: test
    script:
        - make -C Project run_test

cache:
    key: all
    paths:
      - $CCACHE_DIR
=======
server-Server/tests:
    stage: test
    script:
        - pip install -r Server/requirements.txt
        - pip install -e Server
        - initialize_test_db Server/tests.ini
        - pytest Server/makahiya/tests.py -q
>>>>>>> 84a581a... SQLsessions are now closed properly.
