image: rfc1149/rose-dev

variables:
    CCACHE: ccache
    CCACHE_DIR: $CI_PROJECT_DIR/.ccache

olimex-build:
    stage: build
    script:
        - make -C helix
        - make -C Project

olimex-test:
    stage: test
    script:
        - make -C Project run_test

cache:
    key: all
    paths:
      - $CCACHE_DIR
