image: gcc:latest

build:
    stage: build
    script:
        - git checkout dev
        - ls
        - cd test/
        - git clone https://github.com/Snaipe/Criterion.git
        - cd Criterion/
        - mkdir build/
