image: andystanton/gcc-cmake-gl

build:
    stage: build
    script:
        - cd test/
        - support/build-criterion-if-needed
        - (cd Criterion/build/ && make install)
        - make
        - ./test

cache:
  key: all
  paths:
    - test/Criterion
