image: rfc1149/rose-dev

variables:
    CCACHE: ccache
    CCACHE_DIR: $CI_PROJECT_DIR/.ccache

olimex-build:
    stage: build
    script:
        - make -C olimexP407 helix
        - make -C olimexP407

native-build:
    stage: build
    script: make -C code

native-tests:
    stage: test
    script: make -C test check

cache:
    key: all
    paths:
      - $CCACHE_DIR
