ChibiOS/HAL: ADC Driver
ADC Driver
HAL » Normal Drivers
Generic ADC Driver.
Detailed Description
Generic ADC Driver.
This module implements a generic ADC (Analog to Digital Converter) driver supporting a variety of buffer and conversion modes.
Precondition
In order to use the ADC driver the HAL_USE_ADC option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
ADC Operations
The ADC driver is quite complex, an explanation of the terminology and of the operational details follows.
ADC Conversion Groups
The ADCConversionGroup is the objects that specifies a physical conversion operation. This structure contains some standard fields and several implementation-dependent fields.
The standard fields define the CG mode, the number of channels belonging to the CG and the optional callbacks.
The implementation-dependent fields specify the physical ADC operation mode, the analog channels belonging to the group and any other implementation-specific setting. Usually the extra fields just mirror the physical ADC registers, please refer to the vendor's MCU Reference Manual for details about the available settings. Details are also available into the documentation of the ADC low level drivers and in the various sample applications.
ADC Conversion Modes
The driver supports several conversion modes:
One Shot, the driver performs a single group conversion then stops.
Linear Buffer, the driver performs a series of group conversions then stops. This mode is like a one shot conversion repeated N times, the buffer pointer increases after each conversion. The buffer is organized as an S(CG)*N samples matrix, when S(CG) is the conversion group size (number of channels) and N is the buffer depth (number of repeated conversions).
Circular Buffer, much like the linear mode but the operation does not stop when the buffer is filled, it is automatically restarted with the buffer pointer wrapping back to the buffer base.
ADC Callbacks
The driver is able to invoke callbacks during the conversion process. A callback is invoked when the operation has been completed or, in circular mode, when the buffer has been filled and the operation is restarted. In circular mode a callback is also invoked when the buffer is half filled.
The "half filled" and "filled" callbacks in circular mode allow to implement "streaming processing" of the sampled data, while the driver is busy filling one half of the buffer the application can process the other half, this allows for continuous interleaved operations.
The driver is not thread safe for performance reasons, if you need to access the ADC bus from multiple threads then use the adcAcquireBus() and adcReleaseBus() APIs in order to gain exclusive access.
ADC configuration options
#define ADC_USE_WAIT TRUE
Enables synchronous APIs.
#define ADC_USE_MUTUAL_EXCLUSION TRUE
Enables the adcAcquireBus() and adcReleaseBus() APIs.
Low level driver helper macros
#define _adc_reset_i(adcp) osalThreadResumeI(&(adcp)->thread, MSG_RESET)
Resumes a thread waiting for a conversion completion.
#define _adc_reset_s(adcp) osalThreadResumeS(&(adcp)->thread, MSG_RESET)
Resumes a thread waiting for a conversion completion.
#define _adc_wakeup_isr(adcp)
Wakes up the waiting thread.
#define _adc_timeout_isr(adcp)
Wakes up the waiting thread with a timeout message.
#define _adc_isr_half_code(adcp)
Common ISR code, half buffer event.
#define _adc_isr_full_code(adcp)
Common ISR code, full buffer event.
#define _adc_isr_error_code(adcp, err)
Common ISR code, error event.
Absolute Maximum Ratings
#define STM32_ADCCLK_MIN 600000
Minimum ADC clock frequency.
#define STM32_ADCCLK_MAX 36000000
Maximum ADC clock frequency.
Triggers selection
#define ADC_CR2_EXTEN_MASK (3U << 28U)
#define ADC_CR2_EXTEN_DISABLED (0U << 28U)
#define ADC_CR2_EXTEN_RISING (1U << 28U)
#define ADC_CR2_EXTEN_FALLING (2U << 28U)
#define ADC_CR2_EXTEN_BOTH (3U << 28U)
#define ADC_CR2_EXTSEL_MASK (15U << 24U)
#define ADC_CR2_EXTSEL_SRC(n) ((n) << 24U)
ADC clock divider settings
#define ADC_CCR_ADCPRE_DIV2 0
#define ADC_CCR_ADCPRE_DIV4 1
#define ADC_CCR_ADCPRE_DIV6 2
#define ADC_CCR_ADCPRE_DIV8 3
Available analog channels
#define ADC_CHANNEL_IN0 0
External analog input 0.
#define ADC_CHANNEL_IN1 1
External analog input 1.
#define ADC_CHANNEL_IN2 2
External analog input 2.
#define ADC_CHANNEL_IN3 3
External analog input 3.
#define ADC_CHANNEL_IN4 4
External analog input 4.
#define ADC_CHANNEL_IN5 5
External analog input 5.
#define ADC_CHANNEL_IN6 6
External analog input 6.
#define ADC_CHANNEL_IN7 7
External analog input 7.
#define ADC_CHANNEL_IN8 8
External analog input 8.
#define ADC_CHANNEL_IN9 9
External analog input 9.
#define ADC_CHANNEL_IN10 10
External analog input 10.
#define ADC_CHANNEL_IN11 11
External analog input 11.
#define ADC_CHANNEL_IN12 12
External analog input 12.
#define ADC_CHANNEL_IN13 13
External analog input 13.
#define ADC_CHANNEL_IN14 14
External analog input 14.
#define ADC_CHANNEL_IN15 15
External analog input 15.
#define ADC_CHANNEL_SENSOR 16
Internal temperature sensor.
#define ADC_CHANNEL_VREFINT 17
Internal reference.
#define ADC_CHANNEL_VBAT 18
VBAT.
Sampling rates
#define ADC_SAMPLE_3 0
3 cycles sampling time.
#define ADC_SAMPLE_15 1
15 cycles sampling time.
#define ADC_SAMPLE_28 2
28 cycles sampling time.
#define ADC_SAMPLE_56 3
56 cycles sampling time.
#define ADC_SAMPLE_84 4
84 cycles sampling time.
#define ADC_SAMPLE_112 5
112 cycles sampling time.
#define ADC_SAMPLE_144 6
144 cycles sampling time.
#define ADC_SAMPLE_480 7
480 cycles sampling time.
Configuration options
#define STM32_ADC_ADCPRE ADC_CCR_ADCPRE_DIV2
ADC common clock divider.
#define STM32_ADC_USE_ADC1 FALSE
ADC1 driver enable switch.
#define STM32_ADC_USE_ADC2 FALSE
ADC2 driver enable switch.
#define STM32_ADC_USE_ADC3 FALSE
ADC3 driver enable switch.
#define STM32_ADC_ADC1_DMA_STREAM STM32_DMA_STREAM_ID(2, 4)
DMA stream used for ADC1 operations.
#define STM32_ADC_ADC2_DMA_STREAM STM32_DMA_STREAM_ID(2, 2)
DMA stream used for ADC2 operations.
#define STM32_ADC_ADC3_DMA_STREAM STM32_DMA_STREAM_ID(2, 1)
DMA stream used for ADC3 operations.
#define STM32_ADC_ADC1_DMA_PRIORITY 2
ADC1 DMA priority (0..3|lowest..highest).
#define STM32_ADC_ADC2_DMA_PRIORITY 2
ADC2 DMA priority (0..3|lowest..highest).
#define STM32_ADC_ADC3_DMA_PRIORITY 2
ADC3 DMA priority (0..3|lowest..highest).
#define STM32_ADC_IRQ_PRIORITY 5
ADC interrupt priority level setting.
#define STM32_ADC_ADC1_DMA_IRQ_PRIORITY 5
ADC1 DMA interrupt priority level setting.
#define STM32_ADC_ADC2_DMA_IRQ_PRIORITY 5
ADC2 DMA interrupt priority level setting.
#define STM32_ADC_ADC3_DMA_IRQ_PRIORITY 5
ADC3 DMA interrupt priority level setting.
Sequences building helper macros
#define ADC_SQR1_NUM_CH(n) (((n) - 1) << 20)
Number of channels in a conversion sequence.
#define ADC_SQR3_SQ1_N(n) ((n) << 0)
1st channel in seq.
#define ADC_SQR3_SQ2_N(n) ((n) << 5)
2nd channel in seq.
#define ADC_SQR3_SQ3_N(n) ((n) << 10)
3rd channel in seq.
#define ADC_SQR3_SQ4_N(n) ((n) << 15)
4th channel in seq.
#define ADC_SQR3_SQ5_N(n) ((n) << 20)
5th channel in seq.
#define ADC_SQR3_SQ6_N(n) ((n) << 25)
6th channel in seq.
#define ADC_SQR2_SQ7_N(n) ((n) << 0)
7th channel in seq.
#define ADC_SQR2_SQ8_N(n) ((n) << 5)
8th channel in seq.
#define ADC_SQR2_SQ9_N(n) ((n) << 10)
9th channel in seq.
#define ADC_SQR2_SQ10_N(n) ((n) << 15)
10th channel in seq.
#define ADC_SQR2_SQ11_N(n) ((n) << 20)
11th channel in seq.
#define ADC_SQR2_SQ12_N(n) ((n) << 25)
12th channel in seq.
#define ADC_SQR1_SQ13_N(n) ((n) << 0)
13th channel in seq.
#define ADC_SQR1_SQ14_N(n) ((n) << 5)
14th channel in seq.
#define ADC_SQR1_SQ15_N(n) ((n) << 10)
15th channel in seq.
#define ADC_SQR1_SQ16_N(n) ((n) << 15)
16th channel in seq.
Sampling rate settings helper macros
#define ADC_SMPR2_SMP_AN0(n) ((n) << 0)
AN0 sampling time.
#define ADC_SMPR2_SMP_AN1(n) ((n) << 3)
AN1 sampling time.
#define ADC_SMPR2_SMP_AN2(n) ((n) << 6)
AN2 sampling time.
#define ADC_SMPR2_SMP_AN3(n) ((n) << 9)
AN3 sampling time.
#define ADC_SMPR2_SMP_AN4(n) ((n) << 12)
AN4 sampling time.
#define ADC_SMPR2_SMP_AN5(n) ((n) << 15)
AN5 sampling time.
#define ADC_SMPR2_SMP_AN6(n) ((n) << 18)
AN6 sampling time.
#define ADC_SMPR2_SMP_AN7(n) ((n) << 21)
AN7 sampling time.
#define ADC_SMPR2_SMP_AN8(n) ((n) << 24)
AN8 sampling time.
#define ADC_SMPR2_SMP_AN9(n) ((n) << 27)
AN9 sampling time.
#define ADC_SMPR1_SMP_AN10(n) ((n) << 0)
AN10 sampling time.
#define ADC_SMPR1_SMP_AN11(n) ((n) << 3)
AN11 sampling time.
#define ADC_SMPR1_SMP_AN12(n) ((n) << 6)
AN12 sampling time.
#define ADC_SMPR1_SMP_AN13(n) ((n) << 9)
AN13 sampling time.
#define ADC_SMPR1_SMP_AN14(n) ((n) << 12)
AN14 sampling time.
#define ADC_SMPR1_SMP_AN15(n) ((n) << 15)
AN15 sampling time.
#define ADC_SMPR1_SMP_SENSOR(n) ((n) << 18)
Temperature Sensor sampling time.
#define ADC_SMPR1_SMP_VREF(n) ((n) << 21)
Voltage Reference sampling time.
#define ADC_SMPR1_SMP_VBAT(n) ((n) << 24)
VBAT sampling time.
Typedefs
typedef uint16_t adcsample_t
ADC sample data type.
typedef uint16_t adc_channels_num_t
Channels number in a conversion group.
typedef struct ADCDriver ADCDriver
Type of a structure representing an ADC driver.
typedef void(* adccallback_t) (ADCDriver *adcp, adcsample_t *buffer, size_t n)
ADC notification callback type.
typedef void(* adcerrorcallback_t) (ADCDriver *adcp, adcerror_t err)
ADC error callback type.
Data Structures
struct ADCConversionGroup
Conversion group configuration structure.
struct ADCConfig
Driver configuration structure.
struct ADCDriver
Structure representing an ADC driver.
Functions
void adcInit (void)
ADC Driver initialization.
void adcObjectInit (ADCDriver *adcp)
Initializes the standard part of a ADCDriver structure.
void adcStart (ADCDriver *adcp, const ADCConfig *config)
Configures and activates the ADC peripheral.
void adcStop (ADCDriver *adcp)
Deactivates the ADC peripheral.
void adcStartConversion (ADCDriver *adcp, const ADCConversionGroup *grpp, adcsample_t *samples, size_t depth)
Starts an ADC conversion.
void adcStartConversionI (ADCDriver *adcp, const ADCConversionGroup *grpp, adcsample_t *samples, size_t depth)
Starts an ADC conversion.
void adcStopConversion (ADCDriver *adcp)
Stops an ongoing conversion.
void adcStopConversionI (ADCDriver *adcp)
Stops an ongoing conversion.
msg_t adcConvert (ADCDriver *adcp, const ADCConversionGroup *grpp, adcsample_t *samples, size_t depth)
Performs an ADC conversion.
void adcAcquireBus (ADCDriver *adcp)
Gains exclusive access to the ADC peripheral.
void adcReleaseBus (ADCDriver *adcp)
Releases exclusive access to the ADC peripheral.
static void adc_lld_serve_rx_interrupt (ADCDriver *adcp, uint32_t flags)
ADC DMA ISR service routine.
OSAL_IRQ_HANDLER (STM32_ADC_HANDLER)
ADC interrupt handler.
void adc_lld_init (void)
Low level ADC driver initialization.
void adc_lld_start (ADCDriver *adcp)
Configures and activates the ADC peripheral.
void adc_lld_stop (ADCDriver *adcp)
Deactivates the ADC peripheral.
void adc_lld_start_conversion (ADCDriver *adcp)
Starts an ADC conversion.
void adc_lld_stop_conversion (ADCDriver *adcp)
Stops an ongoing conversion.
void adcSTM32EnableTSVREFE (void)
Enables the TSVREFE bit.
void adcSTM32DisableTSVREFE (void)
Disables the TSVREFE bit.
void adcSTM32EnableVBATE (void)
Enables the VBATE bit.
void adcSTM32DisableVBATE (void)
Disables the VBATE bit.
Enumerations
enum adcstate_t {
ADC_UNINIT = 0, ADC_STOP = 1, ADC_READY = 2, ADC_ACTIVE = 3,
ADC_COMPLETE = 4, ADC_ERROR = 5
}
Driver state machine possible states.
enum adcerror_t { ADC_ERR_DMAFAILURE = 0, ADC_ERR_OVERFLOW = 1 }
Possible ADC failure causes.
Variables
ADCDriver ADCD1
ADC1 driver identifier.
ADCDriver ADCD2
ADC2 driver identifier.
ADCDriver ADCD3
ADC3 driver identifier.
Macro Definition Documentation
ADC_USE_WAIT
#define ADC_USE_WAIT TRUE
Enables synchronous APIs.
Note
Disabling this option saves both code and data space.
Definition at line 47 of file adc.h.
ADC_USE_MUTUAL_EXCLUSION
#define ADC_USE_MUTUAL_EXCLUSION TRUE
Enables the adcAcquireBus() and adcReleaseBus() APIs.
Note
Disabling this option saves both code and data space.
Definition at line 55 of file adc.h.
_adc_reset_i
#define _adc_reset_i (adcp) osalThreadResumeI(&(adcp)->thread, MSG_RESET)
Resumes a thread waiting for a conversion completion.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 97 of file adc.h.
Referenced by adcStopConversionI().
_adc_reset_s
#define _adc_reset_s (adcp) osalThreadResumeS(&(adcp)->thread, MSG_RESET)
Resumes a thread waiting for a conversion completion.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 107 of file adc.h.
Referenced by adcStopConversion().
_adc_wakeup_isr
#define _adc_wakeup_isr (adcp)
Value:
{                                             \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(adcp)->thread, MSG_OK);                               \
  osalSysUnlockFromISR();                                                   \
}
Wakes up the waiting thread.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 117 of file adc.h.
_adc_timeout_isr
#define _adc_timeout_isr (adcp)
Value:
{                                            \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(adcp)->thread, MSG_TIMEOUT);                          \
  osalSysUnlockFromISR();                                                   \
}
Wakes up the waiting thread with a timeout message.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 130 of file adc.h.
_adc_isr_half_code
#define _adc_isr_half_code (adcp)
Value:
{                                          \
  if ((adcp)->grpp->end_cb != NULL) {                                       \
    (adcp)->grpp->end_cb(adcp, (adcp)->samples, (adcp)->depth / 2);         \
  }                                                                         \
}
Common ISR code, half buffer event.
This code handles the portable part of the ISR code:
Callback invocation.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 155 of file adc.h.
_adc_isr_full_code
#define _adc_isr_full_code (adcp)
Common ISR code, full buffer event.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread wakeup, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 175 of file adc.h.
_adc_isr_error_code
#define _adc_isr_error_code (adcp, err)
Value:
{                                    \
  adc_lld_stop_conversion(adcp);                                            \
  if ((adcp)->grpp->error_cb != NULL) {                                     \
    (adcp)->state = ADC_ERROR;                                              \
    (adcp)->grpp->error_cb(adcp, err);                                      \
    if ((adcp)->state == ADC_ERROR)                                         \
      (adcp)->state = ADC_READY;                                            \
      (adcp)->grpp = NULL;                                                  \
  }                                                                         \
  else {                                                                    \
    (adcp)->state = ADC_READY;                                              \
    (adcp)->grpp = NULL;                                                    \
  }                                                                         \
  _adc_timeout_isr(adcp);                                                   \
}
Common ISR code, error event.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread timeout signaling, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] adcp pointer to the ADCDriver object
[in] err platform dependent error code
Function Class:
Not an API, this function is for internal use only.
Definition at line 226 of file adc.h.
STM32_ADCCLK_MIN
#define STM32_ADCCLK_MIN 600000
Minimum ADC clock frequency.
Definition at line 41 of file adc_lld.h.
STM32_ADCCLK_MAX
#define STM32_ADCCLK_MAX 36000000
Maximum ADC clock frequency.
Definition at line 47 of file adc_lld.h.
ADC_CHANNEL_IN0
#define ADC_CHANNEL_IN0 0
External analog input 0.
Definition at line 81 of file adc_lld.h.
ADC_CHANNEL_IN1
#define ADC_CHANNEL_IN1 1
External analog input 1.
Definition at line 82 of file adc_lld.h.
ADC_CHANNEL_IN2
#define ADC_CHANNEL_IN2 2
External analog input 2.
Definition at line 83 of file adc_lld.h.
ADC_CHANNEL_IN3
#define ADC_CHANNEL_IN3 3
External analog input 3.
Definition at line 84 of file adc_lld.h.
ADC_CHANNEL_IN4
#define ADC_CHANNEL_IN4 4
External analog input 4.
Definition at line 85 of file adc_lld.h.
ADC_CHANNEL_IN5
#define ADC_CHANNEL_IN5 5
External analog input 5.
Definition at line 86 of file adc_lld.h.
ADC_CHANNEL_IN6
#define ADC_CHANNEL_IN6 6
External analog input 6.
Definition at line 87 of file adc_lld.h.
ADC_CHANNEL_IN7
#define ADC_CHANNEL_IN7 7
External analog input 7.
Definition at line 88 of file adc_lld.h.
ADC_CHANNEL_IN8
#define ADC_CHANNEL_IN8 8
External analog input 8.
Definition at line 89 of file adc_lld.h.
ADC_CHANNEL_IN9
#define ADC_CHANNEL_IN9 9
External analog input 9.
Definition at line 90 of file adc_lld.h.
ADC_CHANNEL_IN10
#define ADC_CHANNEL_IN10 10
External analog input 10.
Definition at line 91 of file adc_lld.h.
ADC_CHANNEL_IN11
#define ADC_CHANNEL_IN11 11
External analog input 11.
Definition at line 92 of file adc_lld.h.
ADC_CHANNEL_IN12
#define ADC_CHANNEL_IN12 12
External analog input 12.
Definition at line 93 of file adc_lld.h.
ADC_CHANNEL_IN13
#define ADC_CHANNEL_IN13 13
External analog input 13.
Definition at line 94 of file adc_lld.h.
ADC_CHANNEL_IN14
#define ADC_CHANNEL_IN14 14
External analog input 14.
Definition at line 95 of file adc_lld.h.
ADC_CHANNEL_IN15
#define ADC_CHANNEL_IN15 15
External analog input 15.
Definition at line 96 of file adc_lld.h.
ADC_CHANNEL_SENSOR
#define ADC_CHANNEL_SENSOR 16
Internal temperature sensor.
Note
Available onADC1 only.
Definition at line 97 of file adc_lld.h.
ADC_CHANNEL_VREFINT
#define ADC_CHANNEL_VREFINT 17
Internal reference.
Note
Available onADC1 only.
Definition at line 100 of file adc_lld.h.
ADC_CHANNEL_VBAT
#define ADC_CHANNEL_VBAT 18
VBAT.
Note
Available onADC1 only.
Definition at line 103 of file adc_lld.h.
ADC_SAMPLE_3
#define ADC_SAMPLE_3 0
3 cycles sampling time.
Definition at line 112 of file adc_lld.h.
ADC_SAMPLE_15
#define ADC_SAMPLE_15 1
15 cycles sampling time.
Definition at line 113 of file adc_lld.h.
ADC_SAMPLE_28
#define ADC_SAMPLE_28 2
28 cycles sampling time.
Definition at line 114 of file adc_lld.h.
ADC_SAMPLE_56
#define ADC_SAMPLE_56 3
56 cycles sampling time.
Definition at line 115 of file adc_lld.h.
ADC_SAMPLE_84
#define ADC_SAMPLE_84 4
84 cycles sampling time.
Definition at line 116 of file adc_lld.h.
ADC_SAMPLE_112
#define ADC_SAMPLE_112 5
112 cycles sampling time.
Definition at line 117 of file adc_lld.h.
ADC_SAMPLE_144
#define ADC_SAMPLE_144 6
144 cycles sampling time.
Definition at line 118 of file adc_lld.h.
ADC_SAMPLE_480
#define ADC_SAMPLE_480 7
480 cycles sampling time.
Definition at line 119 of file adc_lld.h.
STM32_ADC_ADCPRE
#define STM32_ADC_ADCPRE ADC_CCR_ADCPRE_DIV2
ADC common clock divider.
Note
This setting is influenced by the VDDA voltage and other external conditions, please refer to the datasheet for more info.
See section 5.3.20 "12-bit ADC characteristics".
Definition at line 138 of file adc_lld.h.
Referenced by adc_lld_start().
STM32_ADC_USE_ADC1
#define STM32_ADC_USE_ADC1 FALSE
ADC1 driver enable switch.
If set to TRUE the support for ADC1 is included.
Note
The default is TRUE.
Definition at line 147 of file adc_lld.h.
STM32_ADC_USE_ADC2
#define STM32_ADC_USE_ADC2 FALSE
ADC2 driver enable switch.
If set to TRUE the support for ADC2 is included.
Note
The default is TRUE.
Definition at line 156 of file adc_lld.h.
STM32_ADC_USE_ADC3
#define STM32_ADC_USE_ADC3 FALSE
ADC3 driver enable switch.
If set to TRUE the support for ADC3 is included.
Note
The default is TRUE.
Definition at line 165 of file adc_lld.h.
STM32_ADC_ADC1_DMA_STREAM
#define STM32_ADC_ADC1_DMA_STREAM STM32_DMA_STREAM_ID(2, 4)
DMA stream used for ADC1 operations.
Definition at line 172 of file adc_lld.h.
Referenced by adc_lld_init().
STM32_ADC_ADC2_DMA_STREAM
#define STM32_ADC_ADC2_DMA_STREAM STM32_DMA_STREAM_ID(2, 2)
DMA stream used for ADC2 operations.
Definition at line 179 of file adc_lld.h.
STM32_ADC_ADC3_DMA_STREAM
#define STM32_ADC_ADC3_DMA_STREAM STM32_DMA_STREAM_ID(2, 1)
DMA stream used for ADC3 operations.
Definition at line 186 of file adc_lld.h.
STM32_ADC_ADC1_DMA_PRIORITY
#define STM32_ADC_ADC1_DMA_PRIORITY 2
ADC1 DMA priority (0..3|lowest..highest).
Definition at line 193 of file adc_lld.h.
STM32_ADC_ADC2_DMA_PRIORITY
#define STM32_ADC_ADC2_DMA_PRIORITY 2
ADC2 DMA priority (0..3|lowest..highest).
Definition at line 200 of file adc_lld.h.
STM32_ADC_ADC3_DMA_PRIORITY
#define STM32_ADC_ADC3_DMA_PRIORITY 2
ADC3 DMA priority (0..3|lowest..highest).
Definition at line 207 of file adc_lld.h.
STM32_ADC_IRQ_PRIORITY
#define STM32_ADC_IRQ_PRIORITY 5
ADC interrupt priority level setting.
Note
This setting is shared among ADC1, ADC2 and ADC3 because all ADCs share the same vector.
Definition at line 216 of file adc_lld.h.
STM32_ADC_ADC1_DMA_IRQ_PRIORITY
#define STM32_ADC_ADC1_DMA_IRQ_PRIORITY 5
ADC1 DMA interrupt priority level setting.
Definition at line 223 of file adc_lld.h.
Referenced by adc_lld_start().
STM32_ADC_ADC2_DMA_IRQ_PRIORITY
#define STM32_ADC_ADC2_DMA_IRQ_PRIORITY 5
ADC2 DMA interrupt priority level setting.
Definition at line 230 of file adc_lld.h.
Referenced by adc_lld_start().
STM32_ADC_ADC3_DMA_IRQ_PRIORITY
#define STM32_ADC_ADC3_DMA_IRQ_PRIORITY 5
ADC3 DMA interrupt priority level setting.
Definition at line 237 of file adc_lld.h.
Referenced by adc_lld_start().
ADC_SQR1_NUM_CH
#define ADC_SQR1_NUM_CH (n) (((n) - 1) << 20)
Number of channels in a conversion sequence.
Definition at line 487 of file adc_lld.h.
ADC_SQR3_SQ1_N
#define ADC_SQR3_SQ1_N (n) ((n) << 0)
1st channel in seq.
Definition at line 489 of file adc_lld.h.
ADC_SQR3_SQ2_N
#define ADC_SQR3_SQ2_N (n) ((n) << 5)
2nd channel in seq.
Definition at line 490 of file adc_lld.h.
ADC_SQR3_SQ3_N
#define ADC_SQR3_SQ3_N (n) ((n) << 10)
3rd channel in seq.
Definition at line 491 of file adc_lld.h.
ADC_SQR3_SQ4_N
#define ADC_SQR3_SQ4_N (n) ((n) << 15)
4th channel in seq.
Definition at line 492 of file adc_lld.h.
ADC_SQR3_SQ5_N
#define ADC_SQR3_SQ5_N (n) ((n) << 20)
5th channel in seq.
Definition at line 493 of file adc_lld.h.
ADC_SQR3_SQ6_N
#define ADC_SQR3_SQ6_N (n) ((n) << 25)
6th channel in seq.
Definition at line 494 of file adc_lld.h.
ADC_SQR2_SQ7_N
#define ADC_SQR2_SQ7_N (n) ((n) << 0)
7th channel in seq.
Definition at line 496 of file adc_lld.h.
ADC_SQR2_SQ8_N
#define ADC_SQR2_SQ8_N (n) ((n) << 5)
8th channel in seq.
Definition at line 497 of file adc_lld.h.
ADC_SQR2_SQ9_N
#define ADC_SQR2_SQ9_N (n) ((n) << 10)
9th channel in seq.
Definition at line 498 of file adc_lld.h.
ADC_SQR2_SQ10_N
#define ADC_SQR2_SQ10_N (n) ((n) << 15)
10th channel in seq.
Definition at line 499 of file adc_lld.h.
ADC_SQR2_SQ11_N
#define ADC_SQR2_SQ11_N (n) ((n) << 20)
11th channel in seq.
Definition at line 500 of file adc_lld.h.
ADC_SQR2_SQ12_N
#define ADC_SQR2_SQ12_N (n) ((n) << 25)
12th channel in seq.
Definition at line 501 of file adc_lld.h.
ADC_SQR1_SQ13_N
#define ADC_SQR1_SQ13_N (n) ((n) << 0)
13th channel in seq.
Definition at line 503 of file adc_lld.h.
ADC_SQR1_SQ14_N
#define ADC_SQR1_SQ14_N (n) ((n) << 5)
14th channel in seq.
Definition at line 504 of file adc_lld.h.
ADC_SQR1_SQ15_N
#define ADC_SQR1_SQ15_N (n) ((n) << 10)
15th channel in seq.
Definition at line 505 of file adc_lld.h.
ADC_SQR1_SQ16_N
#define ADC_SQR1_SQ16_N (n) ((n) << 15)
16th channel in seq.
Definition at line 506 of file adc_lld.h.
ADC_SMPR2_SMP_AN0
#define ADC_SMPR2_SMP_AN0 (n) ((n) << 0)
AN0 sampling time.
Definition at line 513 of file adc_lld.h.
ADC_SMPR2_SMP_AN1
#define ADC_SMPR2_SMP_AN1 (n) ((n) << 3)
AN1 sampling time.
Definition at line 514 of file adc_lld.h.
ADC_SMPR2_SMP_AN2
#define ADC_SMPR2_SMP_AN2 (n) ((n) << 6)
AN2 sampling time.
Definition at line 515 of file adc_lld.h.
ADC_SMPR2_SMP_AN3
#define ADC_SMPR2_SMP_AN3 (n) ((n) << 9)
AN3 sampling time.
Definition at line 516 of file adc_lld.h.
ADC_SMPR2_SMP_AN4
#define ADC_SMPR2_SMP_AN4 (n) ((n) << 12)
AN4 sampling time.
Definition at line 517 of file adc_lld.h.
ADC_SMPR2_SMP_AN5
#define ADC_SMPR2_SMP_AN5 (n) ((n) << 15)
AN5 sampling time.
Definition at line 518 of file adc_lld.h.
ADC_SMPR2_SMP_AN6
#define ADC_SMPR2_SMP_AN6 (n) ((n) << 18)
AN6 sampling time.
Definition at line 519 of file adc_lld.h.
ADC_SMPR2_SMP_AN7
#define ADC_SMPR2_SMP_AN7 (n) ((n) << 21)
AN7 sampling time.
Definition at line 520 of file adc_lld.h.
ADC_SMPR2_SMP_AN8
#define ADC_SMPR2_SMP_AN8 (n) ((n) << 24)
AN8 sampling time.
Definition at line 521 of file adc_lld.h.
ADC_SMPR2_SMP_AN9
#define ADC_SMPR2_SMP_AN9 (n) ((n) << 27)
AN9 sampling time.
Definition at line 522 of file adc_lld.h.
ADC_SMPR1_SMP_AN10
#define ADC_SMPR1_SMP_AN10 (n) ((n) << 0)
AN10 sampling time.
Definition at line 524 of file adc_lld.h.
ADC_SMPR1_SMP_AN11
#define ADC_SMPR1_SMP_AN11 (n) ((n) << 3)
AN11 sampling time.
Definition at line 525 of file adc_lld.h.
ADC_SMPR1_SMP_AN12
#define ADC_SMPR1_SMP_AN12 (n) ((n) << 6)
AN12 sampling time.
Definition at line 526 of file adc_lld.h.
ADC_SMPR1_SMP_AN13
#define ADC_SMPR1_SMP_AN13 (n) ((n) << 9)
AN13 sampling time.
Definition at line 527 of file adc_lld.h.
ADC_SMPR1_SMP_AN14
#define ADC_SMPR1_SMP_AN14 (n) ((n) << 12)
AN14 sampling time.
Definition at line 528 of file adc_lld.h.
ADC_SMPR1_SMP_AN15
#define ADC_SMPR1_SMP_AN15 (n) ((n) << 15)
AN15 sampling time.
Definition at line 529 of file adc_lld.h.
ADC_SMPR1_SMP_SENSOR
#define ADC_SMPR1_SMP_SENSOR (n) ((n) << 18)
Temperature Sensor sampling time.
Definition at line 530 of file adc_lld.h.
ADC_SMPR1_SMP_VREF
#define ADC_SMPR1_SMP_VREF (n) ((n) << 21)
Voltage Reference sampling time.
Definition at line 534 of file adc_lld.h.
ADC_SMPR1_SMP_VBAT
#define ADC_SMPR1_SMP_VBAT (n) ((n) << 24)
VBAT sampling time.
Definition at line 538 of file adc_lld.h.
Typedef Documentation
adcsample_t
typedef uint16_t adcsample_t
ADC sample data type.
Definition at line 305 of file adc_lld.h.
adc_channels_num_t
typedef uint16_t adc_channels_num_t
Channels number in a conversion group.
Definition at line 310 of file adc_lld.h.
ADCDriver
typedef struct ADCDriver ADCDriver
Type of a structure representing an ADC driver.
Definition at line 325 of file adc_lld.h.
adccallback_t
typedef void(* adccallback_t) (ADCDriver *adcp, adcsample_t *buffer, size_t n)
ADC notification callback type.
Parameters
[in] adcp pointer to the ADCDriver object triggering the callback
[in] buffer pointer to the most recent samples data
[in] n number of buffer rows available starting from buffer
Definition at line 335 of file adc_lld.h.
adcerrorcallback_t
typedef void(* adcerrorcallback_t) (ADCDriver *adcp, adcerror_t err)
ADC error callback type.
Parameters
[in] adcp pointer to the ADCDriver object triggering the callback
[in] err ADC error code
Definition at line 344 of file adc_lld.h.
Enumeration Type Documentation
adcstate_t
enum adcstate_t
Driver state machine possible states.
Enumerator
ADC_UNINIT
Not initialized.
ADC_STOP
Stopped.
ADC_READY
Ready.
ADC_ACTIVE
Converting.
ADC_COMPLETE
Conversion complete.
ADC_ERROR
Conversion error.
Definition at line 70 of file adc.h.
adcerror_t
enum adcerror_t
Possible ADC failure causes.
Note
Error codes are architecture dependent and should not relied upon.
Enumerator
ADC_ERR_DMAFAILURE
DMA operations failure.
ADC_ERR_OVERFLOW
ADC overflow condition.
Definition at line 317 of file adc_lld.h.
Function Documentation
adcInit()
void adcInit (void)
ADC Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file adc.c.
References adc_lld_init().
adcObjectInit()
void adcObjectInit (ADCDriver * adcp)
Initializes the standard part of a ADCDriver structure.
Parameters
[out] adcp pointer to the ADCDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file adc.c.
References ADC_STOP, ADCDriver::config, ADCDriver::depth, ADCDriver::grpp, ADCDriver::mutex, ADCDriver::samples, ADCDriver::state, and ADCDriver::thread.
Referenced by adc_lld_init().
adcStart()
void adcStart (ADCDriver * adcp, const ADCConfig * config)
Configures and activates the ADC peripheral.
Parameters
[in] adcp pointer to the ADCDriver object
[in] config pointer to the ADCConfig object. Depending on the implementation the value can be NULL.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 95 of file adc.c.
References adc_lld_start(), ADC_READY, ADC_STOP, ADCDriver::config, and ADCDriver::state.
adcStop()
void adcStop (ADCDriver * adcp)
Deactivates the ADC peripheral.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 115 of file adc.c.
References adc_lld_stop(), ADC_READY, ADC_STOP, and ADCDriver::state.
adcStartConversion()
void adcStartConversion (ADCDriver * adcp, const ADCConversionGroup * grpp, adcsample_t * samples, size_t depth)
Starts an ADC conversion.
Starts an asynchronous conversion operation.
Note
The buffer is organized as a matrix of M*N elements where M is the channels number configured into the conversion group and N is the buffer depth. The samples are sequentially written into the buffer with no gaps.
Parameters
[in] adcp pointer to the ADCDriver object
[in] grpp pointer to a ADCConversionGroup object
[out] samples pointer to the samples buffer
[in] depth buffer depth (matrix rows number). The buffer depth must be one or an even number.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 143 of file adc.c.
References adcStartConversionI().
adcStartConversionI()
void adcStartConversionI (ADCDriver * adcp, const ADCConversionGroup * grpp, adcsample_t * samples, size_t depth)
Starts an ADC conversion.
Starts an asynchronous conversion operation.
Postcondition
The callbacks associated to the conversion group will be invoked on buffer fill and error events.
Note
The buffer is organized as a matrix of M*N elements where M is the channels number configured into the conversion group and N is the buffer depth. The samples are sequentially written into the buffer with no gaps.
Parameters
[in] adcp pointer to the ADCDriver object
[in] grpp pointer to a ADCConversionGroup object
[out] samples pointer to the samples buffer
[in] depth buffer depth (matrix rows number). The buffer depth must be one or an even number.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 171 of file adc.c.
References ADC_ACTIVE, ADC_COMPLETE, ADC_ERROR, adc_lld_start_conversion(), ADC_READY, ADCDriver::depth, ADCDriver::grpp, ADCDriver::samples, and ADCDriver::state.
Referenced by adcConvert(), and adcStartConversion().
adcStopConversion()
void adcStopConversion (ADCDriver * adcp)
Stops an ongoing conversion.
This function stops the currently ongoing conversion and returns the driver in the ADC_READY state. If there was no conversion being processed then the function does nothing.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 201 of file adc.c.
References _adc_reset_s, ADC_ACTIVE, adc_lld_stop_conversion(), ADC_READY, ADCDriver::grpp, and ADCDriver::state.
adcStopConversionI()
void adcStopConversionI (ADCDriver * adcp)
Stops an ongoing conversion.
This function stops the currently ongoing conversion and returns the driver in the ADC_READY state. If there was no conversion being processed then the function does nothing.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 227 of file adc.c.
References _adc_reset_i, ADC_ACTIVE, ADC_COMPLETE, adc_lld_stop_conversion(), ADC_READY, ADCDriver::grpp, and ADCDriver::state.
adcConvert()
msg_t adcConvert (ADCDriver * adcp, const ADCConversionGroup * grpp, adcsample_t * samples, size_t depth)
Performs an ADC conversion.
Performs a synchronous conversion operation.
Note
The buffer is organized as a matrix of M*N elements where M is the channels number configured into the conversion group and N is the buffer depth. The samples are sequentially written into the buffer with no gaps.
Parameters
[in] adcp pointer to the ADCDriver object
[in] grpp pointer to a ADCConversionGroup object
[out] samples pointer to the samples buffer
[in] depth buffer depth (matrix rows number). The buffer depth must be one or an even number.
Returns
The operation result.
Return values
MSG_OK Conversion finished.
MSG_RESET The conversion has been stopped using acdStopConversion() or acdStopConversionI(), the result buffer may contain incorrect data.
MSG_TIMEOUT The conversion has been stopped because an hardware error.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 268 of file adc.c.
References adcStartConversionI(), and ADCDriver::thread.
adcAcquireBus()
void adcAcquireBus (ADCDriver * adcp)
Gains exclusive access to the ADC peripheral.
This function tries to gain ownership to the ADC bus, if the bus is already being used then the invoking thread is queued.
Precondition
In order to use this function the option ADC_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 295 of file adc.c.
References ADCDriver::mutex.
adcReleaseBus()
void adcReleaseBus (ADCDriver * adcp)
Releases exclusive access to the ADC peripheral.
Precondition
In order to use this function the option ADC_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 311 of file adc.c.
References ADCDriver::mutex.
adc_lld_serve_rx_interrupt()
static void adc_lld_serve_rx_interrupt (ADCDriver * adcp, uint32_t flags) static
ADC DMA ISR service routine.
Parameters
[in] adcp pointer to the ADCDriver object
[in] flags pre-shifted content of the ISR register
Definition at line 75 of file adc_lld.c.
Referenced by adc_lld_start().
OSAL_IRQ_HANDLER()
OSAL_IRQ_HANDLER (STM32_ADC_HANDLER)
ADC interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 111 of file adc_lld.c.
adc_lld_init()
void adc_lld_init (void)
Low level ADC driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 171 of file adc_lld.c.
References ADCDriver::adc, adcObjectInit(), ADCDriver::dmamode, ADCDriver::dmastp, STM32_ADC_ADC1_DMA_STREAM, and STM32_DMA_STREAM.
Referenced by adcInit().
adc_lld_start()
void adc_lld_start (ADCDriver * adcp)
Configures and activates the ADC peripheral.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 224 of file adc_lld.c.
References ADCDriver::adc, adc_lld_serve_rx_interrupt(), ADC_STOP, ADCDriver::dmastp, dmaStreamAllocate(), dmaStreamSetPeripheral, rccEnableADC1, rccEnableADC2, rccEnableADC3, ADCDriver::state, STM32_ADC_ADC1_DMA_IRQ_PRIORITY, STM32_ADC_ADC2_DMA_IRQ_PRIORITY, STM32_ADC_ADC3_DMA_IRQ_PRIORITY, and STM32_ADC_ADCPRE.
Referenced by adcStart().
adc_lld_stop()
void adc_lld_stop (ADCDriver * adcp)
Deactivates the ADC peripheral.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 287 of file adc_lld.c.
References ADCDriver::adc, ADC_READY, ADCDriver::dmastp, dmaStreamRelease(), rccDisableADC1, rccDisableADC2, rccDisableADC3, and ADCDriver::state.
Referenced by adcStop().
adc_lld_start_conversion()
void adc_lld_start_conversion (ADCDriver * adcp)
Starts an ADC conversion.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 319 of file adc_lld.c.
References ADCConversionGroup::circular, ADCDriver::dmamode, and ADCDriver::grpp.
Referenced by adcStartConversionI().
adc_lld_stop_conversion()
void adc_lld_stop_conversion (ADCDriver * adcp)
Stops an ongoing conversion.
Parameters
[in] adcp pointer to the ADCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 374 of file adc_lld.c.
References ADCDriver::adc, ADCDriver::dmastp, and dmaStreamDisable.
Referenced by adcStopConversion(), and adcStopConversionI().
adcSTM32EnableTSVREFE()
void adcSTM32EnableTSVREFE (void)
Enables the TSVREFE bit.
The TSVREFE bit is required in order to sample the internal temperature sensor and internal reference voltage.
Note
This is an STM32-only functionality.
Definition at line 388 of file adc_lld.c.
adcSTM32DisableTSVREFE()
void adcSTM32DisableTSVREFE (void)
Disables the TSVREFE bit.
The TSVREFE bit is required in order to sample the internal temperature sensor and internal reference voltage.
Note
This is an STM32-only functionality.
Definition at line 399 of file adc_lld.c.
adcSTM32EnableVBATE()
void adcSTM32EnableVBATE (void)
Enables the VBATE bit.
The VBATE bit is required in order to sample the VBAT channel.
Note
This is an STM32-only functionality.
This function is meant to be called after adcStart().
Definition at line 410 of file adc_lld.c.
adcSTM32DisableVBATE()
void adcSTM32DisableVBATE (void)
Disables the VBATE bit.
The VBATE bit is required in order to sample the VBAT channel.
Note
This is an STM32-only functionality.
This function is meant to be called after adcStart().
Definition at line 421 of file adc_lld.c.
Variable Documentation
ADCD1
ADCDriver ADCD1
ADC1 driver identifier.
Definition at line 48 of file adc_lld.c.
ADCD2
ADCDriver ADCD2
ADC2 driver identifier.
Definition at line 53 of file adc_lld.c.
ADCD3
ADCDriver ADCD3
ADC3 driver identifier.
Definition at line 58 of file adc_lld.c.