ChibiOS/HAL: COMMON_ARMCMx_NVIC
COMMON_ARMCMx_NVIC
Detailed Description
Macros
#define NVIC_PRIORITY_MASK(prio) ((prio) << (8U - (unsigned)__NVIC_PRIO_BITS))
Priority level to priority mask conversion macro.
System vectors numbers
#define HANDLER_MEM_MANAGE 0
#define HANDLER_BUS_FAULT 1
#define HANDLER_USAGE_FAULT 2
#define HANDLER_RESERVED_3 3
#define HANDLER_RESERVED_4 4
#define HANDLER_RESERVED_5 5
#define HANDLER_RESERVED_6 6
#define HANDLER_SVCALL 7
#define HANDLER_DEBUG_MONITOR 8
#define HANDLER_RESERVED_9 9
#define HANDLER_PENDSV 10
#define HANDLER_SYSTICK 11
Functions
void nvicEnableVector (uint32_t n, uint32_t prio)
Sets the priority of an interrupt handler and enables it.
void nvicDisableVector (uint32_t n)
Disables an interrupt handler.
void nvicSetSystemHandlerPriority (uint32_t handler, uint32_t prio)
Changes the priority of a system handler.
void nvicClearPending (uint32_t n)
Clears a pending interrupt source.
Macro Definition Documentation
HANDLER_MEM_MANAGE
#define HANDLER_MEM_MANAGE 0
MEM MANAGE vector id.
Definition at line 36 of file nvic.h.
HANDLER_BUS_FAULT
#define HANDLER_BUS_FAULT 1
BUS FAULT vector id.
Definition at line 37 of file nvic.h.
HANDLER_USAGE_FAULT
#define HANDLER_USAGE_FAULT 2
USAGE FAULT vector id.
Definition at line 38 of file nvic.h.
HANDLER_SVCALL
#define HANDLER_SVCALL 7
SVCALL vector id.
Definition at line 43 of file nvic.h.
HANDLER_DEBUG_MONITOR
#define HANDLER_DEBUG_MONITOR 8
DEBUG MONITOR vector id.
Definition at line 44 of file nvic.h.
HANDLER_PENDSV
#define HANDLER_PENDSV 10
PENDSV vector id.
Definition at line 46 of file nvic.h.
HANDLER_SYSTICK
#define HANDLER_SYSTICK 11
SYS TCK vector id.
Definition at line 47 of file nvic.h.
NVIC_PRIORITY_MASK
#define NVIC_PRIORITY_MASK (prio) ((prio) << (8U - (unsigned)__NVIC_PRIO_BITS))
Priority level to priority mask conversion macro.
Definition at line 69 of file nvic.h.
Referenced by nvicEnableVector(), and nvicSetSystemHandlerPriority().
Function Documentation
nvicEnableVector()
void nvicEnableVector (uint32_t n, uint32_t prio)
Sets the priority of an interrupt handler and enables it.
Parameters
[in] n the interrupt number
[in] prio the interrupt priority
Definition at line 57 of file nvic.c.
References NVIC_PRIORITY_MASK.
Referenced by can_lld_start(), ext_lld_exti_irq_enable(), gpt_lld_start(), icu_lld_start(), pwm_lld_start(), sd_lld_start(), uart_lld_start(), and usb_lld_start().
nvicDisableVector()
void nvicDisableVector (uint32_t n)
Disables an interrupt handler.
Parameters
[in] n the interrupt number
Definition at line 74 of file nvic.c.
Referenced by can_lld_stop(), dmaStreamRelease(), ext_lld_exti_irq_disable(), gpt_lld_stop(), i2c_lld_stop(), icu_lld_stop(), mac_lld_stop(), pwm_lld_stop(), sd_lld_stop(), sdc_lld_stop(), and uart_lld_stop().
nvicSetSystemHandlerPriority()
void nvicSetSystemHandlerPriority (uint32_t handler, uint32_t prio)
Changes the priority of a system handler.
Parameters
[in] handler the system handler number
[in] prio the system handler priority
Definition at line 90 of file nvic.c.
References NVIC_PRIORITY_MASK.
nvicClearPending()
void nvicClearPending (uint32_t n)
Clears a pending interrupt source.
Parameters
[in] n the interrupt number
Definition at line 109 of file nvic.c.