ChibiOS/HAL: EXT Driver
EXT Driver
HAL » Normal Drivers
Generic EXT Driver.
Detailed Description
Generic EXT Driver.
This module implements a generic EXT (EXTernal) driver.
Precondition
In order to use the EXT driver the HAL_USE_EXT option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
EXT Operations.
This driver abstracts generic external interrupt sources, a callback is invoked when a programmable transition is detected on one of the configured channels. Several channel modes are possible.
EXT_CH_MODE_DISABLED, channel not used.
EXT_CH_MODE_RISING_EDGE, callback on a rising edge.
EXT_CH_MODE_FALLING_EDGE, callback on a falling edge.
EXT_CH_MODE_BOTH_EDGES, callback on a both edges.
Macros
#define EXT_MAX_CHANNELS STM32_EXTI_NUM_LINES
Available number of EXT channels.
EXT channel modes
#define EXT_CH_MODE_EDGES_MASK 3U
Mask of edges field.
#define EXT_CH_MODE_DISABLED 0U
Channel disabled.
#define EXT_CH_MODE_RISING_EDGE 1U
Rising edge callback.
#define EXT_CH_MODE_FALLING_EDGE 2U
Falling edge callback.
#define EXT_CH_MODE_BOTH_EDGES 3U
Both edges callback.
#define EXT_CH_MODE_AUTOSTART 4U
Channel started automatically on driver start.
Macro Functions
#define extChannelEnableI(extp, channel) ext_lld_channel_enable(extp, channel)
Enables an EXT channel.
#define extChannelDisableI(extp, channel) ext_lld_channel_disable(extp, channel)
Disables an EXT channel.
#define extSetChannelMode(extp, channel, extcp)
Changes the operation mode of a channel.
Configuration options
#define STM32_EXT_EXTI0_IRQ_PRIORITY 6
EXTI0 interrupt priority level setting.
#define STM32_EXT_EXTI1_IRQ_PRIORITY 6
EXTI1 interrupt priority level setting.
#define STM32_EXT_EXTI2_IRQ_PRIORITY 6
EXTI2 interrupt priority level setting.
#define STM32_EXT_EXTI3_IRQ_PRIORITY 6
EXTI3 interrupt priority level setting.
#define STM32_EXT_EXTI4_IRQ_PRIORITY 6
EXTI4 interrupt priority level setting.
#define STM32_EXT_EXTI5_9_IRQ_PRIORITY 6
EXTI9..5 interrupt priority level setting.
#define STM32_EXT_EXTI10_15_IRQ_PRIORITY 6
EXTI15..10 interrupt priority level setting.
#define STM32_EXT_EXTI16_IRQ_PRIORITY 6
EXTI16 interrupt priority level setting.
#define STM32_EXT_EXTI17_IRQ_PRIORITY 6
EXTI17 interrupt priority level setting.
#define STM32_EXT_EXTI18_IRQ_PRIORITY 6
EXTI18 interrupt priority level setting.
#define STM32_EXT_EXTI19_IRQ_PRIORITY 6
EXTI19 interrupt priority level setting.
#define STM32_EXT_EXTI20_IRQ_PRIORITY 6
EXTI20 interrupt priority level setting.
#define STM32_EXT_EXTI21_IRQ_PRIORITY 6
EXTI21 interrupt priority level setting.
#define STM32_EXT_EXTI22_IRQ_PRIORITY 6
EXTI22 interrupt priority level setting.
STM32-specific EXT channel modes
#define EXT_MODE_GPIO_MASK 0xF0
Port field mask.
#define EXT_MODE_GPIO_OFF 4
Port field offset.
#define EXT_MODE_GPIOA 0x00
GPIOA identifier.
#define EXT_MODE_GPIOB 0x10
GPIOB identifier.
#define EXT_MODE_GPIOC 0x20
GPIOC identifier.
#define EXT_MODE_GPIOD 0x30
GPIOD identifier.
#define EXT_MODE_GPIOE 0x40
GPIOE identifier.
#define EXT_MODE_GPIOF 0x50
GPIOF identifier.
#define EXT_MODE_GPIOG 0x60
GPIOG identifier.
#define EXT_MODE_GPIOH 0x70
GPIOH identifier.
#define EXT_MODE_GPIOI 0x80
GPIOI identifier.
Typedefs
typedef struct EXTDriver EXTDriver
Type of a structure representing a EXT driver.
typedef uint32_t expchannel_t
EXT channel identifier.
typedef void(* extcallback_t) (EXTDriver *extp, expchannel_t channel)
Type of an EXT generic notification callback.
Data Structures
struct EXTChannelConfig
Channel configuration structure.
struct EXTConfig
Driver configuration structure.
struct EXTDriver
Structure representing an EXT driver.
Functions
void extInit (void)
EXT Driver initialization.
void extObjectInit (EXTDriver *extp)
Initializes the standard part of a EXTDriver structure.
void extStart (EXTDriver *extp, const EXTConfig *config)
Configures and activates the EXT peripheral.
void extStop (EXTDriver *extp)
Deactivates the EXT peripheral.
void extChannelEnable (EXTDriver *extp, expchannel_t channel)
Enables an EXT channel.
void extChannelDisable (EXTDriver *extp, expchannel_t channel)
Disables an EXT channel.
void extSetChannelModeI (EXTDriver *extp, expchannel_t channel, const EXTChannelConfig *extcp)
Changes the operation mode of a channel.
void ext_lld_init (void)
Low level EXT driver initialization.
void ext_lld_start (EXTDriver *extp)
Configures and activates the EXT peripheral.
void ext_lld_stop (EXTDriver *extp)
Deactivates the EXT peripheral.
void ext_lld_channel_enable (EXTDriver *extp, expchannel_t channel)
Enables an EXT channel.
void ext_lld_channel_disable (EXTDriver *extp, expchannel_t channel)
Disables an EXT channel.
OSAL_IRQ_HANDLER (Vector58)
EXTI[0] interrupt handler.
OSAL_IRQ_HANDLER (Vector5C)
EXTI[1] interrupt handler.
OSAL_IRQ_HANDLER (Vector60)
EXTI[2] interrupt handler.
OSAL_IRQ_HANDLER (Vector64)
EXTI[3] interrupt handler.
OSAL_IRQ_HANDLER (Vector68)
EXTI[4] interrupt handler.
OSAL_IRQ_HANDLER (Vector9C)
EXTI[5]...EXTI[9] interrupt handler.
OSAL_IRQ_HANDLER (VectorE0)
EXTI[10]...EXTI[15] interrupt handler.
OSAL_IRQ_HANDLER (Vector44)
EXTI[16] interrupt handler (PVD).
OSAL_IRQ_HANDLER (VectorE4)
EXTI[17] interrupt handler (RTC_ALARM).
OSAL_IRQ_HANDLER (VectorE8)
EXTI[18] interrupt handler (OTG_FS_WKUP).
OSAL_IRQ_HANDLER (Vector138)
EXTI[19] interrupt handler (ETH_WKUP).
OSAL_IRQ_HANDLER (Vector170)
EXTI[20] interrupt handler (OTG_HS_WKUP).
OSAL_IRQ_HANDLER (Vector48)
EXTI[21] interrupt handler (TAMPER_STAMP).
OSAL_IRQ_HANDLER (Vector4C)
EXTI[22] interrupt handler (RTC_WKUP).
void ext_lld_exti_irq_enable (void)
Enables EXTI IRQ sources.
void ext_lld_exti_irq_disable (void)
Disables EXTI IRQ sources.
Enumerations
enum extstate_t { EXT_UNINIT = 0, EXT_STOP = 1, EXT_ACTIVE = 2 }
Driver state machine possible states.
Variables
EXTDriver EXTD1
EXTD1 driver identifier.
Macro Definition Documentation
EXT_CH_MODE_EDGES_MASK
#define EXT_CH_MODE_EDGES_MASK 3U
Mask of edges field.
Definition at line 38 of file ext.h.
Referenced by extChannelDisable(), and extChannelEnable().
EXT_CH_MODE_DISABLED
#define EXT_CH_MODE_DISABLED 0U
Channel disabled.
Definition at line 39 of file ext.h.
Referenced by extChannelDisable(), and extChannelEnable().
EXT_CH_MODE_RISING_EDGE
#define EXT_CH_MODE_RISING_EDGE 1U
Rising edge callback.
Definition at line 40 of file ext.h.
EXT_CH_MODE_FALLING_EDGE
#define EXT_CH_MODE_FALLING_EDGE 2U
Falling edge callback.
Definition at line 41 of file ext.h.
EXT_CH_MODE_BOTH_EDGES
#define EXT_CH_MODE_BOTH_EDGES 3U
Both edges callback.
Definition at line 42 of file ext.h.
EXT_CH_MODE_AUTOSTART
#define EXT_CH_MODE_AUTOSTART 4U
Channel started automatically on driver start.
Definition at line 44 of file ext.h.
Referenced by ext_lld_start().
extChannelEnableI
#define extChannelEnableI (extp, channel) ext_lld_channel_enable(extp, channel)
Enables an EXT channel.
Parameters
[in] extp pointer to the EXTDriver object
[in] channel channel to be enabled
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 93 of file ext.h.
Referenced by extChannelEnable().
extChannelDisableI
#define extChannelDisableI (extp, channel) ext_lld_channel_disable(extp, channel)
Disables an EXT channel.
Parameters
[in] extp pointer to the EXTDriver object
[in] channel channel to be disabled
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 103 of file ext.h.
Referenced by extChannelDisable().
extSetChannelMode
#define extSetChannelMode (extp, channel, extcp)
Value:
{                           \
  osalSysLock();                                                            \
  extSetChannelModeI(extp, channel, extcp);                                 \
  osalSysUnlock();                                                          \
}
Changes the operation mode of a channel.
Note
This function attempts to write over the current configuration structure that must have been not declared constant. This violates the const qualifier in extStart() but it is intentional. This function cannot be used if the configuration structure is declared const.
Parameters
[in] extp pointer to the EXTDriver object
[in] channel channel to be changed
[in] extcp new configuration for the channel
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 119 of file ext.h.
STM32_EXT_EXTI0_IRQ_PRIORITY
#define STM32_EXT_EXTI0_IRQ_PRIORITY 6
EXTI0 interrupt priority level setting.
Definition at line 46 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI1_IRQ_PRIORITY
#define STM32_EXT_EXTI1_IRQ_PRIORITY 6
EXTI1 interrupt priority level setting.
Definition at line 53 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI2_IRQ_PRIORITY
#define STM32_EXT_EXTI2_IRQ_PRIORITY 6
EXTI2 interrupt priority level setting.
Definition at line 60 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI3_IRQ_PRIORITY
#define STM32_EXT_EXTI3_IRQ_PRIORITY 6
EXTI3 interrupt priority level setting.
Definition at line 67 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI4_IRQ_PRIORITY
#define STM32_EXT_EXTI4_IRQ_PRIORITY 6
EXTI4 interrupt priority level setting.
Definition at line 74 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI5_9_IRQ_PRIORITY
#define STM32_EXT_EXTI5_9_IRQ_PRIORITY 6
EXTI9..5 interrupt priority level setting.
Definition at line 81 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI10_15_IRQ_PRIORITY
#define STM32_EXT_EXTI10_15_IRQ_PRIORITY 6
EXTI15..10 interrupt priority level setting.
Definition at line 88 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI16_IRQ_PRIORITY
#define STM32_EXT_EXTI16_IRQ_PRIORITY 6
EXTI16 interrupt priority level setting.
Definition at line 95 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI17_IRQ_PRIORITY
#define STM32_EXT_EXTI17_IRQ_PRIORITY 6
EXTI17 interrupt priority level setting.
Definition at line 102 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI18_IRQ_PRIORITY
#define STM32_EXT_EXTI18_IRQ_PRIORITY 6
EXTI18 interrupt priority level setting.
Definition at line 109 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI19_IRQ_PRIORITY
#define STM32_EXT_EXTI19_IRQ_PRIORITY 6
EXTI19 interrupt priority level setting.
Definition at line 116 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI20_IRQ_PRIORITY
#define STM32_EXT_EXTI20_IRQ_PRIORITY 6
EXTI20 interrupt priority level setting.
Definition at line 123 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI21_IRQ_PRIORITY
#define STM32_EXT_EXTI21_IRQ_PRIORITY 6
EXTI21 interrupt priority level setting.
Definition at line 130 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
STM32_EXT_EXTI22_IRQ_PRIORITY
#define STM32_EXT_EXTI22_IRQ_PRIORITY 6
EXTI22 interrupt priority level setting.
Definition at line 137 of file ext_lld_isr.h.
Referenced by ext_lld_exti_irq_enable().
EXT_MAX_CHANNELS
#define EXT_MAX_CHANNELS STM32_EXTI_NUM_LINES
Available number of EXT channels.
Definition at line 39 of file ext_lld.h.
Referenced by ext_lld_start(), extChannelDisable(), extChannelEnable(), and extSetChannelModeI().
EXT_MODE_GPIO_MASK
#define EXT_MODE_GPIO_MASK 0xF0
Port field mask.
Definition at line 45 of file ext_lld.h.
Referenced by ext_lld_channel_enable().
EXT_MODE_GPIO_OFF
#define EXT_MODE_GPIO_OFF 4
Port field offset.
Definition at line 46 of file ext_lld.h.
Referenced by ext_lld_channel_enable().
EXT_MODE_GPIOA
#define EXT_MODE_GPIOA 0x00
GPIOA identifier.
Definition at line 47 of file ext_lld.h.
EXT_MODE_GPIOB
#define EXT_MODE_GPIOB 0x10
GPIOB identifier.
Definition at line 48 of file ext_lld.h.
EXT_MODE_GPIOC
#define EXT_MODE_GPIOC 0x20
GPIOC identifier.
Definition at line 49 of file ext_lld.h.
EXT_MODE_GPIOD
#define EXT_MODE_GPIOD 0x30
GPIOD identifier.
Definition at line 50 of file ext_lld.h.
EXT_MODE_GPIOE
#define EXT_MODE_GPIOE 0x40
GPIOE identifier.
Definition at line 51 of file ext_lld.h.
EXT_MODE_GPIOF
#define EXT_MODE_GPIOF 0x50
GPIOF identifier.
Definition at line 52 of file ext_lld.h.
EXT_MODE_GPIOG
#define EXT_MODE_GPIOG 0x60
GPIOG identifier.
Definition at line 53 of file ext_lld.h.
EXT_MODE_GPIOH
#define EXT_MODE_GPIOH 0x70
GPIOH identifier.
Definition at line 54 of file ext_lld.h.
EXT_MODE_GPIOI
#define EXT_MODE_GPIOI 0x80
GPIOI identifier.
Definition at line 55 of file ext_lld.h.
Typedef Documentation
EXTDriver
typedef struct EXTDriver EXTDriver
Type of a structure representing a EXT driver.
Definition at line 73 of file ext.h.
expchannel_t
typedef uint32_t expchannel_t
EXT channel identifier.
Definition at line 73 of file ext_lld.h.
extcallback_t
typedef void(* extcallback_t) (EXTDriver *extp, expchannel_t channel)
Type of an EXT generic notification callback.
Parameters
[in] extp pointer to the EXPDriver object triggering the callback
Definition at line 81 of file ext_lld.h.
Enumeration Type Documentation
extstate_t
enum extstate_t
Driver state machine possible states.
Enumerator
EXT_UNINIT
Not initialized.
EXT_STOP
Stopped.
EXT_ACTIVE
Active.
Definition at line 64 of file ext.h.
Function Documentation
extInit()
void extInit (void)
EXT Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file ext.c.
References ext_lld_init().
extObjectInit()
void extObjectInit (EXTDriver * extp)
Initializes the standard part of a EXTDriver structure.
Parameters
[out] extp pointer to the EXTDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file ext.c.
References EXTDriver::config, EXT_STOP, and EXTDriver::state.
Referenced by ext_lld_init().
extStart()
void extStart (EXTDriver * extp, const EXTConfig * config)
Configures and activates the EXT peripheral.
Postcondition
After activation all EXT channels are in the disabled state, use extChannelEnable() in order to activate them.
Parameters
[in] extp pointer to the EXTDriver object
[in] config pointer to the EXTConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 84 of file ext.c.
References EXTDriver::config, EXT_ACTIVE, ext_lld_start(), EXT_STOP, and EXTDriver::state.
extStop()
void extStop (EXTDriver * extp)
Deactivates the EXT peripheral.
Parameters
[in] extp pointer to the EXTDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 104 of file ext.c.
References EXT_ACTIVE, ext_lld_stop(), EXT_STOP, and EXTDriver::state.
extChannelEnable()
void extChannelEnable (EXTDriver * extp, expchannel_t channel)
Enables an EXT channel.
Precondition
The channel must not be in EXT_CH_MODE_DISABLED mode.
Parameters
[in] extp pointer to the EXTDriver object
[in] channel channel to be enabled
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 125 of file ext.c.
References EXTConfig::channels, EXTDriver::config, EXT_ACTIVE, EXT_CH_MODE_DISABLED, EXT_CH_MODE_EDGES_MASK, EXT_MAX_CHANNELS, extChannelEnableI, EXTChannelConfig::mode, and EXTDriver::state.
extChannelDisable()
void extChannelDisable (EXTDriver * extp, expchannel_t channel)
Disables an EXT channel.
Precondition
The channel must not be in EXT_CH_MODE_DISABLED mode.
Parameters
[in] extp pointer to the EXTDriver object
[in] channel channel to be disabled
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 147 of file ext.c.
References EXTConfig::channels, EXTDriver::config, EXT_ACTIVE, EXT_CH_MODE_DISABLED, EXT_CH_MODE_EDGES_MASK, EXT_MAX_CHANNELS, extChannelDisableI, EXTChannelConfig::mode, and EXTDriver::state.
extSetChannelModeI()
void extSetChannelModeI (EXTDriver * extp, expchannel_t channel, const EXTChannelConfig * extcp)
Changes the operation mode of a channel.
Note
This function attempts to write over the current configuration structure that must have been not declared constant. This violates the const qualifier in extStart() but it is intentional.
This function cannot be used if the configuration structure is declared const.
The effect of this function on constant configuration structures is not defined.
Parameters
[in] extp pointer to the EXTDriver object
[in] channel channel to be changed
[in] extcp new configuration for the channel
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 177 of file ext.c.
References EXTConfig::channels, EXTDriver::config, EXT_ACTIVE, ext_lld_channel_enable(), EXT_MAX_CHANNELS, and EXTDriver::state.
ext_lld_init()
void ext_lld_init (void)
Low level EXT driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 72 of file ext_lld.c.
References extObjectInit().
Referenced by extInit().
ext_lld_start()
void ext_lld_start (EXTDriver * extp)
Configures and activates the EXT peripheral.
Parameters
[in] extp pointer to the EXTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 85 of file ext_lld.c.
References EXTConfig::channels, EXTDriver::config, EXT_CH_MODE_AUTOSTART, ext_lld_channel_disable(), ext_lld_channel_enable(), ext_lld_exti_irq_enable(), EXT_MAX_CHANNELS, EXT_STOP, EXTChannelConfig::mode, and EXTDriver::state.
Referenced by extStart().
ext_lld_stop()
void ext_lld_stop (EXTDriver * extp)
Deactivates the EXT peripheral.
Parameters
[in] extp pointer to the EXTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 106 of file ext_lld.c.
References EXT_ACTIVE, ext_lld_exti_irq_disable(), and EXTDriver::state.
Referenced by extStop().
ext_lld_channel_enable()
void ext_lld_channel_enable (EXTDriver * extp, expchannel_t channel)
Enables an EXT channel.
Parameters
[in] extp pointer to the EXTDriver object
[in] channel channel to be enabled
Function Class:
Not an API, this function is for internal use only.
Definition at line 128 of file ext_lld.c.
References EXTConfig::channels, EXTDriver::config, EXT_MODE_GPIO_MASK, EXT_MODE_GPIO_OFF, and EXTChannelConfig::mode.
Referenced by ext_lld_start(), and extSetChannelModeI().
ext_lld_channel_disable()
void ext_lld_channel_disable (EXTDriver * extp, expchannel_t channel)
Disables an EXT channel.
Parameters
[in] extp pointer to the EXTDriver object
[in] channel channel to be disabled
Function Class:
Not an API, this function is for internal use only.
Definition at line 212 of file ext_lld.c.
Referenced by ext_lld_start().
OSAL_IRQ_HANDLER() [1/14]
OSAL_IRQ_HANDLER (Vector58)
EXTI[0] interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 56 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [2/14]
OSAL_IRQ_HANDLER (Vector5C)
EXTI[1] interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 75 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [3/14]
OSAL_IRQ_HANDLER (Vector60)
EXTI[2] interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 94 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [4/14]
OSAL_IRQ_HANDLER (Vector64)
EXTI[3] interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 113 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [5/14]
OSAL_IRQ_HANDLER (Vector68)
EXTI[4] interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 132 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [6/14]
OSAL_IRQ_HANDLER (Vector9C)
EXTI[5]...EXTI[9] interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 151 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [7/14]
OSAL_IRQ_HANDLER (VectorE0)
EXTI[10]...EXTI[15] interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 179 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [8/14]
OSAL_IRQ_HANDLER (Vector44)
EXTI[16] interrupt handler (PVD).
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 209 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [9/14]
OSAL_IRQ_HANDLER (VectorE4)
EXTI[17] interrupt handler (RTC_ALARM).
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 228 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [10/14]
OSAL_IRQ_HANDLER (VectorE8)
EXTI[18] interrupt handler (OTG_FS_WKUP).
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 247 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [11/14]
OSAL_IRQ_HANDLER (Vector138)
EXTI[19] interrupt handler (ETH_WKUP).
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 267 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [12/14]
OSAL_IRQ_HANDLER (Vector170)
EXTI[20] interrupt handler (OTG_HS_WKUP).
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 288 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [13/14]
OSAL_IRQ_HANDLER (Vector48)
EXTI[21] interrupt handler (TAMPER_STAMP).
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 309 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
OSAL_IRQ_HANDLER() [14/14]
OSAL_IRQ_HANDLER (Vector4C)
EXTI[22] interrupt handler (RTC_WKUP).
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 329 of file ext_lld_isr.c.
References EXTChannelConfig::cb, EXTConfig::channels, EXTDriver::config, and EXTD1.
ext_lld_exti_irq_enable()
void ext_lld_exti_irq_enable (void)
Enables EXTI IRQ sources.
Function Class:
Not an API, this function is for internal use only.
Definition at line 352 of file ext_lld_isr.c.
References nvicEnableVector(), STM32_EXT_EXTI0_IRQ_PRIORITY, STM32_EXT_EXTI10_15_IRQ_PRIORITY, STM32_EXT_EXTI16_IRQ_PRIORITY, STM32_EXT_EXTI17_IRQ_PRIORITY, STM32_EXT_EXTI18_IRQ_PRIORITY, STM32_EXT_EXTI19_IRQ_PRIORITY, STM32_EXT_EXTI1_IRQ_PRIORITY, STM32_EXT_EXTI20_IRQ_PRIORITY, STM32_EXT_EXTI21_IRQ_PRIORITY, STM32_EXT_EXTI22_IRQ_PRIORITY, STM32_EXT_EXTI2_IRQ_PRIORITY, STM32_EXT_EXTI3_IRQ_PRIORITY, STM32_EXT_EXTI4_IRQ_PRIORITY, and STM32_EXT_EXTI5_9_IRQ_PRIORITY.
Referenced by ext_lld_start().
ext_lld_exti_irq_disable()
void ext_lld_exti_irq_disable (void)
Disables EXTI IRQ sources.
Function Class:
Not an API, this function is for internal use only.
Definition at line 381 of file ext_lld_isr.c.
References nvicDisableVector().
Referenced by ext_lld_stop().
Variable Documentation
EXTD1
EXTDriver EXTD1
EXTD1 driver identifier.
Definition at line 49 of file ext_lld.c.
Referenced by OSAL_IRQ_HANDLER().