ChibiOS/HAL: SDC Driver
SDC Driver
HAL » Normal Drivers
Generic SD Card Driver.
Detailed Description
Generic SD Card Driver.
This module implements a generic SDC (Secure Digital Card) driver.
Precondition
In order to use the SDC driver the HAL_USE_SDC option must be enabled in halconf.h.
Driver State Machine
This driver implements a state machine internally, see the Abstract I/O Block Device module documentation for details.
Driver Operations
This driver allows to read or write single or multiple 512 bytes blocks on a SD Card.
Macros
#define STM32_SDIO_ICR_ALL_FLAGS
Value to clear all interrupts flag at once.
#define STM32_SDIO_STA_ERROR_MASK
Mask of error flags in STA register.
#define STM32_SDC_WRITE_TIMEOUT
SDIO data timeouts in SDIO clock cycles.
#define _sdc_driver_methods _mmcsd_block_device_methods
SDCDriver specific methods.
SD card types
#define SDC_MODE_CARDTYPE_MASK 0xFU
#define SDC_MODE_CARDTYPE_SDV11 0U
#define SDC_MODE_CARDTYPE_SDV20 1U
#define SDC_MODE_CARDTYPE_MMC 2U
#define SDC_MODE_HIGH_CAPACITY 0x10U
SDC bus error conditions
#define SDC_NO_ERROR 0U
#define SDC_CMD_CRC_ERROR 1U
#define SDC_DATA_CRC_ERROR 2U
#define SDC_DATA_TIMEOUT 4U
#define SDC_COMMAND_TIMEOUT 8U
#define SDC_TX_UNDERRUN 16U
#define SDC_RX_OVERRUN 32U
#define SDC_STARTBIT_ERROR 64U
#define SDC_OVERFLOW_ERROR 128U
#define SDC_UNHANDLED_ERROR 0xFFFFFFFFU
SDC configuration options
#define SDC_INIT_RETRY 100
Number of initialization attempts before rejecting the card.
#define SDC_MMC_SUPPORT FALSE
Include support for MMC cards.
#define SDC_NICE_WAITING TRUE
Delays insertions.
Macro Functions
#define sdcIsCardInserted(sdcp) (sdc_lld_is_card_inserted(sdcp))
Returns the card insertion status.
#define sdcIsWriteProtected(sdcp) (sdc_lld_is_write_protected(sdcp))
Returns the write protect status.
Configuration options
#define STM32_SDC_SDIO_DMA_PRIORITY 3
SDIO DMA priority (0..3|lowest..highest).
#define STM32_SDC_SDIO_IRQ_PRIORITY 9
SDIO interrupt priority level setting.
#define STM32_SDC_WRITE_TIMEOUT_MS 250
Write timeout in milliseconds.
#define STM32_SDC_READ_TIMEOUT_MS 25
Read timeout in milliseconds.
#define STM32_SDC_CLOCK_ACTIVATION_DELAY 10
Card clock activation delay in milliseconds.
#define STM32_SDC_SDIO_UNALIGNED_SUPPORT TRUE
Support for unaligned transfers.
Typedefs
typedef uint32_t sdcmode_t
Type of card flags.
typedef uint32_t sdcflags_t
SDC Driver condition flags type.
typedef struct SDCDriver SDCDriver
Type of a structure representing an SDC driver.
Data Structures
struct SDCConfig
Driver configuration structure.
struct SDCDriverVMT
SDCDriver virtual methods table.
struct SDCDriver
Structure representing an SDC driver.
Functions
static bool mode_detect (SDCDriver *sdcp)
Detects card mode.
static bool mmc_init (SDCDriver *sdcp)
Init procedure for MMC.
static bool sdc_init (SDCDriver *sdcp)
Init procedure for SDC.
static uint32_t mmc_cmd6_construct (mmc_switch_t access, uint32_t idx, uint32_t value, uint32_t cmd_set)
Constructs CMD6 argument for MMC.
static uint32_t sdc_cmd6_construct (sd_switch_t mode, sd_switch_function_t function, uint32_t value)
Constructs CMD6 argument for SDC.
static uint16_t sdc_cmd6_extract_info (sd_switch_function_t function, const uint8_t *buf)
Extracts information from CMD6 answer.
static bool sdc_cmd6_check_status (sd_switch_function_t function, const uint8_t *buf)
Checks status after switching using CMD6.
static bool sdc_detect_bus_clk (SDCDriver *sdcp, sdcbusclk_t *clk)
Reads supported bus clock and switch SDC to appropriate mode.
static bool mmc_detect_bus_clk (SDCDriver *sdcp, sdcbusclk_t *clk)
Reads supported bus clock and switch MMC to appropriate mode.
static bool detect_bus_clk (SDCDriver *sdcp, sdcbusclk_t *clk)
Reads supported bus clock and switch card to appropriate mode.
static bool sdc_set_bus_width (SDCDriver *sdcp)
Sets bus width for SDC.
static bool mmc_set_bus_width (SDCDriver *sdcp)
Sets bus width for MMC.
bool _sdc_wait_for_transfer_state (SDCDriver *sdcp)
Wait for the card to complete pending operations.
void sdcInit (void)
SDC Driver initialization.
void sdcObjectInit (SDCDriver *sdcp)
Initializes the standard part of a SDCDriver structure.
void sdcStart (SDCDriver *sdcp, const SDCConfig *config)
Configures and activates the SDC peripheral.
void sdcStop (SDCDriver *sdcp)
Deactivates the SDC peripheral.
bool sdcConnect (SDCDriver *sdcp)
Performs the initialization procedure on the inserted card.
bool sdcDisconnect (SDCDriver *sdcp)
Brings the driver in a state safe for card removal.
bool sdcRead (SDCDriver *sdcp, uint32_t startblk, uint8_t *buf, uint32_t n)
Reads one or more blocks.
bool sdcWrite (SDCDriver *sdcp, uint32_t startblk, const uint8_t *buf, uint32_t n)
Writes one or more blocks.
sdcflags_t sdcGetAndClearErrors (SDCDriver *sdcp)
Returns the errors mask associated to the previous operation.
bool sdcSync (SDCDriver *sdcp)
Waits for card idle condition.
bool sdcGetInfo (SDCDriver *sdcp, BlockDeviceInfo *bdip)
Returns the media info.
bool sdcErase (SDCDriver *sdcp, uint32_t startblk, uint32_t endblk)
Erases the supplied blocks.
static bool sdc_lld_prepare_read_bytes (SDCDriver *sdcp, uint8_t *buf, uint32_t bytes)
Prepares to handle read transaction.
static bool sdc_lld_prepare_read (SDCDriver *sdcp, uint32_t startblk, uint32_t n, uint32_t *resp)
Prepares card to handle read transaction.
static bool sdc_lld_prepare_write (SDCDriver *sdcp, uint32_t startblk, uint32_t n, uint32_t *resp)
Prepares card to handle write transaction.
static bool sdc_lld_wait_transaction_end (SDCDriver *sdcp, uint32_t n, uint32_t *resp)
Wait end of data transaction and performs finalizations.
static void sdc_lld_collect_errors (SDCDriver *sdcp, uint32_t sta)
Gets SDC errors.
static void sdc_lld_error_cleanup (SDCDriver *sdcp, uint32_t n, uint32_t *resp)
Performs clean transaction stopping in case of errors.
OSAL_IRQ_HANDLER (STM32_SDIO_HANDLER)
SDIO IRQ handler.
void sdc_lld_init (void)
Low level SDC driver initialization.
void sdc_lld_start (SDCDriver *sdcp)
Configures and activates the SDC peripheral.
void sdc_lld_stop (SDCDriver *sdcp)
Deactivates the SDC peripheral.
void sdc_lld_start_clk (SDCDriver *sdcp)
Starts the SDIO clock and sets it to init mode (400kHz or less).
void sdc_lld_set_data_clk (SDCDriver *sdcp, sdcbusclk_t clk)
Sets the SDIO clock to data mode (25MHz or less).
void sdc_lld_stop_clk (SDCDriver *sdcp)
Stops the SDIO clock.
void sdc_lld_set_bus_mode (SDCDriver *sdcp, sdcbusmode_t mode)
Switches the bus to 4 bits mode.
void sdc_lld_send_cmd_none (SDCDriver *sdcp, uint8_t cmd, uint32_t arg)
Sends an SDIO command with no response expected.
bool sdc_lld_send_cmd_short (SDCDriver *sdcp, uint8_t cmd, uint32_t arg, uint32_t *resp)
Sends an SDIO command with a short response expected.
bool sdc_lld_send_cmd_short_crc (SDCDriver *sdcp, uint8_t cmd, uint32_t arg, uint32_t *resp)
Sends an SDIO command with a short response expected and CRC.
bool sdc_lld_send_cmd_long_crc (SDCDriver *sdcp, uint8_t cmd, uint32_t arg, uint32_t *resp)
Sends an SDIO command with a long response expected and CRC.
bool sdc_lld_read_special (SDCDriver *sdcp, uint8_t *buf, size_t bytes, uint8_t cmd, uint32_t arg)
Reads special registers using data bus.
bool sdc_lld_read_aligned (SDCDriver *sdcp, uint32_t startblk, uint8_t *buf, uint32_t blocks)
Reads one or more blocks.
bool sdc_lld_write_aligned (SDCDriver *sdcp, uint32_t startblk, const uint8_t *buf, uint32_t blocks)
Writes one or more blocks.
bool sdc_lld_read (SDCDriver *sdcp, uint32_t startblk, uint8_t *buf, uint32_t blocks)
Reads one or more blocks.
bool sdc_lld_write (SDCDriver *sdcp, uint32_t startblk, const uint8_t *buf, uint32_t blocks)
Writes one or more blocks.
bool sdc_lld_sync (SDCDriver *sdcp)
Waits for card idle condition.
Enumerations
enum mmc_switch_t
MMC switch mode.
enum sd_switch_t
SDC switch mode.
enum sd_switch_function_t
SDC switch function.
enum sdcbusmode_t
Type of SDIO bus mode.
enum sdcbusclk_t
Max supported clock.
Variables
static const struct SDCDriverVMT sdc_vmt
Virtual methods table.
SDCDriver SDCD1
SDCD1 driver identifier.
static const SDCConfig sdc_default_cfg
SDIO default configuration.
Macro Definition Documentation
SDC_INIT_RETRY
#define SDC_INIT_RETRY 100
Number of initialization attempts before rejecting the card.
Note
Attempts are performed at 10mS intervals.
Definition at line 74 of file sdc.h.
SDC_MMC_SUPPORT
#define SDC_MMC_SUPPORT FALSE
Include support for MMC cards.
Note
MMC support is not yet implemented so this option must be kept at FALSE.
Definition at line 83 of file sdc.h.
SDC_NICE_WAITING
#define SDC_NICE_WAITING TRUE
Delays insertions.
If enabled this options inserts delays into the MMC waiting routines releasing some extra CPU time for the threads with lower priority, this may slow down the driver a bit however.
Definition at line 93 of file sdc.h.
sdcIsCardInserted
#define sdcIsCardInserted (sdcp) (sdc_lld_is_card_inserted(sdcp))
Returns the card insertion status.
Note
This macro wraps a low level function named sdc_lld_is_card_inserted(), this function must be provided by the application because it is not part of the SDC driver.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The card state.
Return values
FALSE card not inserted.
TRUE card inserted.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 146 of file sdc.h.
sdcIsWriteProtected
#define sdcIsWriteProtected (sdcp) (sdc_lld_is_write_protected(sdcp))
Returns the write protect status.
Note
This macro wraps a low level function named sdc_lld_is_write_protected(), this function must be provided by the application because it is not part of the SDC driver.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The card state.
Return values
FALSE not write protected.
TRUE write protected.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 162 of file sdc.h.
STM32_SDIO_ICR_ALL_FLAGS
#define STM32_SDIO_ICR_ALL_FLAGS
Value:
(SDIO_ICR_CCRCFAILC | SDIO_ICR_DCRCFAILC | \
                                  SDIO_ICR_CTIMEOUTC | SDIO_ICR_DTIMEOUTC | \
                                  SDIO_ICR_TXUNDERRC | SDIO_ICR_RXOVERRC |  \
                                  SDIO_ICR_CMDRENDC  | SDIO_ICR_CMDSENTC |  \
                                  SDIO_ICR_DATAENDC  | SDIO_ICR_STBITERRC | \
                                  SDIO_ICR_DBCKENDC  | SDIO_ICR_SDIOITC |   \
                                  SDIO_ICR_CEATAENDC)
Value to clear all interrupts flag at once.
Definition at line 37 of file sdc_lld.h.
Referenced by sdc_lld_error_cleanup().
STM32_SDIO_STA_ERROR_MASK
#define STM32_SDIO_STA_ERROR_MASK
Value:
(SDIO_STA_CCRCFAIL | SDIO_STA_DCRCFAIL |  \
                                   SDIO_STA_CTIMEOUT | SDIO_STA_DTIMEOUT |  \
                                   SDIO_STA_TXUNDERR | SDIO_STA_RXOVERR)
Mask of error flags in STA register.
Definition at line 48 of file sdc_lld.h.
Referenced by sdc_lld_send_cmd_long_crc().
STM32_SDC_SDIO_DMA_PRIORITY
#define STM32_SDC_SDIO_DMA_PRIORITY 3
SDIO DMA priority (0..3|lowest..highest).
Definition at line 64 of file sdc_lld.h.
STM32_SDC_SDIO_IRQ_PRIORITY
#define STM32_SDC_SDIO_IRQ_PRIORITY 9
SDIO interrupt priority level setting.
Definition at line 71 of file sdc_lld.h.
STM32_SDC_WRITE_TIMEOUT_MS
#define STM32_SDC_WRITE_TIMEOUT_MS 250
Write timeout in milliseconds.
Definition at line 78 of file sdc_lld.h.
STM32_SDC_READ_TIMEOUT_MS
#define STM32_SDC_READ_TIMEOUT_MS 25
Read timeout in milliseconds.
Definition at line 85 of file sdc_lld.h.
STM32_SDC_CLOCK_ACTIVATION_DELAY
#define STM32_SDC_CLOCK_ACTIVATION_DELAY 10
Card clock activation delay in milliseconds.
Definition at line 92 of file sdc_lld.h.
STM32_SDC_SDIO_UNALIGNED_SUPPORT
#define STM32_SDC_SDIO_UNALIGNED_SUPPORT TRUE
Support for unaligned transfers.
Note
Unaligned transfers are much slower.
Definition at line 100 of file sdc_lld.h.
STM32_SDC_WRITE_TIMEOUT
#define STM32_SDC_WRITE_TIMEOUT
Value:
(((STM32_HCLK / (STM32_SDIO_DIV_HS + 2)) / 1000) *                        \
   STM32_SDC_WRITE_TIMEOUT_MS)
SDIO data timeouts in SDIO clock cycles.
Definition at line 175 of file sdc_lld.h.
Referenced by sdc_lld_write_aligned().
_sdc_driver_methods
#define _sdc_driver_methods _mmcsd_block_device_methods
SDCDriver specific methods.
Definition at line 227 of file sdc_lld.h.
Typedef Documentation
sdcmode_t
typedef uint32_t sdcmode_t
Type of card flags.
Definition at line 191 of file sdc_lld.h.
sdcflags_t
typedef uint32_t sdcflags_t
SDC Driver condition flags type.
Definition at line 196 of file sdc_lld.h.
SDCDriver
typedef struct SDCDriver SDCDriver
Type of a structure representing an SDC driver.
Definition at line 201 of file sdc_lld.h.
Enumeration Type Documentation
mmc_switch_t
enum mmc_switch_t
MMC switch mode.
Definition at line 38 of file sdc.c.
sd_switch_t
enum sd_switch_t
SDC switch mode.
Definition at line 48 of file sdc.c.
sd_switch_function_t
enum sd_switch_function_t
SDC switch function.
Definition at line 56 of file sdc.c.
sdcbusmode_t
enum sdcbusmode_t
Type of SDIO bus mode.
Definition at line 108 of file sdc.h.
sdcbusclk_t
enum sdcbusclk_t
Max supported clock.
Definition at line 117 of file sdc.h.
Function Documentation
mode_detect()
static bool mode_detect (SDCDriver * sdcp) static
Detects card mode.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 99 of file sdc.c.
References sdc_lld_send_cmd_short_crc().
mmc_init()
static bool mmc_init (SDCDriver * sdcp) static
Init procedure for MMC.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 143 of file sdc.c.
References sdc_lld_send_cmd_short().
sdc_init()
static bool sdc_init (SDCDriver * sdcp) static
Init procedure for SDC.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 180 of file sdc.c.
References SDCDriver::cardmode.
mmc_cmd6_construct()
static uint32_t mmc_cmd6_construct (mmc_switch_t access, uint32_t idx, uint32_t value, uint32_t cmd_set) static
Constructs CMD6 argument for MMC.
Parameters
[in] access EXT_CSD access mode
[in] idx EXT_CSD byte number
[in] value value to be written in target field
[in] cmd_set switch current command set
Returns
CMD6 argument.
Function Class:
Not an API, this function is for internal use only.
Definition at line 228 of file sdc.c.
Referenced by mmc_set_bus_width().
sdc_cmd6_construct()
static uint32_t sdc_cmd6_construct (sd_switch_t mode, sd_switch_function_t function, uint32_t value) static
Constructs CMD6 argument for SDC.
Parameters
[in] mode switch/test mode
[in] function function number to be switched
[in] value value to be written in target function
Returns
CMD6 argument.
Function Class:
Not an API, this function is for internal use only.
Definition at line 248 of file sdc.c.
sdc_cmd6_extract_info()
static uint16_t sdc_cmd6_extract_info (sd_switch_function_t function, const uint8_t * buf) static
Extracts information from CMD6 answer.
Parameters
[in] function function number to be switched
[in] buf buffer with answer
Returns
extracted answer.
Function Class:
Not an API, this function is for internal use only.
Definition at line 270 of file sdc.c.
sdc_cmd6_check_status()
static bool sdc_cmd6_check_status (sd_switch_function_t function, const uint8_t * buf) static
Checks status after switching using CMD6.
Parameters
[in] function function number to be switched
[in] buf buffer with answer
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 290 of file sdc.c.
sdc_detect_bus_clk()
static bool sdc_detect_bus_clk (SDCDriver * sdcp, sdcbusclk_t * clk) static
Reads supported bus clock and switch SDC to appropriate mode.
Parameters
[in] sdcp pointer to the SDCDriver object
[out] clk pointer to clock enum
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 318 of file sdc.c.
mmc_detect_bus_clk()
static bool mmc_detect_bus_clk (SDCDriver * sdcp, sdcbusclk_t * clk) static
Reads supported bus clock and switch MMC to appropriate mode.
Parameters
[in] sdcp pointer to the SDCDriver object
[out] clk pointer to clock enum
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 372 of file sdc.c.
References SDCDriver::config, and SDCConfig::scratchpad.
detect_bus_clk()
static bool detect_bus_clk (SDCDriver * sdcp, sdcbusclk_t * clk) static
Reads supported bus clock and switch card to appropriate mode.
Parameters
[in] sdcp pointer to the SDCDriver object
[out] clk pointer to clock enum
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 406 of file sdc.c.
sdc_set_bus_width()
static bool sdc_set_bus_width (SDCDriver * sdcp) static
Sets bus width for SDC.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 425 of file sdc.c.
mmc_set_bus_width()
static bool mmc_set_bus_width (SDCDriver * sdcp) static
Sets bus width for MMC.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 463 of file sdc.c.
References mmc_cmd6_construct().
_sdc_wait_for_transfer_state()
bool _sdc_wait_for_transfer_state (SDCDriver * sdcp)
Wait for the card to complete pending operations.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 502 of file sdc.c.
References sdc_lld_send_cmd_short_crc().
Referenced by sdc_lld_write_aligned().
sdcInit()
void sdcInit (void)
SDC Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 541 of file sdc.c.
References sdc_lld_init().
sdcObjectInit()
void sdcObjectInit (SDCDriver * sdcp)
Initializes the standard part of a SDCDriver structure.
Parameters
[out] sdcp pointer to the SDCDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 553 of file sdc.c.
References BLK_STOP, SDCDriver::errors, sdc_vmt, and SDCDriver::vmt.
Referenced by sdc_lld_init().
sdcStart()
void sdcStart (SDCDriver * sdcp, const SDCConfig * config)
Configures and activates the SDC peripheral.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] config pointer to the SDCConfig object, can be NULL if the driver supports a default configuration or requires no configuration
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 572 of file sdc.c.
References BLK_ACTIVE, BLK_STOP, SDCDriver::config, and sdc_lld_start().
sdcStop()
void sdcStop (SDCDriver * sdcp)
Deactivates the SDC peripheral.
Parameters
[in] sdcp pointer to the SDCDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 592 of file sdc.c.
References BLK_ACTIVE, BLK_STOP, and sdc_lld_stop().
sdcConnect()
bool sdcConnect (SDCDriver * sdcp)
Performs the initialization procedure on the inserted card.
This function should be invoked when a card is inserted and brings the driver in the BLK_READY state where it is possible to perform read and write operations.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 618 of file sdc.c.
sdcDisconnect()
bool sdcDisconnect (SDCDriver * sdcp)
Brings the driver in a state safe for card removal.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 757 of file sdc.c.
References BLK_ACTIVE, and BLK_READY.
sdcRead()
bool sdcRead (SDCDriver * sdcp, uint32_t startblk, uint8_t * buf, uint32_t n)
Reads one or more blocks.
Precondition
The driver must be in the BLK_READY state after a successful sdcConnect() invocation.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] startblk first block to read
[out] buf pointer to the read buffer
[in] n number of blocks to read
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 800 of file sdc.c.
References BLK_READY, and SDCDriver::errors.
sdcWrite()
bool sdcWrite (SDCDriver * sdcp, uint32_t startblk, const uint8_t * buf, uint32_t n)
Writes one or more blocks.
Precondition
The driver must be in the BLK_READY state after a successful sdcConnect() invocation.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] startblk first block to write
[out] buf pointer to the write buffer
[in] n number of blocks to write
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 837 of file sdc.c.
References BLK_READY, and SDCDriver::errors.
sdcGetAndClearErrors()
sdcflags_t sdcGetAndClearErrors (SDCDriver * sdcp)
Returns the errors mask associated to the previous operation.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The errors mask.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 867 of file sdc.c.
References BLK_READY, and SDCDriver::errors.
sdcSync()
bool sdcSync (SDCDriver * sdcp)
Waits for card idle condition.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 891 of file sdc.c.
References BLK_READY.
sdcGetInfo()
bool sdcGetInfo (SDCDriver * sdcp, BlockDeviceInfo * bdip)
Returns the media info.
Parameters
[in] sdcp pointer to the SDCDriver object
[out] bdip pointer to a BlockDeviceInfo structure
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 922 of file sdc.c.
References BLK_READY.
sdcErase()
bool sdcErase (SDCDriver * sdcp, uint32_t startblk, uint32_t endblk)
Erases the supplied blocks.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] startblk starting block number
[in] endblk ending block number
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 949 of file sdc.c.
References BLK_READY, BLK_WRITING, and SDCDriver::cardmode.
sdc_lld_prepare_read_bytes()
static bool sdc_lld_prepare_read_bytes (SDCDriver * sdcp, uint8_t * buf, uint32_t bytes) static
Prepares to handle read transaction.
Designed for read special registers from card.
Parameters
[in] sdcp pointer to the SDCDriver object
[out] buf pointer to the read buffer
[in] bytes number of bytes to read
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 87 of file sdc_lld.c.
References SDCDriver::sdio.
Referenced by sdc_lld_read_special().
sdc_lld_prepare_read()
static bool sdc_lld_prepare_read (SDCDriver * sdcp, uint32_t startblk, uint32_t n, uint32_t * resp) static
Prepares card to handle read transaction.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] startblk first block to read
[in] n number of blocks to read
[in] resp pointer to the response buffer
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 135 of file sdc_lld.c.
References SDCDriver::cardmode.
sdc_lld_prepare_write()
static bool sdc_lld_prepare_write (SDCDriver * sdcp, uint32_t startblk, uint32_t n, uint32_t * resp) static
Prepares card to handle write transaction.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] startblk first block to read
[in] n number of blocks to write
[in] resp pointer to the response buffer
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 173 of file sdc_lld.c.
References SDCDriver::cardmode.
sdc_lld_wait_transaction_end()
static bool sdc_lld_wait_transaction_end (SDCDriver * sdcp, uint32_t n, uint32_t * resp) static
Wait end of data transaction and performs finalizations.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] n number of blocks in transaction
[in] resp pointer to the response buffer
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Definition at line 208 of file sdc_lld.c.
References SDCDriver::sdio, and SDCDriver::thread.
Referenced by sdc_lld_read_special().
sdc_lld_collect_errors()
static void sdc_lld_collect_errors (SDCDriver * sdcp, uint32_t sta) static
Gets SDC errors.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] sta value of the STA register
Function Class:
Not an API, this function is for internal use only.
Definition at line 261 of file sdc_lld.c.
Referenced by sdc_lld_error_cleanup(), sdc_lld_send_cmd_long_crc(), sdc_lld_send_cmd_short(), and sdc_lld_send_cmd_short_crc().
sdc_lld_error_cleanup()
static void sdc_lld_error_cleanup (SDCDriver * sdcp, uint32_t n, uint32_t * resp) static
Performs clean transaction stopping in case of errors.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] n number of blocks in transaction
[in] resp pointer to the response buffer
Function Class:
Not an API, this function is for internal use only.
Definition at line 291 of file sdc_lld.c.
References SDCDriver::dma, dmaStreamClearInterrupt, dmaStreamDisable, sdc_lld_collect_errors(), sdc_lld_send_cmd_short_crc(), SDCDriver::sdio, and STM32_SDIO_ICR_ALL_FLAGS.
OSAL_IRQ_HANDLER()
OSAL_IRQ_HANDLER (STM32_SDIO_HANDLER)
SDIO IRQ handler.
It just wakes transaction thread. All error handling performs in that thread.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 320 of file sdc_lld.c.
sdc_lld_init()
void sdc_lld_init (void)
Low level SDC driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 346 of file sdc_lld.c.
References SDCDriver::dma, sdcObjectInit(), SDCDriver::sdio, STM32_DMA_STREAM, and SDCDriver::thread.
Referenced by sdcInit().
sdc_lld_start()
void sdc_lld_start (SDCDriver * sdcp)
Configures and activates the SDC peripheral.
Parameters
[in] sdcp pointer to the SDCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 361 of file sdc_lld.c.
References SDCDriver::config, SDCDriver::dmamode, and sdc_default_cfg.
Referenced by sdcStart().
sdc_lld_stop()
void sdc_lld_stop (SDCDriver * sdcp)
Deactivates the SDC peripheral.
Parameters
[in] sdcp pointer to the SDCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 407 of file sdc_lld.c.
References BLK_STOP, nvicDisableVector(), and SDCDriver::sdio.
Referenced by sdcStop().
sdc_lld_start_clk()
void sdc_lld_start_clk (SDCDriver * sdcp)
Starts the SDIO clock and sets it to init mode (400kHz or less).
Parameters
[in] sdcp pointer to the SDCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 431 of file sdc_lld.c.
References SDCDriver::sdio.
sdc_lld_set_data_clk()
void sdc_lld_set_data_clk (SDCDriver * sdcp, sdcbusclk_t clk)
Sets the SDIO clock to data mode (25MHz or less).
Parameters
[in] sdcp pointer to the SDCDriver object
[in] clk the clock mode
Function Class:
Not an API, this function is for internal use only.
Definition at line 450 of file sdc_lld.c.
sdc_lld_stop_clk()
void sdc_lld_stop_clk (SDCDriver * sdcp)
Stops the SDIO clock.
Parameters
[in] sdcp pointer to the SDCDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 472 of file sdc_lld.c.
References SDCDriver::sdio.
sdc_lld_set_bus_mode()
void sdc_lld_set_bus_mode (SDCDriver * sdcp, sdcbusmode_t mode)
Switches the bus to 4 bits mode.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] mode bus mode
Function Class:
Not an API, this function is for internal use only.
Definition at line 486 of file sdc_lld.c.
References SDCDriver::sdio.
sdc_lld_send_cmd_none()
void sdc_lld_send_cmd_none (SDCDriver * sdcp, uint8_t cmd, uint32_t arg)
Sends an SDIO command with no response expected.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] cmd card command
[in] arg command argument
Function Class:
Not an API, this function is for internal use only.
Definition at line 511 of file sdc_lld.c.
References SDCDriver::sdio.
sdc_lld_send_cmd_short()
bool sdc_lld_send_cmd_short (SDCDriver * sdcp, uint8_t cmd, uint32_t arg, uint32_t * resp)
Sends an SDIO command with a short response expected.
Note
The CRC is not verified.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] cmd card command
[in] arg command argument
[out] resp pointer to the response buffer (one word)
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 535 of file sdc_lld.c.
References sdc_lld_collect_errors(), and SDCDriver::sdio.
Referenced by mmc_init().
sdc_lld_send_cmd_short_crc()
bool sdc_lld_send_cmd_short_crc (SDCDriver * sdcp, uint8_t cmd, uint32_t arg, uint32_t * resp)
Sends an SDIO command with a short response expected and CRC.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] cmd card command
[in] arg command argument
[out] resp pointer to the response buffer (one word)
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 568 of file sdc_lld.c.
References sdc_lld_collect_errors(), and SDCDriver::sdio.
Referenced by _sdc_wait_for_transfer_state(), mode_detect(), sdc_lld_error_cleanup(), and sdc_lld_read_special().
sdc_lld_send_cmd_long_crc()
bool sdc_lld_send_cmd_long_crc (SDCDriver * sdcp, uint8_t cmd, uint32_t arg, uint32_t * resp)
Sends an SDIO command with a long response expected and CRC.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] cmd card command
[in] arg command argument
[out] resp pointer to the response buffer (four words)
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 600 of file sdc_lld.c.
References sdc_lld_collect_errors(), SDCDriver::sdio, and STM32_SDIO_STA_ERROR_MASK.
sdc_lld_read_special()
bool sdc_lld_read_special (SDCDriver * sdcp, uint8_t * buf, size_t bytes, uint8_t cmd, uint32_t arg)
Reads special registers using data bus.
Needs only during card detection procedure.
Parameters
[in] sdcp pointer to the SDCDriver object
[out] buf pointer to the read buffer
[in] bytes number of bytes to read
[in] cmd card command
[in] arg argument for command
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 642 of file sdc_lld.c.
References MMCSD_R1_ERROR, sdc_lld_prepare_read_bytes(), sdc_lld_send_cmd_short_crc(), and sdc_lld_wait_transaction_end().
sdc_lld_read_aligned()
bool sdc_lld_read_aligned (SDCDriver * sdcp, uint32_t startblk, uint8_t * buf, uint32_t blocks)
Reads one or more blocks.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] startblk first block to read
[out] buf pointer to the read buffer
[in] blocks number of blocks to read
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 677 of file sdc_lld.c.
References MMCSD_BLOCK_SIZE, and SDCDriver::sdio.
Referenced by sdc_lld_read().
sdc_lld_write_aligned()
bool sdc_lld_write_aligned (SDCDriver * sdcp, uint32_t startblk, const uint8_t * buf, uint32_t blocks)
Writes one or more blocks.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] startblk first block to write
[out] buf pointer to the write buffer
[in] n number of blocks to write
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 739 of file sdc_lld.c.
References _sdc_wait_for_transfer_state(), MMCSD_BLOCK_SIZE, SDCDriver::sdio, and STM32_SDC_WRITE_TIMEOUT.
Referenced by sdc_lld_write().
sdc_lld_read()
bool sdc_lld_read (SDCDriver * sdcp, uint32_t startblk, uint8_t * buf, uint32_t blocks)
Reads one or more blocks.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] startblk first block to read
[out] buf pointer to the read buffer
[in] blocks number of blocks to read
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 801 of file sdc_lld.c.
References sdc_lld_read_aligned().
sdc_lld_write()
bool sdc_lld_write (SDCDriver * sdcp, uint32_t startblk, const uint8_t * buf, uint32_t blocks)
Writes one or more blocks.
Parameters
[in] sdcp pointer to the SDCDriver object
[in] startblk first block to write
[out] buf pointer to the write buffer
[in] blocks number of blocks to write
Returns
The operation status.
Return values
HAL_SUCCESS operation succeeded.
HAL_FAILED operation failed.
Function Class:
Not an API, this function is for internal use only.
Definition at line 834 of file sdc_lld.c.
References MMCSD_BLOCK_SIZE, and sdc_lld_write_aligned().
sdc_lld_sync()
bool sdc_lld_sync (SDCDriver * sdcp)
Waits for card idle condition.
Parameters
[in] sdcp pointer to the SDCDriver object
Returns
The operation status.
Return values
HAL_SUCCESS the operation succeeded.
HAL_FAILED the operation failed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 864 of file sdc_lld.c.
Variable Documentation
sdc_vmt
const struct SDCDriverVMT sdc_vmt static
Initial value:
= {
  (bool (*)(void *))sdc_lld_is_card_inserted,
  (bool (*)(void *))sdc_lld_is_write_protected,
  (bool (*)(void *))sdcConnect,
  (bool (*)(void *))sdcDisconnect,
  (bool (*)(void *, uint32_t, uint8_t *, uint32_t))sdcRead,
  (bool (*)(void *, uint32_t, const uint8_t *, uint32_t))sdcWrite,
  (bool (*)(void *))sdcSync,
  (bool (*)(void *, BlockDeviceInfo *))sdcGetInfo
}
Virtual methods table.
Definition at line 74 of file sdc.c.
Referenced by sdcObjectInit().
SDCD1
SDCDriver SDCD1
SDCD1 driver identifier.
Definition at line 44 of file sdc_lld.c.
sdc_default_cfg
const SDCConfig sdc_default_cfg static
Initial value:
= {
  NULL,
  SDC_MODE_4BIT
}
SDIO default configuration.
Definition at line 64 of file sdc_lld.c.
Referenced by sdc_lld_start().