ChibiOS/HAL: MAC Driver
MAC Driver
HAL » Normal Drivers
Generic MAC Driver.
Detailed Description
Generic MAC Driver.
This module implements a generic MAC (Media Access Control) driver for Ethernet controllers.
Precondition
In order to use the MAC driver the HAL_USE_MAC option must be enabled in halconf.h.
Macros
#define MAC_SUPPORTS_ZERO_COPY TRUE
This implementation supports the zero-copy mode API.
MAC configuration options
#define MAC_USE_ZERO_COPY FALSE
Enables an event sources for incoming packets.
#define MAC_USE_EVENTS TRUE
Enables an event sources for incoming packets.
Macro Functions
#define macGetReceiveEventSource(macp) (&(macp)->rdevent)
Returns the received frames event source.
#define macWriteTransmitDescriptor(tdp, buf, size) mac_lld_write_transmit_descriptor(tdp, buf, size)
Writes to a transmit descriptor's stream.
#define macReadReceiveDescriptor(rdp, buf, size) mac_lld_read_receive_descriptor(rdp, buf, size)
Reads from a receive descriptor's stream.
#define macGetNextTransmitBuffer(tdp, size, sizep) mac_lld_get_next_transmit_buffer(tdp, size, sizep)
Returns a pointer to the next transmit buffer in the descriptor chain.
#define macGetNextReceiveBuffer(rdp, sizep) mac_lld_get_next_receive_buffer(rdp, sizep)
Returns a pointer to the next receive buffer in the descriptor chain.
RDES0 constants
#define STM32_RDES0_OWN 0x80000000
#define STM32_RDES0_AFM 0x40000000
#define STM32_RDES0_FL_MASK 0x3FFF0000
#define STM32_RDES0_ES 0x00008000
#define STM32_RDES0_DESERR 0x00004000
#define STM32_RDES0_SAF 0x00002000
#define STM32_RDES0_LE 0x00001000
#define STM32_RDES0_OE 0x00000800
#define STM32_RDES0_VLAN 0x00000400
#define STM32_RDES0_FS 0x00000200
#define STM32_RDES0_LS 0x00000100
#define STM32_RDES0_IPHCE 0x00000080
#define STM32_RDES0_LCO 0x00000040
#define STM32_RDES0_FT 0x00000020
#define STM32_RDES0_RWT 0x00000010
#define STM32_RDES0_RE 0x00000008
#define STM32_RDES0_DE 0x00000004
#define STM32_RDES0_CE 0x00000002
#define STM32_RDES0_PCE 0x00000001
RDES1 constants
#define STM32_RDES1_DIC 0x80000000
#define STM32_RDES1_RBS2_MASK 0x1FFF0000
#define STM32_RDES1_RER 0x00008000
#define STM32_RDES1_RCH 0x00004000
#define STM32_RDES1_RBS1_MASK 0x00001FFF
TDES0 constants
#define STM32_TDES0_OWN 0x80000000
#define STM32_TDES0_IC 0x40000000
#define STM32_TDES0_LS 0x20000000
#define STM32_TDES0_FS 0x10000000
#define STM32_TDES0_DC 0x08000000
#define STM32_TDES0_DP 0x04000000
#define STM32_TDES0_TTSE 0x02000000
#define STM32_TDES0_LOCKED 0x01000000 /* NOTE: Pseudo flag. */
#define STM32_TDES0_CIC_MASK 0x00C00000
#define STM32_TDES0_CIC(n) ((n) << 22)
#define STM32_TDES0_TER 0x00200000
#define STM32_TDES0_TCH 0x00100000
#define STM32_TDES0_TTSS 0x00020000
#define STM32_TDES0_IHE 0x00010000
#define STM32_TDES0_ES 0x00008000
#define STM32_TDES0_JT 0x00004000
#define STM32_TDES0_FF 0x00002000
#define STM32_TDES0_IPE 0x00001000
#define STM32_TDES0_LCA 0x00000800
#define STM32_TDES0_NC 0x00000400
#define STM32_TDES0_LCO 0x00000200
#define STM32_TDES0_EC 0x00000100
#define STM32_TDES0_VF 0x00000080
#define STM32_TDES0_CC_MASK 0x00000078
#define STM32_TDES0_ED 0x00000004
#define STM32_TDES0_UF 0x00000002
#define STM32_TDES0_DB 0x00000001
TDES1 constants
#define STM32_TDES1_TBS2_MASK 0x1FFF0000
#define STM32_TDES1_TBS1_MASK 0x00001FFF
Configuration options
#define STM32_MAC_TRANSMIT_BUFFERS 2
Number of available transmit buffers.
#define STM32_MAC_RECEIVE_BUFFERS 4
Number of available receive buffers.
#define STM32_MAC_BUFFERS_SIZE 1522
Maximum supported frame size.
#define STM32_MAC_PHY_TIMEOUT 100
PHY detection timeout.
#define STM32_MAC_ETH1_CHANGE_PHY_STATE TRUE
Change the PHY power state inside the driver.
#define STM32_MAC_ETH1_IRQ_PRIORITY 13
ETHD1 interrupt priority level setting.
#define STM32_MAC_IP_CHECKSUM_OFFLOAD 0
IP checksum offload.
Typedefs
typedef struct MACDriver MACDriver
Type of a structure representing a MAC driver.
Data Structures
struct stm32_eth_rx_descriptor_t
Type of an STM32 Ethernet receive descriptor.
struct stm32_eth_tx_descriptor_t
Type of an STM32 Ethernet transmit descriptor.
struct MACConfig
Driver configuration structure.
struct MACDriver
Structure representing a MAC driver.
struct MACTransmitDescriptor
Structure representing a transmit descriptor.
struct MACReceiveDescriptor
Structure representing a receive descriptor.
Functions
void macInit (void)
MAC Driver initialization.
void macObjectInit (MACDriver *macp)
Initialize the standard part of a MACDriver structure.
void macStart (MACDriver *macp, const MACConfig *config)
Configures and activates the MAC peripheral.
void macStop (MACDriver *macp)
Deactivates the MAC peripheral.
msg_t macWaitTransmitDescriptor (MACDriver *macp, MACTransmitDescriptor *tdp, systime_t timeout)
Allocates a transmission descriptor.
void macReleaseTransmitDescriptor (MACTransmitDescriptor *tdp)
Releases a transmit descriptor and starts the transmission of the enqueued data as a single frame.
msg_t macWaitReceiveDescriptor (MACDriver *macp, MACReceiveDescriptor *rdp, systime_t timeout)
Waits for a received frame.
void macReleaseReceiveDescriptor (MACReceiveDescriptor *rdp)
Releases a receive descriptor.
bool macPollLinkStatus (MACDriver *macp)
Updates and returns the link status.
void mii_write (MACDriver *macp, uint32_t reg, uint32_t value)
Writes a PHY register.
uint32_t mii_read (MACDriver *macp, uint32_t reg)
Reads a PHY register.
static void mii_find_phy (MACDriver *macp)
PHY address detection.
static void mac_lld_set_address (const uint8_t *p)
MAC address setup.
void mac_lld_init (void)
Low level MAC initialization.
void mac_lld_start (MACDriver *macp)
Configures and activates the MAC peripheral.
void mac_lld_stop (MACDriver *macp)
Deactivates the MAC peripheral.
msg_t mac_lld_get_transmit_descriptor (MACDriver *macp, MACTransmitDescriptor *tdp)
Returns a transmission descriptor.
void mac_lld_release_transmit_descriptor (MACTransmitDescriptor *tdp)
Releases a transmit descriptor and starts the transmission of the enqueued data as a single frame.
msg_t mac_lld_get_receive_descriptor (MACDriver *macp, MACReceiveDescriptor *rdp)
Returns a receive descriptor.
void mac_lld_release_receive_descriptor (MACReceiveDescriptor *rdp)
Releases a receive descriptor.
bool mac_lld_poll_link_status (MACDriver *macp)
Updates and returns the link status.
size_t mac_lld_write_transmit_descriptor (MACTransmitDescriptor *tdp, uint8_t *buf, size_t size)
Writes to a transmit descriptor's stream.
size_t mac_lld_read_receive_descriptor (MACReceiveDescriptor *rdp, uint8_t *buf, size_t size)
Reads from a receive descriptor's stream.
uint8_t * mac_lld_get_next_transmit_buffer (MACTransmitDescriptor *tdp, size_t size, size_t *sizep)
Returns a pointer to the next transmit buffer in the descriptor chain.
const uint8_t * mac_lld_get_next_receive_buffer (MACReceiveDescriptor *rdp, size_t *sizep)
Returns a pointer to the next receive buffer in the descriptor chain.
Enumerations
enum macstate_t { MAC_UNINIT = 0, MAC_STOP = 1, MAC_ACTIVE = 2 }
Driver state machine possible states.
Variables
MACDriver ETHD1
Ethernet driver 1.
Macro Definition Documentation
MAC_USE_ZERO_COPY
#define MAC_USE_ZERO_COPY FALSE
Enables an event sources for incoming packets.
Definition at line 45 of file mac.h.
MAC_USE_EVENTS
#define MAC_USE_EVENTS TRUE
Enables an event sources for incoming packets.
Definition at line 52 of file mac.h.
macGetReceiveEventSource
#define macGetReceiveEventSource (macp) (&(macp)->rdevent)
Returns the received frames event source.
Parameters
[in] macp pointer to the MACDriver object
Returns
The pointer to the EventSource structure.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 97 of file mac.h.
macWriteTransmitDescriptor
#define macWriteTransmitDescriptor (tdp, buf, size) mac_lld_write_transmit_descriptor(tdp, buf, size)
Writes to a transmit descriptor's stream.
Parameters
[in] tdp pointer to a MACTransmitDescriptor structure
[in] buf pointer to the buffer containing the data to be written
[in] size number of bytes to be written
Returns
The number of bytes written into the descriptor's stream, this value can be less than the amount specified in the parameter size if the maximum frame size is reached.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 113 of file mac.h.
macReadReceiveDescriptor
#define macReadReceiveDescriptor (rdp, buf, size) mac_lld_read_receive_descriptor(rdp, buf, size)
Reads from a receive descriptor's stream.
Parameters
[in] rdp pointer to a MACReceiveDescriptor structure
[in] buf pointer to the buffer that will receive the read data
[in] size number of bytes to be read
Returns
The number of bytes read from the descriptor's stream, this value can be less than the amount specified in the parameter size if there are no more bytes to read.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 128 of file mac.h.
macGetNextTransmitBuffer
#define macGetNextTransmitBuffer (tdp, size, sizep) mac_lld_get_next_transmit_buffer(tdp, size, sizep)
Returns a pointer to the next transmit buffer in the descriptor chain.
Note
The API guarantees that enough buffers can be requested to fill a whole frame.
Parameters
[in] tdp pointer to a MACTransmitDescriptor structure
[in] size size of the requested buffer. Specify the frame size on the first call then scale the value down subtracting the amount of data already copied into the previous buffers.
[out] sizep pointer to variable receiving the real buffer size. The returned value can be less than the amount requested, this means that more buffers must be requested in order to fill the frame data entirely.
Returns
Pointer to the returned buffer.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 151 of file mac.h.
macGetNextReceiveBuffer
#define macGetNextReceiveBuffer (rdp, sizep) mac_lld_get_next_receive_buffer(rdp, sizep)
Returns a pointer to the next receive buffer in the descriptor chain.
Note
The API guarantees that the descriptor chain contains a whole frame.
Parameters
[in] rdp pointer to a MACReceiveDescriptor structure
[out] sizep pointer to variable receiving the buffer size, it is zero when the last buffer has already been returned.
Returns
Pointer to the returned buffer.
Return values
NULL if the buffer chain has been entirely scanned.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 168 of file mac.h.
MAC_SUPPORTS_ZERO_COPY
#define MAC_SUPPORTS_ZERO_COPY TRUE
This implementation supports the zero-copy mode API.
Definition at line 37 of file mac_lld.h.
STM32_MAC_TRANSMIT_BUFFERS
#define STM32_MAC_TRANSMIT_BUFFERS 2
Number of available transmit buffers.
Definition at line 128 of file mac_lld.h.
STM32_MAC_RECEIVE_BUFFERS
#define STM32_MAC_RECEIVE_BUFFERS 4
Number of available receive buffers.
Definition at line 135 of file mac_lld.h.
Referenced by mac_lld_init(), and mac_lld_start().
STM32_MAC_BUFFERS_SIZE
#define STM32_MAC_BUFFERS_SIZE 1522
Maximum supported frame size.
Definition at line 142 of file mac_lld.h.
STM32_MAC_PHY_TIMEOUT
#define STM32_MAC_PHY_TIMEOUT 100
PHY detection timeout.
Timeout for PHY address detection, the scan for a PHY is performed the specified number of times before invoking the failure handler. This setting applies only if the PHY address is not explicitly set in the board header file using BOARD_PHY_ADDRESS. A zero value disables the timeout and a single search is performed.
Definition at line 154 of file mac_lld.h.
Referenced by mii_find_phy().
STM32_MAC_ETH1_CHANGE_PHY_STATE
#define STM32_MAC_ETH1_CHANGE_PHY_STATE TRUE
Change the PHY power state inside the driver.
Definition at line 161 of file mac_lld.h.
STM32_MAC_ETH1_IRQ_PRIORITY
#define STM32_MAC_ETH1_IRQ_PRIORITY 13
ETHD1 interrupt priority level setting.
Definition at line 168 of file mac_lld.h.
STM32_MAC_IP_CHECKSUM_OFFLOAD
#define STM32_MAC_IP_CHECKSUM_OFFLOAD 0
IP checksum offload.
The following modes are available:
0 Function disabled.
1 Only IP header checksum calculation and insertion are enabled.
2 IP header checksum and payload checksum calculation and insertion are enabled, but pseudo-header checksum is not calculated in hardware.
3 IP Header checksum and payload checksum calculation and insertion are enabled, and pseudo-header checksum is calculated in hardware.
Definition at line 185 of file mac_lld.h.
Typedef Documentation
MACDriver
typedef struct MACDriver MACDriver
Type of a structure representing a MAC driver.
Definition at line 76 of file mac.h.
Enumeration Type Documentation
macstate_t
enum macstate_t
Driver state machine possible states.
Enumerator
MAC_UNINIT
Not initialized.
MAC_STOP
Stopped.
MAC_ACTIVE
Active.
Definition at line 67 of file mac.h.
Function Documentation
macInit()
void macInit (void)
MAC Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 64 of file mac.c.
References mac_lld_init().
macObjectInit()
void macObjectInit (MACDriver * macp)
Initialize the standard part of a MACDriver structure.
Parameters
[out] macp pointer to the MACDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 76 of file mac.c.
References MACDriver::config, MAC_STOP, MACDriver::rdevent, MACDriver::rdqueue, MACDriver::state, and MACDriver::tdqueue.
Referenced by mac_lld_init().
macStart()
void macStart (MACDriver * macp, const MACConfig * config)
Configures and activates the MAC peripheral.
Parameters
[in] macp pointer to the MACDriver object
[in] config pointer to the MACConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 95 of file mac.c.
References MACDriver::config, MAC_ACTIVE, mac_lld_start(), MAC_STOP, and MACDriver::state.
macStop()
void macStop (MACDriver * macp)
Deactivates the MAC peripheral.
Parameters
[in] macp pointer to the MACDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 115 of file mac.c.
References MAC_ACTIVE, mac_lld_stop(), MAC_STOP, and MACDriver::state.
macWaitTransmitDescriptor()
msg_t macWaitTransmitDescriptor (MACDriver * macp, MACTransmitDescriptor * tdp, systime_t timeout)
Allocates a transmission descriptor.
One of the available transmission descriptors is locked and returned. If a descriptor is not currently available then the invoking thread is queued until one is freed.
Parameters
[in] macp pointer to the MACDriver object
[out] tdp pointer to a MACTransmitDescriptor structure
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK the descriptor was obtained.
MSG_TIMEOUT the operation timed out, descriptor not initialized.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 146 of file mac.c.
References MAC_ACTIVE, mac_lld_get_transmit_descriptor(), MACDriver::state, and MACDriver::tdqueue.
macReleaseTransmitDescriptor()
void macReleaseTransmitDescriptor (MACTransmitDescriptor * tdp)
Releases a transmit descriptor and starts the transmission of the enqueued data as a single frame.
Parameters
[in] tdp the pointer to the MACTransmitDescriptor structure
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 180 of file mac.c.
References mac_lld_release_transmit_descriptor().
macWaitReceiveDescriptor()
msg_t macWaitReceiveDescriptor (MACDriver * macp, MACReceiveDescriptor * rdp, systime_t timeout)
Waits for a received frame.
Stops until a frame is received and buffered. If a frame is not immediately available then the invoking thread is queued until one is received.
Parameters
[in] macp pointer to the MACDriver object
[out] rdp pointer to a MACReceiveDescriptor structure
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK the descriptor was obtained.
MSG_TIMEOUT the operation timed out, descriptor not initialized.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 206 of file mac.c.
References MAC_ACTIVE, mac_lld_get_receive_descriptor(), MACDriver::rdqueue, and MACDriver::state.
macReleaseReceiveDescriptor()
void macReleaseReceiveDescriptor (MACReceiveDescriptor * rdp)
Releases a receive descriptor.
The descriptor and its buffer are made available for more incoming frames.
Parameters
[in] rdp the pointer to the MACReceiveDescriptor structure
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 241 of file mac.c.
References mac_lld_release_receive_descriptor().
macPollLinkStatus()
bool macPollLinkStatus (MACDriver * macp)
Updates and returns the link status.
Parameters
[in] macp pointer to the MACDriver object
Returns
The link status.
Return values
true if the link is active.
false if the link is down.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 258 of file mac.c.
References MAC_ACTIVE, mac_lld_poll_link_status(), and MACDriver::state.
mii_write()
void mii_write (MACDriver * macp, uint32_t reg, uint32_t value)
Writes a PHY register.
Parameters
[in] macp pointer to the MACDriver object
[in] reg register number
[in] value new register value
Function Class:
Not an API, this function is for internal use only.
Definition at line 89 of file mac_lld.c.
References MACDriver::phyaddr.
Referenced by mac_lld_stop().
mii_read()
uint32_t mii_read (MACDriver * macp, uint32_t reg)
Reads a PHY register.
Parameters
[in] macp pointer to the MACDriver object
[in] reg register number
Returns
The PHY register content.
Function Class:
Not an API, this function is for internal use only.
Definition at line 108 of file mac_lld.c.
References MACDriver::phyaddr.
Referenced by mac_lld_poll_link_status(), mac_lld_stop(), and mii_find_phy().
mii_find_phy()
static void mii_find_phy (MACDriver * macp) static
PHY address detection.
Parameters
[in] macp pointer to the MACDriver object
Definition at line 122 of file mac_lld.c.
References MII_PHYSID1, MII_PHYSID2, mii_read(), MACDriver::phyaddr, and STM32_MAC_PHY_TIMEOUT.
mac_lld_set_address()
static void mac_lld_set_address (const uint8_t * p) static
MAC address setup.
Parameters
[in] p pointer to a six bytes buffer containing the MAC address
Definition at line 152 of file mac_lld.c.
mac_lld_init()
void mac_lld_init (void)
Low level MAC initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 213 of file mac_lld.c.
References MACDriver::link_up, macObjectInit(), and STM32_MAC_RECEIVE_BUFFERS.
Referenced by macInit().
mac_lld_start()
void mac_lld_start (MACDriver * macp)
Configures and activates the MAC peripheral.
Parameters
[in] macp pointer to the MACDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 291 of file mac_lld.c.
References STM32_MAC_RECEIVE_BUFFERS.
Referenced by macStart().
mac_lld_stop()
void mac_lld_stop (MACDriver * macp)
Deactivates the MAC peripheral.
Parameters
[in] macp pointer to the MACDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 367 of file mac_lld.c.
References BMCR_PDOWN, MAC_STOP, MII_BMCR, mii_read(), mii_write(), nvicDisableVector(), rccDisableETH, and MACDriver::state.
Referenced by macStop().
mac_lld_get_transmit_descriptor()
msg_t mac_lld_get_transmit_descriptor (MACDriver * macp, MACTransmitDescriptor * tdp)
Returns a transmission descriptor.
One of the available transmission descriptors is locked and returned.
Parameters
[in] macp pointer to the MACDriver object
[out] tdp pointer to a MACTransmitDescriptor structure
Returns
The operation status.
Return values
MSG_OK the descriptor has been obtained.
MSG_TIMEOUT descriptor not available.
Function Class:
Not an API, this function is for internal use only.
Definition at line 402 of file mac_lld.c.
References MACDriver::link_up, and MACDriver::txptr.
Referenced by macWaitTransmitDescriptor().
mac_lld_release_transmit_descriptor()
void mac_lld_release_transmit_descriptor (MACTransmitDescriptor * tdp)
Releases a transmit descriptor and starts the transmission of the enqueued data as a single frame.
Parameters
[in] tdp the pointer to the MACTransmitDescriptor structure
Function Class:
Not an API, this function is for internal use only.
Definition at line 445 of file mac_lld.c.
References MACTransmitDescriptor::physdesc.
Referenced by macReleaseTransmitDescriptor().
mac_lld_get_receive_descriptor()
msg_t mac_lld_get_receive_descriptor (MACDriver * macp, MACReceiveDescriptor * rdp)
Returns a receive descriptor.
Parameters
[in] macp pointer to the MACDriver object
[out] rdp pointer to a MACReceiveDescriptor structure
Returns
The operation status.
Return values
MSG_OK the descriptor has been obtained.
MSG_TIMEOUT descriptor not available.
Function Class:
Not an API, this function is for internal use only.
Definition at line 478 of file mac_lld.c.
References MACDriver::rxptr.
Referenced by macWaitReceiveDescriptor().
mac_lld_release_receive_descriptor()
void mac_lld_release_receive_descriptor (MACReceiveDescriptor * rdp)
Releases a receive descriptor.
The descriptor and its buffer are made available for more incoming frames.
Parameters
[in] rdp the pointer to the MACReceiveDescriptor structure
Function Class:
Not an API, this function is for internal use only.
Definition at line 526 of file mac_lld.c.
References MACReceiveDescriptor::physdesc.
Referenced by macReleaseReceiveDescriptor().
mac_lld_poll_link_status()
bool mac_lld_poll_link_status (MACDriver * macp)
Updates and returns the link status.
Parameters
[in] macp pointer to the MACDriver object
Returns
The link status.
Return values
true if the link is active.
false if the link is down.
Function Class:
Not an API, this function is for internal use only.
Definition at line 555 of file mac_lld.c.
References BMCR_ANENABLE, BMCR_FULLDPLX, BMCR_SPEED100, BMSR_ANEGCOMPLETE, BMSR_LSTATUS, BMSR_RFAULT, MACDriver::link_up, LPA_100BASE4, LPA_100FULL, LPA_100HALF, LPA_10FULL, MII_BMCR, MII_BMSR, MII_LPA, and mii_read().
Referenced by macPollLinkStatus().
mac_lld_write_transmit_descriptor()
size_t mac_lld_write_transmit_descriptor (MACTransmitDescriptor * tdp, uint8_t * buf, size_t size)
Writes to a transmit descriptor's stream.
Parameters
[in] tdp pointer to a MACTransmitDescriptor structure
[in] buf pointer to the buffer containing the data to be written
[in] size number of bytes to be written
Returns
The number of bytes written into the descriptor's stream, this value can be less than the amount specified in the parameter size if the maximum frame size is reached.
Function Class:
Not an API, this function is for internal use only.
Definition at line 628 of file mac_lld.c.
References MACTransmitDescriptor::physdesc.
mac_lld_read_receive_descriptor()
size_t mac_lld_read_receive_descriptor (MACReceiveDescriptor * rdp, uint8_t * buf, size_t size)
Reads from a receive descriptor's stream.
Parameters
[in] rdp pointer to a MACReceiveDescriptor structure
[in] buf pointer to the buffer that will receive the read data
[in] size number of bytes to be read
Returns
The number of bytes read from the descriptor's stream, this value can be less than the amount specified in the parameter size if there are no more bytes to read.
Function Class:
Not an API, this function is for internal use only.
Definition at line 658 of file mac_lld.c.
References MACReceiveDescriptor::physdesc.
mac_lld_get_next_transmit_buffer()
uint8_t* mac_lld_get_next_transmit_buffer (MACTransmitDescriptor * tdp, size_t size, size_t * sizep)
Returns a pointer to the next transmit buffer in the descriptor chain.
Note
The API guarantees that enough buffers can be requested to fill a whole frame.
Parameters
[in] tdp pointer to a MACTransmitDescriptor structure
[in] size size of the requested buffer. Specify the frame size on the first call then scale the value down subtracting the amount of data already copied into the previous buffers.
[out] sizep pointer to variable receiving the buffer size, it is zero when the last buffer has already been returned. Note that a returned size lower than the amount requested means that more buffers must be requested in order to fill the frame data entirely.
Returns
Pointer to the returned buffer.
Return values
NULL if the buffer chain has been entirely scanned.
Function Class:
Not an API, this function is for internal use only.
Definition at line 697 of file mac_lld.c.
References MACTransmitDescriptor::offset, MACTransmitDescriptor::physdesc, and MACTransmitDescriptor::size.
mac_lld_get_next_receive_buffer()
const uint8_t* mac_lld_get_next_receive_buffer (MACReceiveDescriptor * rdp, size_t * sizep)
Returns a pointer to the next receive buffer in the descriptor chain.
Note
The API guarantees that the descriptor chain contains a whole frame.
Parameters
[in] rdp pointer to a MACReceiveDescriptor structure
[out] sizep pointer to variable receiving the buffer size, it is zero when the last buffer has already been returned.
Returns
Pointer to the returned buffer.
Return values
NULL if the buffer chain has been entirely scanned.
Function Class:
Not an API, this function is for internal use only.
Definition at line 724 of file mac_lld.c.
References MACReceiveDescriptor::offset, MACReceiveDescriptor::physdesc, and MACReceiveDescriptor::size.
Variable Documentation
ETHD1
MACDriver ETHD1
Ethernet driver 1.
Definition at line 61 of file mac_lld.c.