ChibiOS/HAL: HAL Driver
HAL Driver
HAL » Normal Drivers
Hardware Abstraction Layer.
Detailed Description
Hardware Abstraction Layer.
The HAL (Hardware Abstraction Layer) driver performs the system initialization and includes the platform support code shared by the other drivers. This driver does contain any API function except for a general initialization function halInit() that must be invoked before any HAL service can be used, usually the HAL initialization should be performed immediately before the kernel initialization.
Some HAL driver implementations also offer a custom early clock setup function that can be invoked before the C runtime initialization in order to accelerate the startup time.
Macros
#define _CHIBIOS_HAL_
ChibiOS/HAL identification macro.
#define CH_HAL_STABLE 1
Stable release flag.
#define HAL_IMPLEMENTS_COUNTERS TRUE
Defines the support for realtime counters in the HAL.
#define STM32_0WS_THRESHOLD 30000000
Maximum frequency thresholds and wait states for flash access.
#define STM32_PLLM (STM32_PLLM_VALUE << 0)
STM32_PLLM field.
#define STM32_PLLCLKIN (STM32_HSECLK / STM32_PLLM_VALUE)
PLLs input clock frequency.
#define STM32_ACTIVATE_PLL TRUE
PLL activation flag.
#define STM32_PLLN (STM32_PLLN_VALUE << 6)
STM32_PLLN field.
#define STM32_PLLP (0 << 16)
STM32_PLLP field.
#define STM32_PLLQ (STM32_PLLQ_VALUE << 24)
STM32_PLLQ field.
#define STM32_PLLVCO (STM32_PLLCLKIN * STM32_PLLN_VALUE)
PLL VCO frequency.
#define STM32_PLLCLKOUT (STM32_PLLVCO / STM32_PLLP_VALUE)
PLL output clock frequency.
#define STM32_SYSCLK STM32_HSICLK
System clock source.
#define STM32_HCLK (STM32_SYSCLK / 1)
AHB frequency.
#define STM32_PCLK1 (STM32_HCLK / 1)
APB1 frequency.
#define STM32_PCLK2 (STM32_HCLK / 1)
APB2 frequency.
#define STM32_ACTIVATE_PLLI2S TRUE
PLLI2S activation flag.
#define STM32_PLLI2SN (STM32_PLLI2SN_VALUE << 6)
STM32_PLLI2SN field.
#define STM32_PLLI2SR (STM32_PLLI2SR_VALUE << 28)
STM32_PLLI2SR field.
#define STM32_ACTIVATE_PLLSAI FALSE
PLLSAI activation flag.
#define STM32_PLLSAIN (STM32_PLLSAIN_VALUE << 6)
STM32_PLLSAIN field.
#define STM32_PLLSAIQ (STM32_PLLSAIQ_VALUE << 24)
STM32_PLLSAIQ field.
#define STM32_PLLSAIR (STM32_PLLSAIR_VALUE << 28)
STM32_PLLSAIR field.
#define STM32_PLLI2SVCO (STM32_PLLCLKIN * STM32_PLLI2SN_VALUE)
PLL VCO frequency.
#define STM32_PLLI2SCLKOUT (STM32_PLLI2SVCO / STM32_PLLI2SR_VALUE)
PLLI2S output clock frequency.
#define STM32_MCO1DIVCLK STM32_HSICLK
MCO1 divider clock.
#define STM32_MCO1CLK STM32_MCO1DIVCLK
MCO1 output pin clock.
#define STM32_MCO2DIVCLK STM32_HSECLK
MCO2 divider clock.
#define STM32_MCO2CLK STM32_MCO2DIVCLK
MCO2 output pin clock.
#define STM32_RTCPRE (STM32_RTCPRE_VALUE << 16)
RTC HSE divider setting.
#define STM32_HSEDIVCLK (STM32_HSECLK / STM32_RTCPRE_VALUE)
HSE divider toward RTC clock.
#define STM32_RTCCLK 0
RTC clock.
#define STM32_PLL48CLK (STM32_PLLVCO / STM32_PLLQ_VALUE)
48MHz frequency.
#define STM32_TIMCLK1 (STM32_PCLK1 * 1)
Clock of timers connected to APB1 (Timers 2, 3, 4, 5, 6, 7, 12, 13, 14).
#define STM32_TIMCLK2 (STM32_PCLK2 * 1)
Clock of timers connected to APB2 (Timers 1, 8, 9, 10, 11).
#define STM32_FLASHBITS 0x00000000
Flash settings.
ChibiOS/HAL version identification
#define HAL_VERSION "4.0.5"
HAL version string.
#define CH_HAL_MAJOR 4
HAL version major number.
#define CH_HAL_MINOR 0
HAL version minor number.
#define CH_HAL_PATCH 5
HAL version patch number.
Return codes
#define HAL_SUCCESS false
#define HAL_FAILED true
Platform identification macros
#define PLATFORM_NAME "STM32F439 High Performance with DSP and FPU"
Absolute Maximum Ratings
#define STM32_SYSCLK_MAX 180000000
Absolute maximum system clock.
#define STM32_SYSCLK_MAX 168000000
Absolute maximum system clock.
#define STM32_SYSCLK_MAX 84000000
Absolute maximum system clock.
#define STM32_HSECLK_MAX 26000000
Maximum HSE clock frequency.
#define STM32_HSECLK_MAX 26000000
Maximum HSE clock frequency.
#define STM32_HSECLK_MAX 26000000
Maximum HSE clock frequency.
#define STM32_HSECLK_BYP_MAX 50000000
Maximum HSE clock frequency using an external source.
#define STM32_HSECLK_BYP_MAX 50000000
Maximum HSE clock frequency using an external source.
#define STM32_HSECLK_BYP_MAX 50000000
Maximum HSE clock frequency using an external source.
#define STM32_HSECLK_MIN 4000000
Minimum HSE clock frequency.
#define STM32_HSECLK_MIN 4000000
Minimum HSE clock frequency.
#define STM32_HSECLK_MIN 4000000
Minimum HSE clock frequency.
#define STM32_HSECLK_BYP_MIN 1000000
Minimum HSE clock frequency.
#define STM32_HSECLK_BYP_MIN 1000000
Minimum HSE clock frequency.
#define STM32_HSECLK_BYP_MIN 1000000
Minimum HSE clock frequency.
#define STM32_LSECLK_MAX 32768
Maximum LSE clock frequency.
#define STM32_LSECLK_MAX 32768
Maximum LSE clock frequency.
#define STM32_LSECLK_MAX 32768
Maximum LSE clock frequency.
#define STM32_LSECLK_BYP_MAX 1000000
Maximum LSE clock frequency.
#define STM32_LSECLK_BYP_MAX 1000000
Maximum LSE clock frequency.
#define STM32_LSECLK_BYP_MAX 1000000
Maximum LSE clock frequency.
#define STM32_LSECLK_MIN 32768
Minimum LSE clock frequency.
#define STM32_LSECLK_MIN 32768
Minimum LSE clock frequency.
#define STM32_LSECLK_MIN 32768
Minimum LSE clock frequency.
#define STM32_PLLIN_MAX 2100000
Maximum PLLs input clock frequency.
#define STM32_PLLIN_MAX 2100000
Maximum PLLs input clock frequency.
#define STM32_PLLIN_MAX 2100000
Maximum PLLs input clock frequency.
#define STM32_PLLIN_MIN 950000
Minimum PLLs input clock frequency.
#define STM32_PLLIN_MIN 950000
Minimum PLLs input clock frequency.
#define STM32_PLLIN_MIN 950000
Minimum PLLs input clock frequency.
#define STM32_PLLVCO_MAX 432000000
Maximum PLLs VCO clock frequency.
#define STM32_PLLVCO_MAX 432000000
Maximum PLLs VCO clock frequency.
#define STM32_PLLVCO_MAX 432000000
Maximum PLLs VCO clock frequency.
#define STM32_PLLVCO_MIN 192000000
Minimum PLLs VCO clock frequency.
#define STM32_PLLVCO_MIN 192000000
Minimum PLLs VCO clock frequency.
#define STM32_PLLVCO_MIN 192000000
Minimum PLLs VCO clock frequency.
#define STM32_PLLOUT_MAX 180000000
Maximum PLL output clock frequency.
#define STM32_PLLOUT_MAX 168000000
Maximum PLL output clock frequency.
#define STM32_PLLOUT_MAX 84000000
Maximum PLL output clock frequency.
#define STM32_PLLOUT_MIN 24000000
Minimum PLL output clock frequency.
#define STM32_PLLOUT_MIN 24000000
Minimum PLL output clock frequency.
#define STM32_PLLOUT_MIN 24000000
Minimum PLL output clock frequency.
#define STM32_PCLK1_MAX (STM32_PLLOUT_MAX /4)
Maximum APB1 clock frequency.
#define STM32_PCLK1_MAX 42000000
Maximum APB1 clock frequency.
#define STM32_PCLK1_MAX 42000000
Maximum APB1 clock frequency.
#define STM32_PCLK2_MAX (STM32_PLLOUT_MAX / 2)
Maximum APB2 clock frequency.
#define STM32_PCLK2_MAX 84000000
Maximum APB2 clock frequency.
#define STM32_PCLK2_MAX 84000000
Maximum APB2 clock frequency.
#define STM32_SPII2S_MAX 45000000
Maximum SPI/I2S clock frequency.
#define STM32_SPII2S_MAX 42000000
Maximum SPI/I2S clock frequency.
#define STM32_SPII2S_MAX 42000000
Maximum SPI/I2S clock frequency.
Internal clock sources
#define STM32_HSICLK 16000000
#define STM32_LSICLK 32000
PWR_CR register bits definitions
#define STM32_VOS_SCALE3 0x00004000
#define STM32_VOS_SCALE2 0x00008000
#define STM32_VOS_SCALE1 0x0000C000
#define STM32_PLS_MASK (7 << 5)
#define STM32_PLS_LEV0 (0 << 5)
#define STM32_PLS_LEV1 (1 << 5)
#define STM32_PLS_LEV2 (2 << 5)
#define STM32_PLS_LEV3 (3 << 5)
#define STM32_PLS_LEV4 (4 << 5)
#define STM32_PLS_LEV5 (5 << 5)
#define STM32_PLS_LEV6 (6 << 5)
#define STM32_PLS_LEV7 (7 << 5)
RCC_PLLCFGR register bits definitions
#define STM32_PLLP_MASK (3 << 16)
#define STM32_PLLP_DIV2 (0 << 16)
#define STM32_PLLP_DIV4 (1 << 16)
#define STM32_PLLP_DIV6 (2 << 16)
#define STM32_PLLP_DIV8 (3 << 16)
#define STM32_PLLSRC_HSI (0 << 22)
#define STM32_PLLSRC_HSE (1 << 22)
RCC_CFGR register bits definitions
#define STM32_SW_MASK (3 << 0)
#define STM32_SW_HSI (0 << 0)
#define STM32_SW_HSE (1 << 0)
#define STM32_SW_PLL (2 << 0)
#define STM32_HPRE_MASK (15 << 4)
#define STM32_HPRE_DIV1 (0 << 4)
#define STM32_HPRE_DIV2 (8 << 4)
#define STM32_HPRE_DIV4 (9 << 4)
#define STM32_HPRE_DIV8 (10 << 4)
#define STM32_HPRE_DIV16 (11 << 4)
#define STM32_HPRE_DIV64 (12 << 4)
#define STM32_HPRE_DIV128 (13 << 4)
#define STM32_HPRE_DIV256 (14 << 4)
#define STM32_HPRE_DIV512 (15 << 4)
#define STM32_PPRE1_MASK (7 << 10)
#define STM32_PPRE1_DIV1 (0 << 10)
#define STM32_PPRE1_DIV2 (4 << 10)
#define STM32_PPRE1_DIV4 (5 << 10)
#define STM32_PPRE1_DIV8 (6 << 10)
#define STM32_PPRE1_DIV16 (7 << 10)
#define STM32_PPRE2_MASK (7 << 13)
#define STM32_PPRE2_DIV1 (0 << 13)
#define STM32_PPRE2_DIV2 (4 << 13)
#define STM32_PPRE2_DIV4 (5 << 13)
#define STM32_PPRE2_DIV8 (6 << 13)
#define STM32_PPRE2_DIV16 (7 << 13)
#define STM32_RTCPRE_MASK (31 << 16)
#define STM32_MCO1SEL_MASK (3 << 21)
#define STM32_MCO1SEL_HSI (0 << 21)
#define STM32_MCO1SEL_LSE (1 << 21)
#define STM32_MCO1SEL_HSE (2 << 21)
#define STM32_MCO1SEL_PLL (3 << 21)
#define STM32_I2SSRC_MASK (1 << 23)
#define STM32_I2SSRC_PLLI2S (0 << 23)
#define STM32_I2SSRC_CKIN (1 << 23)
#define STM32_MCO1PRE_MASK (7 << 24)
#define STM32_MCO1PRE_DIV1 (0 << 24)
#define STM32_MCO1PRE_DIV2 (4 << 24)
#define STM32_MCO1PRE_DIV3 (5 << 24)
#define STM32_MCO1PRE_DIV4 (6 << 24)
#define STM32_MCO1PRE_DIV5 (7 << 24)
#define STM32_MCO2PRE_MASK (7 << 27)
#define STM32_MCO2PRE_DIV1 (0 << 27)
#define STM32_MCO2PRE_DIV2 (4 << 27)
#define STM32_MCO2PRE_DIV3 (5 << 27)
#define STM32_MCO2PRE_DIV4 (6 << 27)
#define STM32_MCO2PRE_DIV5 (7 << 27)
#define STM32_MCO2SEL_MASK (3 << 30)
#define STM32_MCO2SEL_SYSCLK (0 << 30)
#define STM32_MCO2SEL_PLLI2S (1 << 30)
#define STM32_MCO2SEL_HSE (2 << 30)
#define STM32_MCO2SEL_PLL (3 << 30)
RCC_PLLI2SCFGR register bits definitions
#define STM32_PLLI2SN_MASK (511 << 6)
#define STM32_PLLI2SR_MASK (7 << 28)
RCC_BDCR register bits definitions
#define STM32_RTCSEL_MASK (3 << 8)
#define STM32_RTCSEL_NOCLOCK (0 << 8)
#define STM32_RTCSEL_LSE (1 << 8)
#define STM32_RTCSEL_LSI (2 << 8)
#define STM32_RTCSEL_HSEDIV (3 << 8)
Configuration options
#define STM32_NO_INIT FALSE
Disables the PWR/RCC initialization in the HAL.
#define STM32_PVD_ENABLE FALSE
Enables or disables the programmable voltage detector.
#define STM32_PLS STM32_PLS_LEV0
Sets voltage level for programmable voltage detector.
#define STM32_BKPRAM_ENABLE FALSE
Enables the backup RAM regulator.
#define STM32_HSI_ENABLED TRUE
Enables or disables the HSI clock source.
#define STM32_LSI_ENABLED FALSE
Enables or disables the LSI clock source.
#define STM32_HSE_ENABLED TRUE
Enables or disables the HSE clock source.
#define STM32_LSE_ENABLED FALSE
Enables or disables the LSE clock source.
#define STM32_CLOCK48_REQUIRED TRUE
USB/SDIO clock setting.
#define STM32_SW STM32_SW_PLL
Main clock source selection.
#define STM32_PLLSRC STM32_PLLSRC_HSE
Clock source for the PLLs.
#define STM32_PLLM_VALUE 8
PLLM divider value.
#define STM32_PLLN_VALUE 336
PLLN multiplier value.
#define STM32_PLLP_VALUE 2
PLLP divider value.
#define STM32_PLLQ_VALUE 7
PLLQ multiplier value.
#define STM32_HPRE STM32_HPRE_DIV1
AHB prescaler value.
#define STM32_PPRE1 STM32_PPRE1_DIV4
APB1 prescaler value.
#define STM32_PPRE2 STM32_PPRE2_DIV2
APB2 prescaler value.
#define STM32_RTCSEL STM32_RTCSEL_LSE
RTC clock source.
#define STM32_RTCPRE_VALUE 8
RTC HSE prescaler value.
#define STM32_MCO1SEL STM32_MCO1SEL_HSI
MCO1 clock source value.
#define STM32_MCO1PRE STM32_MCO1PRE_DIV1
MCO1 prescaler value.
#define STM32_MCO2SEL STM32_MCO2SEL_SYSCLK
MCO2 clock source value.
#define STM32_MCO2PRE STM32_MCO2PRE_DIV5
MCO2 prescaler value.
#define STM32_I2SSRC STM32_I2SSRC_CKIN
I2S clock source.
#define STM32_PLLI2SN_VALUE 192
PLLI2SN multiplier value.
#define STM32_PLLI2SR_VALUE 5
PLLI2SR multiplier value.
#define STM32_PLLSAIQ_VALUE 8
PLLSAIQ value.
#define STM32_PLLSAIN_VALUE 120
PLLSAIQ value.
#define STM32_PLLSAIR_VALUE 4
PLLSAIQ value.
STM32F4xx/STM32F2xx capabilities
#define STM32_ADC_HANDLER Vector88
#define STM32_ADC_NUMBER 18
#define STM32_HAS_ADC1 TRUE
#define STM32_ADC1_DMA_MSK
#define STM32_ADC1_DMA_CHN 0x00000000
#define STM32_HAS_ADC2 TRUE
#define STM32_ADC2_DMA_MSK
#define STM32_ADC2_DMA_CHN 0x00001100
#define STM32_HAS_ADC3 TRUE
#define STM32_ADC3_DMA_MSK
#define STM32_ADC3_DMA_CHN 0x00000022
#define STM32_HAS_ADC4 FALSE
#define STM32_HAS_SDADC1 FALSE
#define STM32_HAS_SDADC2 FALSE
#define STM32_HAS_SDADC3 FALSE
#define STM32_HAS_CAN1 TRUE
#define STM32_HAS_CAN2 TRUE
#define STM32_CAN_MAX_FILTERS 28
#define STM32_HAS_DAC1_CH1 TRUE
#define STM32_DAC1_CH1_DMA_MSK (STM32_DMA_STREAM_ID_MSK(1, 5))
#define STM32_DAC1_CH1_DMA_CHN 0x00700000
#define STM32_HAS_DAC1_CH2 TRUE
#define STM32_DAC1_CH2_DMA_MSK (STM32_DMA_STREAM_ID_MSK(1, 6))
#define STM32_DAC1_CH2_DMA_CHN 0x07000000
#define STM32_HAS_DAC2_CH1 FALSE
#define STM32_HAS_DAC2_CH2 FALSE
#define STM32_ADVANCED_DMA TRUE
#define STM32_DMA_CACHE_HANDLING FALSE
#define STM32_HAS_DMA1 TRUE
#define STM32_DMA1_CH0_HANDLER Vector6C
#define STM32_DMA1_CH1_HANDLER Vector70
#define STM32_DMA1_CH2_HANDLER Vector74
#define STM32_DMA1_CH3_HANDLER Vector78
#define STM32_DMA1_CH4_HANDLER Vector7C
#define STM32_DMA1_CH5_HANDLER Vector80
#define STM32_DMA1_CH6_HANDLER Vector84
#define STM32_DMA1_CH7_HANDLER VectorFC
#define STM32_DMA1_CH0_NUMBER 11
#define STM32_DMA1_CH1_NUMBER 12
#define STM32_DMA1_CH2_NUMBER 13
#define STM32_DMA1_CH3_NUMBER 14
#define STM32_DMA1_CH4_NUMBER 15
#define STM32_DMA1_CH5_NUMBER 16
#define STM32_DMA1_CH6_NUMBER 17
#define STM32_DMA1_CH7_NUMBER 47
#define STM32_HAS_DMA2 TRUE
#define STM32_DMA2_CH0_HANDLER Vector120
#define STM32_DMA2_CH1_HANDLER Vector124
#define STM32_DMA2_CH2_HANDLER Vector128
#define STM32_DMA2_CH3_HANDLER Vector12C
#define STM32_DMA2_CH4_HANDLER Vector130
#define STM32_DMA2_CH5_HANDLER Vector150
#define STM32_DMA2_CH6_HANDLER Vector154
#define STM32_DMA2_CH7_HANDLER Vector158
#define STM32_DMA2_CH0_NUMBER 56
#define STM32_DMA2_CH1_NUMBER 57
#define STM32_DMA2_CH2_NUMBER 58
#define STM32_DMA2_CH3_NUMBER 59
#define STM32_DMA2_CH4_NUMBER 60
#define STM32_DMA2_CH5_NUMBER 68
#define STM32_DMA2_CH6_NUMBER 69
#define STM32_DMA2_CH7_NUMBER 70
#define STM32_HAS_ETH TRUE
#define STM32_ETH_HANDLER Vector134
#define STM32_ETH_NUMBER 61
#define STM32_EXTI_NUM_LINES 23
#define STM32_EXTI_IMR_MASK 0x00000000U
#define STM32_HAS_GPIOA TRUE
#define STM32_HAS_GPIOB TRUE
#define STM32_HAS_GPIOC TRUE
#define STM32_HAS_GPIOD TRUE
#define STM32_HAS_GPIOE TRUE
#define STM32_HAS_GPIOH TRUE
#define STM32_HAS_GPIOF TRUE
#define STM32_HAS_GPIOG TRUE
#define STM32_HAS_GPIOI TRUE
#define STM32_HAS_GPIOJ FALSE
#define STM32_HAS_GPIOK FALSE
#define STM32_GPIO_EN_MASK
#define STM32_HAS_I2C1 TRUE
#define STM32_I2C1_RX_DMA_MSK
#define STM32_I2C1_RX_DMA_CHN 0x00100001
#define STM32_I2C1_TX_DMA_MSK
#define STM32_I2C1_TX_DMA_CHN 0x11000000
#define STM32_HAS_I2C2 TRUE
#define STM32_I2C2_RX_DMA_MSK
#define STM32_I2C2_RX_DMA_CHN 0x00007700
#define STM32_I2C2_TX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 7)
#define STM32_I2C2_TX_DMA_CHN 0x70000000
#define STM32_HAS_I2C3 TRUE
#define STM32_I2C3_RX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 2)
#define STM32_I2C3_RX_DMA_CHN 0x00000300
#define STM32_I2C3_TX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 4)
#define STM32_I2C3_TX_DMA_CHN 0x00030000
#define STM32_HAS_I2C4 FALSE
#define STM32_HAS_RTC TRUE
#define STM32_RTC_HAS_SUBSECONDS TRUE
#define STM32_RTC_HAS_PERIODIC_WAKEUPS TRUE
#define STM32_RTC_NUM_ALARMS 2
#define STM32_RTC_HAS_INTERRUPTS FALSE
#define STM32_HAS_SDIO TRUE
#define STM32_SDC_SDIO_DMA_MSK
#define STM32_SDC_SDIO_DMA_CHN 0x04004000
#define STM32_HAS_SPI1 TRUE
#define STM32_SPI1_SUPPORTS_I2S FALSE
#define STM32_SPI1_RX_DMA_MSK
#define STM32_SPI1_RX_DMA_CHN 0x00000303
#define STM32_SPI1_TX_DMA_MSK
#define STM32_SPI1_TX_DMA_CHN 0x00303000
#define STM32_HAS_SPI2 TRUE
#define STM32_SPI2_SUPPORTS_I2S TRUE
#define STM32_SPI2_I2S_FULLDUPLEX TRUE
#define STM32_SPI2_RX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 3)
#define STM32_SPI2_RX_DMA_CHN 0x00000000
#define STM32_SPI2_TX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 4)
#define STM32_SPI2_TX_DMA_CHN 0x00000000
#define STM32_HAS_SPI3 TRUE
#define STM32_SPI3_SUPPORTS_I2S TRUE
#define STM32_SPI3_I2S_FULLDUPLEX TRUE
#define STM32_SPI3_RX_DMA_MSK
#define STM32_SPI3_RX_DMA_CHN 0x00000000
#define STM32_SPI3_TX_DMA_MSK
#define STM32_SPI3_TX_DMA_CHN 0x00000000
#define STM32_HAS_SPI4 TRUE
#define STM32_SPI4_SUPPORTS_I2S FALSE
#define STM32_SPI4_RX_DMA_MSK
#define STM32_SPI4_RX_DMA_CHN 0x00005004
#define STM32_SPI4_TX_DMA_MSK
#define STM32_SPI4_TX_DMA_CHN 0x00050040
#define STM32_HAS_SPI5 TRUE
#define STM32_SPI5_SUPPORTS_I2S FALSE
#define STM32_SPI5_RX_DMA_MSK
#define STM32_SPI5_RX_DMA_CHN 0x00702000
#define STM32_SPI5_TX_DMA_MSK
#define STM32_SPI5_TX_DMA_CHN 0x07020000
#define STM32_HAS_SPI6 TRUE
#define STM32_SPI6_SUPPORTS_I2S FALSE
#define STM32_SPI6_RX_DMA_MSK (STM32_DMA_STREAM_ID_MSK(2, 6))
#define STM32_SPI6_RX_DMA_CHN 0x01000000
#define STM32_SPI6_TX_DMA_MSK (STM32_DMA_STREAM_ID_MSK(2, 5))
#define STM32_SPI6_TX_DMA_CHN 0x00100000
#define STM32_TIM_MAX_CHANNELS 4
#define STM32_HAS_TIM1 TRUE
#define STM32_TIM1_IS_32BITS FALSE
#define STM32_TIM1_CHANNELS 4
#define STM32_HAS_TIM2 TRUE
#define STM32_TIM2_IS_32BITS TRUE
#define STM32_TIM2_CHANNELS 4
#define STM32_HAS_TIM3 TRUE
#define STM32_TIM3_IS_32BITS FALSE
#define STM32_TIM3_CHANNELS 4
#define STM32_HAS_TIM4 TRUE
#define STM32_TIM4_IS_32BITS FALSE
#define STM32_TIM4_CHANNELS 4
#define STM32_HAS_TIM5 TRUE
#define STM32_TIM5_IS_32BITS TRUE
#define STM32_TIM5_CHANNELS 4
#define STM32_HAS_TIM6 TRUE
#define STM32_TIM6_IS_32BITS FALSE
#define STM32_TIM6_CHANNELS 0
#define STM32_HAS_TIM7 TRUE
#define STM32_TIM7_IS_32BITS FALSE
#define STM32_TIM7_CHANNELS 0
#define STM32_HAS_TIM8 TRUE
#define STM32_TIM8_IS_32BITS FALSE
#define STM32_TIM8_CHANNELS 6
#define STM32_HAS_TIM9 TRUE
#define STM32_TIM9_IS_32BITS FALSE
#define STM32_TIM9_CHANNELS 2
#define STM32_HAS_TIM10 TRUE
#define STM32_TIM10_IS_32BITS FALSE
#define STM32_TIM10_CHANNELS 2
#define STM32_HAS_TIM11 TRUE
#define STM32_TIM11_IS_32BITS FALSE
#define STM32_TIM11_CHANNELS 2
#define STM32_HAS_TIM12 TRUE
#define STM32_TIM12_IS_32BITS FALSE
#define STM32_TIM12_CHANNELS 2
#define STM32_HAS_TIM13 TRUE
#define STM32_TIM13_IS_32BITS FALSE
#define STM32_TIM13_CHANNELS 2
#define STM32_HAS_TIM14 TRUE
#define STM32_TIM14_IS_32BITS FALSE
#define STM32_TIM14_CHANNELS 2
#define STM32_HAS_TIM15 FALSE
#define STM32_HAS_TIM16 FALSE
#define STM32_HAS_TIM17 FALSE
#define STM32_HAS_TIM18 FALSE
#define STM32_HAS_TIM19 FALSE
#define STM32_HAS_TIM20 FALSE
#define STM32_HAS_TIM21 FALSE
#define STM32_HAS_TIM22 FALSE
#define STM32_HAS_USART1 TRUE
#define STM32_USART1_RX_DMA_MSK
#define STM32_USART1_RX_DMA_CHN 0x00400400
#define STM32_USART1_TX_DMA_MSK STM32_DMA_STREAM_ID_MSK(2, 7)
#define STM32_USART1_TX_DMA_CHN 0x40000000
#define STM32_HAS_USART2 TRUE
#define STM32_USART2_RX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 5)
#define STM32_USART2_RX_DMA_CHN 0x00400000
#define STM32_USART2_TX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 6)
#define STM32_USART2_TX_DMA_CHN 0x04000000
#define STM32_HAS_USART3 TRUE
#define STM32_USART3_RX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 1)
#define STM32_USART3_RX_DMA_CHN 0x00000040
#define STM32_USART3_TX_DMA_MSK
#define STM32_USART3_TX_DMA_CHN 0x00074000
#define STM32_HAS_UART4 TRUE
#define STM32_UART4_RX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 2)
#define STM32_UART4_RX_DMA_CHN 0x00000400
#define STM32_UART4_TX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 4)
#define STM32_UART4_TX_DMA_CHN 0x00040000
#define STM32_HAS_UART5 TRUE
#define STM32_UART5_RX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 0)
#define STM32_UART5_RX_DMA_CHN 0x00000004
#define STM32_UART5_TX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 7)
#define STM32_UART5_TX_DMA_CHN 0x40000000
#define STM32_HAS_USART6 TRUE
#define STM32_USART6_RX_DMA_MSK
#define STM32_USART6_RX_DMA_CHN 0x00000550
#define STM32_USART6_TX_DMA_MSK
#define STM32_USART6_TX_DMA_CHN 0x55000000
#define STM32_HAS_UART7 TRUE
#define STM32_UART7_RX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 3)
#define STM32_UART7_RX_DMA_CHN 0x00005000
#define STM32_UART7_TX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 1)
#define STM32_UART7_TX_DMA_CHN 0x00000050
#define STM32_HAS_UART8 TRUE
#define STM32_UART8_RX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 6)
#define STM32_UART8_RX_DMA_CHN 0x05000000
#define STM32_UART8_TX_DMA_MSK STM32_DMA_STREAM_ID_MSK(1, 0)
#define STM32_UART8_TX_DMA_CHN 0x00000005
#define STM32_HAS_LPUART1 FALSE
#define STM32_HAS_USB FALSE
#define STM32_HAS_OTG1 TRUE
#define STM32_HAS_OTG2 TRUE
#define STM32_HAS_IWDG TRUE
#define STM32_IWDG_IS_WINDOWED FALSE
#define STM32_HAS_LTDC TRUE
#define STM32_HAS_DMA2D TRUE
#define STM32_HAS_FSMC TRUE
#define STM32_FSMC_IS_FMC TRUE
#define STM32_FSMC_HANDLER Vector100
#define STM32_FSMC_NUMBER 48
#define STM32_HAS_CRC TRUE
#define STM32_CRC_PROGRAMMABLE FALSE
Functions
void halInit (void)
HAL initialization.
static void hal_lld_backup_domain_init (void)
Initializes the backup domain.
void hal_lld_init (void)
Low level HAL driver initialization.
void stm32_clock_init (void)
STM32F2xx clocks and PLL initialization.
Variables
uint32_t SystemCoreClock = STM32_HCLK
CMSIS system core clock variable.
Macro Definition Documentation
_CHIBIOS_HAL_
#define _CHIBIOS_HAL_
ChibiOS/HAL identification macro.
Definition at line 92 of file hal.h.
CH_HAL_STABLE
#define CH_HAL_STABLE 1
Stable release flag.
Definition at line 97 of file hal.h.
HAL_VERSION
#define HAL_VERSION "4.0.5"
HAL version string.
Definition at line 106 of file hal.h.
CH_HAL_MAJOR
#define CH_HAL_MAJOR 4
HAL version major number.
Definition at line 111 of file hal.h.
CH_HAL_MINOR
#define CH_HAL_MINOR 0
HAL version minor number.
Definition at line 116 of file hal.h.
CH_HAL_PATCH
#define CH_HAL_PATCH 5
HAL version patch number.
Definition at line 121 of file hal.h.
HAL_IMPLEMENTS_COUNTERS
#define HAL_IMPLEMENTS_COUNTERS TRUE
Defines the support for realtime counters in the HAL.
Definition at line 55 of file hal_lld.h.
STM32_SYSCLK_MAX [1/3]
#define STM32_SYSCLK_MAX 180000000
Absolute maximum system clock.
Definition at line 228 of file hal_lld.h.
STM32_SYSCLK_MAX [2/3]
#define STM32_SYSCLK_MAX 168000000
Absolute maximum system clock.
Definition at line 228 of file hal_lld.h.
STM32_SYSCLK_MAX [3/3]
#define STM32_SYSCLK_MAX 84000000
Absolute maximum system clock.
Definition at line 228 of file hal_lld.h.
STM32_HSECLK_MAX [1/3]
#define STM32_HSECLK_MAX 26000000
Maximum HSE clock frequency.
Definition at line 229 of file hal_lld.h.
STM32_HSECLK_MAX [2/3]
#define STM32_HSECLK_MAX 26000000
Maximum HSE clock frequency.
Definition at line 229 of file hal_lld.h.
STM32_HSECLK_MAX [3/3]
#define STM32_HSECLK_MAX 26000000
Maximum HSE clock frequency.
Definition at line 229 of file hal_lld.h.
STM32_HSECLK_BYP_MAX [1/3]
#define STM32_HSECLK_BYP_MAX 50000000
Maximum HSE clock frequency using an external source.
Definition at line 230 of file hal_lld.h.
STM32_HSECLK_BYP_MAX [2/3]
#define STM32_HSECLK_BYP_MAX 50000000
Maximum HSE clock frequency using an external source.
Definition at line 230 of file hal_lld.h.
STM32_HSECLK_BYP_MAX [3/3]
#define STM32_HSECLK_BYP_MAX 50000000
Maximum HSE clock frequency using an external source.
Definition at line 230 of file hal_lld.h.
STM32_HSECLK_MIN [1/3]
#define STM32_HSECLK_MIN 4000000
Minimum HSE clock frequency.
Definition at line 231 of file hal_lld.h.
STM32_HSECLK_MIN [2/3]
#define STM32_HSECLK_MIN 4000000
Minimum HSE clock frequency.
Definition at line 231 of file hal_lld.h.
STM32_HSECLK_MIN [3/3]
#define STM32_HSECLK_MIN 4000000
Minimum HSE clock frequency.
Definition at line 231 of file hal_lld.h.
STM32_HSECLK_BYP_MIN [1/3]
#define STM32_HSECLK_BYP_MIN 1000000
Minimum HSE clock frequency.
Definition at line 232 of file hal_lld.h.
STM32_HSECLK_BYP_MIN [2/3]
#define STM32_HSECLK_BYP_MIN 1000000
Minimum HSE clock frequency.
Definition at line 232 of file hal_lld.h.
STM32_HSECLK_BYP_MIN [3/3]
#define STM32_HSECLK_BYP_MIN 1000000
Minimum HSE clock frequency.
Definition at line 232 of file hal_lld.h.
STM32_LSECLK_MAX [1/3]
#define STM32_LSECLK_MAX 32768
Maximum LSE clock frequency.
Definition at line 233 of file hal_lld.h.
STM32_LSECLK_MAX [2/3]
#define STM32_LSECLK_MAX 32768
Maximum LSE clock frequency.
Definition at line 233 of file hal_lld.h.
STM32_LSECLK_MAX [3/3]
#define STM32_LSECLK_MAX 32768
Maximum LSE clock frequency.
Definition at line 233 of file hal_lld.h.
STM32_LSECLK_BYP_MAX [1/3]
#define STM32_LSECLK_BYP_MAX 1000000
Maximum LSE clock frequency.
Definition at line 234 of file hal_lld.h.
STM32_LSECLK_BYP_MAX [2/3]
#define STM32_LSECLK_BYP_MAX 1000000
Maximum LSE clock frequency.
Definition at line 234 of file hal_lld.h.
STM32_LSECLK_BYP_MAX [3/3]
#define STM32_LSECLK_BYP_MAX 1000000
Maximum LSE clock frequency.
Definition at line 234 of file hal_lld.h.
STM32_LSECLK_MIN [1/3]
#define STM32_LSECLK_MIN 32768
Minimum LSE clock frequency.
Definition at line 235 of file hal_lld.h.
STM32_LSECLK_MIN [2/3]
#define STM32_LSECLK_MIN 32768
Minimum LSE clock frequency.
Definition at line 235 of file hal_lld.h.
STM32_LSECLK_MIN [3/3]
#define STM32_LSECLK_MIN 32768
Minimum LSE clock frequency.
Definition at line 235 of file hal_lld.h.
STM32_PLLIN_MAX [1/3]
#define STM32_PLLIN_MAX 2100000
Maximum PLLs input clock frequency.
Definition at line 236 of file hal_lld.h.
STM32_PLLIN_MAX [2/3]
#define STM32_PLLIN_MAX 2100000
Maximum PLLs input clock frequency.
Definition at line 236 of file hal_lld.h.
STM32_PLLIN_MAX [3/3]
#define STM32_PLLIN_MAX 2100000
Maximum PLLs input clock frequency.
Definition at line 236 of file hal_lld.h.
STM32_PLLIN_MIN [1/3]
#define STM32_PLLIN_MIN 950000
Minimum PLLs input clock frequency.
Definition at line 237 of file hal_lld.h.
STM32_PLLIN_MIN [2/3]
#define STM32_PLLIN_MIN 950000
Minimum PLLs input clock frequency.
Definition at line 237 of file hal_lld.h.
STM32_PLLIN_MIN [3/3]
#define STM32_PLLIN_MIN 950000
Minimum PLLs input clock frequency.
Definition at line 237 of file hal_lld.h.
STM32_PLLVCO_MAX [1/3]
#define STM32_PLLVCO_MAX 432000000
Maximum PLLs VCO clock frequency.
Definition at line 238 of file hal_lld.h.
STM32_PLLVCO_MAX [2/3]
#define STM32_PLLVCO_MAX 432000000
Maximum PLLs VCO clock frequency.
Definition at line 238 of file hal_lld.h.
STM32_PLLVCO_MAX [3/3]
#define STM32_PLLVCO_MAX 432000000
Maximum PLLs VCO clock frequency.
Definition at line 238 of file hal_lld.h.
STM32_PLLVCO_MIN [1/3]
#define STM32_PLLVCO_MIN 192000000
Minimum PLLs VCO clock frequency.
Definition at line 239 of file hal_lld.h.
STM32_PLLVCO_MIN [2/3]
#define STM32_PLLVCO_MIN 192000000
Minimum PLLs VCO clock frequency.
Definition at line 239 of file hal_lld.h.
STM32_PLLVCO_MIN [3/3]
#define STM32_PLLVCO_MIN 192000000
Minimum PLLs VCO clock frequency.
Definition at line 239 of file hal_lld.h.
STM32_PLLOUT_MAX [1/3]
#define STM32_PLLOUT_MAX 180000000
Maximum PLL output clock frequency.
Definition at line 240 of file hal_lld.h.
STM32_PLLOUT_MAX [2/3]
#define STM32_PLLOUT_MAX 168000000
Maximum PLL output clock frequency.
Definition at line 240 of file hal_lld.h.
STM32_PLLOUT_MAX [3/3]
#define STM32_PLLOUT_MAX 84000000
Maximum PLL output clock frequency.
Definition at line 240 of file hal_lld.h.
STM32_PLLOUT_MIN [1/3]
#define STM32_PLLOUT_MIN 24000000
Minimum PLL output clock frequency.
Definition at line 241 of file hal_lld.h.
STM32_PLLOUT_MIN [2/3]
#define STM32_PLLOUT_MIN 24000000
Minimum PLL output clock frequency.
Definition at line 241 of file hal_lld.h.
STM32_PLLOUT_MIN [3/3]
#define STM32_PLLOUT_MIN 24000000
Minimum PLL output clock frequency.
Definition at line 241 of file hal_lld.h.
STM32_PCLK1_MAX [1/3]
#define STM32_PCLK1_MAX (STM32_PLLOUT_MAX /4)
Maximum APB1 clock frequency.
Definition at line 242 of file hal_lld.h.
STM32_PCLK1_MAX [2/3]
#define STM32_PCLK1_MAX 42000000
Maximum APB1 clock frequency.
Definition at line 242 of file hal_lld.h.
STM32_PCLK1_MAX [3/3]
#define STM32_PCLK1_MAX 42000000
Maximum APB1 clock frequency.
Definition at line 242 of file hal_lld.h.
STM32_PCLK2_MAX [1/3]
#define STM32_PCLK2_MAX (STM32_PLLOUT_MAX / 2)
Maximum APB2 clock frequency.
Definition at line 243 of file hal_lld.h.
STM32_PCLK2_MAX [2/3]
#define STM32_PCLK2_MAX 84000000
Maximum APB2 clock frequency.
Definition at line 243 of file hal_lld.h.
STM32_PCLK2_MAX [3/3]
#define STM32_PCLK2_MAX 84000000
Maximum APB2 clock frequency.
Definition at line 243 of file hal_lld.h.
STM32_SPII2S_MAX [1/3]
#define STM32_SPII2S_MAX 45000000
Maximum SPI/I2S clock frequency.
Definition at line 244 of file hal_lld.h.
STM32_SPII2S_MAX [2/3]
#define STM32_SPII2S_MAX 42000000
Maximum SPI/I2S clock frequency.
Definition at line 244 of file hal_lld.h.
STM32_SPII2S_MAX [3/3]
#define STM32_SPII2S_MAX 42000000
Maximum SPI/I2S clock frequency.
Definition at line 244 of file hal_lld.h.
STM32_HSICLK
#define STM32_HSICLK 16000000
High speed internal clock.
Definition at line 292 of file hal_lld.h.
STM32_LSICLK
#define STM32_LSICLK 32000
Low speed internal clock.
Definition at line 293 of file hal_lld.h.
STM32_PLS_MASK
#define STM32_PLS_MASK (7 << 5)
PLS bits mask.
Definition at line 303 of file hal_lld.h.
Referenced by hal_lld_init().
STM32_PLS_LEV0
#define STM32_PLS_LEV0 (0 << 5)
PVD level 0.
Definition at line 304 of file hal_lld.h.
STM32_PLS_LEV1
#define STM32_PLS_LEV1 (1 << 5)
PVD level 1.
Definition at line 305 of file hal_lld.h.
STM32_PLS_LEV2
#define STM32_PLS_LEV2 (2 << 5)
PVD level 2.
Definition at line 306 of file hal_lld.h.
STM32_PLS_LEV3
#define STM32_PLS_LEV3 (3 << 5)
PVD level 3.
Definition at line 307 of file hal_lld.h.
STM32_PLS_LEV4
#define STM32_PLS_LEV4 (4 << 5)
PVD level 4.
Definition at line 308 of file hal_lld.h.
STM32_PLS_LEV5
#define STM32_PLS_LEV5 (5 << 5)
PVD level 5.
Definition at line 309 of file hal_lld.h.
STM32_PLS_LEV6
#define STM32_PLS_LEV6 (6 << 5)
PVD level 6.
Definition at line 310 of file hal_lld.h.
STM32_PLS_LEV7
#define STM32_PLS_LEV7 (7 << 5)
PVD level 7.
Definition at line 311 of file hal_lld.h.
STM32_PLLP_MASK
#define STM32_PLLP_MASK (3 << 16)
PLLP mask.
Definition at line 318 of file hal_lld.h.
STM32_PLLP_DIV2
#define STM32_PLLP_DIV2 (0 << 16)
PLL clock divided by 2.
Definition at line 319 of file hal_lld.h.
STM32_PLLP_DIV4
#define STM32_PLLP_DIV4 (1 << 16)
PLL clock divided by 4.
Definition at line 320 of file hal_lld.h.
STM32_PLLP_DIV6
#define STM32_PLLP_DIV6 (2 << 16)
PLL clock divided by 6.
Definition at line 321 of file hal_lld.h.
STM32_PLLP_DIV8
#define STM32_PLLP_DIV8 (3 << 16)
PLL clock divided by 8.
Definition at line 322 of file hal_lld.h.
STM32_PLLSRC_HSI
#define STM32_PLLSRC_HSI (0 << 22)
PLL clock source is HSI.
Definition at line 324 of file hal_lld.h.
STM32_PLLSRC_HSE
#define STM32_PLLSRC_HSE (1 << 22)
PLL clock source is HSE.
Definition at line 325 of file hal_lld.h.
STM32_SW_MASK
#define STM32_SW_MASK (3 << 0)
SW mask.
Definition at line 332 of file hal_lld.h.
STM32_SW_HSI
#define STM32_SW_HSI (0 << 0)
SYSCLK source is HSI.
Definition at line 333 of file hal_lld.h.
STM32_SW_HSE
#define STM32_SW_HSE (1 << 0)
SYSCLK source is HSE.
Definition at line 334 of file hal_lld.h.
STM32_SW_PLL
#define STM32_SW_PLL (2 << 0)
SYSCLK source is PLL.
Definition at line 335 of file hal_lld.h.
STM32_HPRE_MASK
#define STM32_HPRE_MASK (15 << 4)
HPRE mask.
Definition at line 337 of file hal_lld.h.
STM32_HPRE_DIV1
#define STM32_HPRE_DIV1 (0 << 4)
SYSCLK divided by 1.
Definition at line 338 of file hal_lld.h.
STM32_HPRE_DIV2
#define STM32_HPRE_DIV2 (8 << 4)
SYSCLK divided by 2.
Definition at line 339 of file hal_lld.h.
STM32_HPRE_DIV4
#define STM32_HPRE_DIV4 (9 << 4)
SYSCLK divided by 4.
Definition at line 340 of file hal_lld.h.
STM32_HPRE_DIV8
#define STM32_HPRE_DIV8 (10 << 4)
SYSCLK divided by 8.
Definition at line 341 of file hal_lld.h.
STM32_HPRE_DIV16
#define STM32_HPRE_DIV16 (11 << 4)
SYSCLK divided by 16.
Definition at line 342 of file hal_lld.h.
STM32_HPRE_DIV64
#define STM32_HPRE_DIV64 (12 << 4)
SYSCLK divided by 64.
Definition at line 343 of file hal_lld.h.
STM32_HPRE_DIV128
#define STM32_HPRE_DIV128 (13 << 4)
SYSCLK divided by 128.
Definition at line 344 of file hal_lld.h.
STM32_HPRE_DIV256
#define STM32_HPRE_DIV256 (14 << 4)
SYSCLK divided by 256.
Definition at line 345 of file hal_lld.h.
STM32_HPRE_DIV512
#define STM32_HPRE_DIV512 (15 << 4)
SYSCLK divided by 512.
Definition at line 346 of file hal_lld.h.
STM32_PPRE1_MASK
#define STM32_PPRE1_MASK (7 << 10)
PPRE1 mask.
Definition at line 348 of file hal_lld.h.
STM32_PPRE1_DIV1
#define STM32_PPRE1_DIV1 (0 << 10)
HCLK divided by 1.
Definition at line 349 of file hal_lld.h.
STM32_PPRE1_DIV2
#define STM32_PPRE1_DIV2 (4 << 10)
HCLK divided by 2.
Definition at line 350 of file hal_lld.h.
STM32_PPRE1_DIV4
#define STM32_PPRE1_DIV4 (5 << 10)
HCLK divided by 4.
Definition at line 351 of file hal_lld.h.
STM32_PPRE1_DIV8
#define STM32_PPRE1_DIV8 (6 << 10)
HCLK divided by 8.
Definition at line 352 of file hal_lld.h.
STM32_PPRE1_DIV16
#define STM32_PPRE1_DIV16 (7 << 10)
HCLK divided by 16.
Definition at line 353 of file hal_lld.h.
STM32_PPRE2_MASK
#define STM32_PPRE2_MASK (7 << 13)
PPRE2 mask.
Definition at line 355 of file hal_lld.h.
STM32_PPRE2_DIV1
#define STM32_PPRE2_DIV1 (0 << 13)
HCLK divided by 1.
Definition at line 356 of file hal_lld.h.
STM32_PPRE2_DIV2
#define STM32_PPRE2_DIV2 (4 << 13)
HCLK divided by 2.
Definition at line 357 of file hal_lld.h.
STM32_PPRE2_DIV4
#define STM32_PPRE2_DIV4 (5 << 13)
HCLK divided by 4.
Definition at line 358 of file hal_lld.h.
STM32_PPRE2_DIV8
#define STM32_PPRE2_DIV8 (6 << 13)
HCLK divided by 8.
Definition at line 359 of file hal_lld.h.
STM32_PPRE2_DIV16
#define STM32_PPRE2_DIV16 (7 << 13)
HCLK divided by 16.
Definition at line 360 of file hal_lld.h.
STM32_RTCPRE_MASK
#define STM32_RTCPRE_MASK (31 << 16)
RTCPRE mask.
Definition at line 362 of file hal_lld.h.
STM32_MCO1SEL_MASK
#define STM32_MCO1SEL_MASK (3 << 21)
MCO1 mask.
Definition at line 364 of file hal_lld.h.
STM32_MCO1SEL_HSI
#define STM32_MCO1SEL_HSI (0 << 21)
HSI clock on MCO1 pin.
Definition at line 365 of file hal_lld.h.
STM32_MCO1SEL_LSE
#define STM32_MCO1SEL_LSE (1 << 21)
LSE clock on MCO1 pin.
Definition at line 366 of file hal_lld.h.
STM32_MCO1SEL_HSE
#define STM32_MCO1SEL_HSE (2 << 21)
HSE clock on MCO1 pin.
Definition at line 367 of file hal_lld.h.
STM32_MCO1SEL_PLL
#define STM32_MCO1SEL_PLL (3 << 21)
PLL clock on MCO1 pin.
Definition at line 368 of file hal_lld.h.
STM32_I2SSRC_MASK
#define STM32_I2SSRC_MASK (1 << 23)
I2CSRC mask.
Definition at line 370 of file hal_lld.h.
STM32_I2SSRC_PLLI2S
#define STM32_I2SSRC_PLLI2S (0 << 23)
I2SSRC is PLLI2S.
Definition at line 371 of file hal_lld.h.
STM32_I2SSRC_CKIN
#define STM32_I2SSRC_CKIN (1 << 23)
I2S_CKIN is PLLI2S.
Definition at line 372 of file hal_lld.h.
STM32_MCO1PRE_MASK
#define STM32_MCO1PRE_MASK (7 << 24)
MCO1PRE mask.
Definition at line 374 of file hal_lld.h.
STM32_MCO1PRE_DIV1
#define STM32_MCO1PRE_DIV1 (0 << 24)
MCO1 divided by 1.
Definition at line 375 of file hal_lld.h.
STM32_MCO1PRE_DIV2
#define STM32_MCO1PRE_DIV2 (4 << 24)
MCO1 divided by 2.
Definition at line 376 of file hal_lld.h.
STM32_MCO1PRE_DIV3
#define STM32_MCO1PRE_DIV3 (5 << 24)
MCO1 divided by 3.
Definition at line 377 of file hal_lld.h.
STM32_MCO1PRE_DIV4
#define STM32_MCO1PRE_DIV4 (6 << 24)
MCO1 divided by 4.
Definition at line 378 of file hal_lld.h.
STM32_MCO1PRE_DIV5
#define STM32_MCO1PRE_DIV5 (7 << 24)
MCO1 divided by 5.
Definition at line 379 of file hal_lld.h.
STM32_MCO2PRE_MASK
#define STM32_MCO2PRE_MASK (7 << 27)
MCO2PRE mask.
Definition at line 381 of file hal_lld.h.
STM32_MCO2PRE_DIV1
#define STM32_MCO2PRE_DIV1 (0 << 27)
MCO2 divided by 1.
Definition at line 382 of file hal_lld.h.
STM32_MCO2PRE_DIV2
#define STM32_MCO2PRE_DIV2 (4 << 27)
MCO2 divided by 2.
Definition at line 383 of file hal_lld.h.
STM32_MCO2PRE_DIV3
#define STM32_MCO2PRE_DIV3 (5 << 27)
MCO2 divided by 3.
Definition at line 384 of file hal_lld.h.
STM32_MCO2PRE_DIV4
#define STM32_MCO2PRE_DIV4 (6 << 27)
MCO2 divided by 4.
Definition at line 385 of file hal_lld.h.
STM32_MCO2PRE_DIV5
#define STM32_MCO2PRE_DIV5 (7 << 27)
MCO2 divided by 5.
Definition at line 386 of file hal_lld.h.
STM32_MCO2SEL_MASK
#define STM32_MCO2SEL_MASK (3 << 30)
MCO2 mask.
Definition at line 388 of file hal_lld.h.
STM32_MCO2SEL_SYSCLK
#define STM32_MCO2SEL_SYSCLK (0 << 30)
SYSCLK clock on MCO2 pin.
Definition at line 389 of file hal_lld.h.
STM32_MCO2SEL_PLLI2S
#define STM32_MCO2SEL_PLLI2S (1 << 30)
PLLI2S clock on MCO2 pin.
Definition at line 390 of file hal_lld.h.
STM32_MCO2SEL_HSE
#define STM32_MCO2SEL_HSE (2 << 30)
HSE clock on MCO2 pin.
Definition at line 391 of file hal_lld.h.
STM32_MCO2SEL_PLL
#define STM32_MCO2SEL_PLL (3 << 30)
PLL clock on MCO2 pin.
Definition at line 392 of file hal_lld.h.
STM32_PLLI2SN_MASK
#define STM32_PLLI2SN_MASK (511 << 6)
PLLI2SN mask.
Definition at line 398 of file hal_lld.h.
STM32_PLLI2SR_MASK
#define STM32_PLLI2SR_MASK (7 << 28)
PLLI2SR mask.
Definition at line 399 of file hal_lld.h.
STM32_RTCSEL_MASK
#define STM32_RTCSEL_MASK (3 << 8)
RTC source mask.
Definition at line 406 of file hal_lld.h.
Referenced by hal_lld_backup_domain_init().
STM32_RTCSEL_NOCLOCK
#define STM32_RTCSEL_NOCLOCK (0 << 8)
No RTC source.
Definition at line 407 of file hal_lld.h.
STM32_RTCSEL_LSE
#define STM32_RTCSEL_LSE (1 << 8)
RTC source is LSE.
Definition at line 408 of file hal_lld.h.
STM32_RTCSEL_LSI
#define STM32_RTCSEL_LSI (2 << 8)
RTC source is LSI.
Definition at line 409 of file hal_lld.h.
STM32_RTCSEL_HSEDIV
#define STM32_RTCSEL_HSEDIV (3 << 8)
RTC source is HSE divided.
Definition at line 410 of file hal_lld.h.
STM32_NO_INIT
#define STM32_NO_INIT FALSE
Disables the PWR/RCC initialization in the HAL.
Definition at line 425 of file hal_lld.h.
STM32_PVD_ENABLE
#define STM32_PVD_ENABLE FALSE
Enables or disables the programmable voltage detector.
Definition at line 432 of file hal_lld.h.
STM32_PLS
#define STM32_PLS STM32_PLS_LEV0
Sets voltage level for programmable voltage detector.
Definition at line 439 of file hal_lld.h.
Referenced by hal_lld_init().
STM32_BKPRAM_ENABLE
#define STM32_BKPRAM_ENABLE FALSE
Enables the backup RAM regulator.
Definition at line 446 of file hal_lld.h.
STM32_HSI_ENABLED
#define STM32_HSI_ENABLED TRUE
Enables or disables the HSI clock source.
Definition at line 453 of file hal_lld.h.
STM32_LSI_ENABLED
#define STM32_LSI_ENABLED FALSE
Enables or disables the LSI clock source.
Definition at line 460 of file hal_lld.h.
STM32_HSE_ENABLED
#define STM32_HSE_ENABLED TRUE
Enables or disables the HSE clock source.
Definition at line 467 of file hal_lld.h.
STM32_LSE_ENABLED
#define STM32_LSE_ENABLED FALSE
Enables or disables the LSE clock source.
Definition at line 474 of file hal_lld.h.
STM32_CLOCK48_REQUIRED
#define STM32_CLOCK48_REQUIRED TRUE
USB/SDIO clock setting.
Definition at line 481 of file hal_lld.h.
STM32_SW
#define STM32_SW STM32_SW_PLL
Main clock source selection.
Note
If the selected clock source is not the PLL then the PLL is not initialized and started.
The default value is calculated for a 168MHz system clock from an external 8MHz HSE clock.
Definition at line 492 of file hal_lld.h.
STM32_PLLSRC
#define STM32_PLLSRC STM32_PLLSRC_HSE
Clock source for the PLLs.
Note
This setting has only effect if the PLL is selected as the system clock source.
The default value is calculated for a 168MHz system clock from an external 8MHz HSE clock.
Definition at line 504 of file hal_lld.h.
STM32_PLLM_VALUE
#define STM32_PLLM_VALUE 8
PLLM divider value.
Note
The allowed values are 2..63.
The default value is calculated for a 168MHz system clock from an external 8MHz HSE clock.
Definition at line 514 of file hal_lld.h.
STM32_PLLN_VALUE
#define STM32_PLLN_VALUE 336
PLLN multiplier value.
Note
The allowed values are 192..432.
The default value is calculated for a 168MHz system clock from an external 8MHz HSE clock.
Definition at line 524 of file hal_lld.h.
STM32_PLLP_VALUE
#define STM32_PLLP_VALUE 2
PLLP divider value.
Note
The allowed values are 2, 4, 6, 8.
The default value is calculated for a 168MHz system clock from an external 8MHz HSE clock.
Definition at line 534 of file hal_lld.h.
STM32_PLLQ_VALUE
#define STM32_PLLQ_VALUE 7
PLLQ multiplier value.
Note
The allowed values are 2..15.
The default value is calculated for a 168MHz system clock from an external 8MHz HSE clock.
Definition at line 544 of file hal_lld.h.
STM32_HPRE
#define STM32_HPRE STM32_HPRE_DIV1
AHB prescaler value.
Definition at line 604 of file hal_lld.h.
STM32_PPRE1
#define STM32_PPRE1 STM32_PPRE1_DIV4
APB1 prescaler value.
Definition at line 611 of file hal_lld.h.
STM32_PPRE2
#define STM32_PPRE2 STM32_PPRE2_DIV2
APB2 prescaler value.
Definition at line 618 of file hal_lld.h.
STM32_RTCSEL
#define STM32_RTCSEL STM32_RTCSEL_LSE
RTC clock source.
Definition at line 625 of file hal_lld.h.
Referenced by hal_lld_backup_domain_init().
STM32_RTCPRE_VALUE
#define STM32_RTCPRE_VALUE 8
RTC HSE prescaler value.
Definition at line 632 of file hal_lld.h.
STM32_MCO1SEL
#define STM32_MCO1SEL STM32_MCO1SEL_HSI
MCO1 clock source value.
Note
The default value outputs HSI clock on MCO1 pin.
Definition at line 640 of file hal_lld.h.
STM32_MCO1PRE
#define STM32_MCO1PRE STM32_MCO1PRE_DIV1
MCO1 prescaler value.
Note
The default value outputs HSI clock on MCO1 pin.
Definition at line 648 of file hal_lld.h.
STM32_MCO2SEL
#define STM32_MCO2SEL STM32_MCO2SEL_SYSCLK
MCO2 clock source value.
Note
The default value outputs SYSCLK / 5 on MCO2 pin.
Definition at line 656 of file hal_lld.h.
STM32_MCO2PRE
#define STM32_MCO2PRE STM32_MCO2PRE_DIV5
MCO2 prescaler value.
Note
The default value outputs SYSCLK / 5 on MCO2 pin.
Definition at line 664 of file hal_lld.h.
STM32_I2SSRC
#define STM32_I2SSRC STM32_I2SSRC_CKIN
I2S clock source.
Definition at line 671 of file hal_lld.h.
STM32_PLLI2SN_VALUE
#define STM32_PLLI2SN_VALUE 192
PLLI2SN multiplier value.
Note
The allowed values are 192..432.
Definition at line 679 of file hal_lld.h.
STM32_PLLI2SR_VALUE
#define STM32_PLLI2SR_VALUE 5
PLLI2SR multiplier value.
Note
The allowed values are 2..7.
Definition at line 687 of file hal_lld.h.
STM32_PLLSAIQ_VALUE
#define STM32_PLLSAIQ_VALUE 8
PLLSAIQ value.
Note
The allowed values are 2..15.
Definition at line 695 of file hal_lld.h.
STM32_PLLSAIN_VALUE
#define STM32_PLLSAIN_VALUE 120
PLLSAIQ value.
Note
The allowed values are 49..432.
Definition at line 703 of file hal_lld.h.
STM32_PLLSAIR_VALUE
#define STM32_PLLSAIR_VALUE 4
PLLSAIQ value.
Note
The allowed values are 2..7.
Definition at line 711 of file hal_lld.h.
STM32_0WS_THRESHOLD
#define STM32_0WS_THRESHOLD 30000000
Maximum frequency thresholds and wait states for flash access.
Note
The values are valid for 2.7V to 3.6V supply range.
Definition at line 744 of file hal_lld.h.
STM32_PLLM
#define STM32_PLLM (STM32_PLLM_VALUE << 0)
STM32_PLLM field.
Definition at line 1032 of file hal_lld.h.
STM32_PLLCLKIN
#define STM32_PLLCLKIN (STM32_HSECLK / STM32_PLLM_VALUE)
PLLs input clock frequency.
Definition at line 1041 of file hal_lld.h.
STM32_ACTIVATE_PLL
#define STM32_ACTIVATE_PLL TRUE
PLL activation flag.
Definition at line 1066 of file hal_lld.h.
STM32_PLLN
#define STM32_PLLN (STM32_PLLN_VALUE << 6)
STM32_PLLN field.
Definition at line 1076 of file hal_lld.h.
STM32_PLLP
#define STM32_PLLP (0 << 16)
STM32_PLLP field.
Definition at line 1085 of file hal_lld.h.
STM32_PLLQ
#define STM32_PLLQ (STM32_PLLQ_VALUE << 24)
STM32_PLLQ field.
Definition at line 1101 of file hal_lld.h.
STM32_PLLVCO
#define STM32_PLLVCO (STM32_PLLCLKIN * STM32_PLLN_VALUE)
PLL VCO frequency.
Definition at line 1109 of file hal_lld.h.
STM32_PLLCLKOUT
#define STM32_PLLCLKOUT (STM32_PLLVCO / STM32_PLLP_VALUE)
PLL output clock frequency.
Definition at line 1121 of file hal_lld.h.
STM32_SYSCLK
#define STM32_SYSCLK STM32_HSICLK
System clock source.
Definition at line 1134 of file hal_lld.h.
STM32_HCLK
#define STM32_HCLK (STM32_SYSCLK / 1)
AHB frequency.
Definition at line 1201 of file hal_lld.h.
STM32_PCLK1
#define STM32_PCLK1 (STM32_HCLK / 1)
APB1 frequency.
Definition at line 1233 of file hal_lld.h.
Referenced by usart_init(), and usart_start().
STM32_PCLK2
#define STM32_PCLK2 (STM32_HCLK / 1)
APB2 frequency.
Definition at line 1257 of file hal_lld.h.
Referenced by usart_init(), and usart_start().
STM32_ACTIVATE_PLLI2S
#define STM32_ACTIVATE_PLLI2S TRUE
PLLI2S activation flag.
Definition at line 1284 of file hal_lld.h.
STM32_PLLI2SN
#define STM32_PLLI2SN (STM32_PLLI2SN_VALUE << 6)
STM32_PLLI2SN field.
Definition at line 1294 of file hal_lld.h.
STM32_PLLI2SR
#define STM32_PLLI2SR (STM32_PLLI2SR_VALUE << 28)
STM32_PLLI2SR field.
Definition at line 1304 of file hal_lld.h.
STM32_ACTIVATE_PLLSAI
#define STM32_ACTIVATE_PLLSAI FALSE
PLLSAI activation flag.
Definition at line 1312 of file hal_lld.h.
STM32_PLLSAIN
#define STM32_PLLSAIN (STM32_PLLSAIN_VALUE << 6)
STM32_PLLSAIN field.
Definition at line 1319 of file hal_lld.h.
STM32_PLLSAIQ
#define STM32_PLLSAIQ (STM32_PLLSAIQ_VALUE << 24)
STM32_PLLSAIQ field.
Definition at line 1329 of file hal_lld.h.
STM32_PLLSAIR
#define STM32_PLLSAIR (STM32_PLLSAIR_VALUE << 28)
STM32_PLLSAIR field.
Definition at line 1339 of file hal_lld.h.
STM32_PLLI2SVCO
#define STM32_PLLI2SVCO (STM32_PLLCLKIN * STM32_PLLI2SN_VALUE)
PLL VCO frequency.
Definition at line 1347 of file hal_lld.h.
STM32_PLLI2SCLKOUT
#define STM32_PLLI2SCLKOUT (STM32_PLLI2SVCO / STM32_PLLI2SR_VALUE)
PLLI2S output clock frequency.
Definition at line 1360 of file hal_lld.h.
STM32_MCO1DIVCLK
#define STM32_MCO1DIVCLK STM32_HSICLK
MCO1 divider clock.
Definition at line 1366 of file hal_lld.h.
STM32_MCO1CLK
#define STM32_MCO1CLK STM32_MCO1DIVCLK
MCO1 output pin clock.
Definition at line 1381 of file hal_lld.h.
STM32_MCO2DIVCLK
#define STM32_MCO2DIVCLK STM32_HSECLK
MCO2 divider clock.
Definition at line 1398 of file hal_lld.h.
STM32_MCO2CLK
#define STM32_MCO2CLK STM32_MCO2DIVCLK
MCO2 output pin clock.
Definition at line 1413 of file hal_lld.h.
STM32_RTCPRE
#define STM32_RTCPRE (STM32_RTCPRE_VALUE << 16)
RTC HSE divider setting.
Definition at line 1431 of file hal_lld.h.
STM32_HSEDIVCLK
#define STM32_HSEDIVCLK (STM32_HSECLK / STM32_RTCPRE_VALUE)
HSE divider toward RTC clock.
Definition at line 1441 of file hal_lld.h.
STM32_RTCCLK
#define STM32_RTCCLK 0
RTC clock.
Definition at line 1450 of file hal_lld.h.
STM32_PLL48CLK
#define STM32_PLL48CLK (STM32_PLLVCO / STM32_PLLQ_VALUE)
48MHz frequency.
Definition at line 1465 of file hal_lld.h.
STM32_TIMCLK1
#define STM32_TIMCLK1 (STM32_PCLK1 * 1)
Clock of timers connected to APB1 (Timers 2, 3, 4, 5, 6, 7, 12, 13, 14).
Definition at line 1475 of file hal_lld.h.
STM32_TIMCLK2
#define STM32_TIMCLK2 (STM32_PCLK2 * 1)
Clock of timers connected to APB2 (Timers 1, 8, 9, 10, 11).
Definition at line 1484 of file hal_lld.h.
STM32_FLASHBITS
#define STM32_FLASHBITS 0x00000000
Flash settings.
Definition at line 1493 of file hal_lld.h.
Function Documentation
halInit()
void halInit (void)
HAL initialization.
This function invokes the low level initialization code then initializes all the drivers enabled in the HAL. Finally the board-specific initialization is performed by invoking boardInit() (usually defined in board.c).
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal.c.
References hal_lld_init(), and palInit.
hal_lld_backup_domain_init()
static void hal_lld_backup_domain_init (void) static
Initializes the backup domain.
Note
WARNING! Changing clock source impossible without resetting of the whole BKP domain.
Definition at line 54 of file hal_lld.c.
References rccEnableBKPSRAM, STM32_RTCSEL, and STM32_RTCSEL_MASK.
Referenced by hal_lld_init().
hal_lld_init()
void hal_lld_init (void)
Low level HAL driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 114 of file hal_lld.c.
References dmaInit(), hal_lld_backup_domain_init(), rccEnablePWRInterface, rccResetAHB1, rccResetAHB2, rccResetAPB1, rccResetAPB2, STM32_PLS, and STM32_PLS_MASK.
Referenced by halInit().
stm32_clock_init()
void stm32_clock_init (void)
STM32F2xx clocks and PLL initialization.
Note
All the involved constants come from the file board.h.
This function should be invoked just after the system reset.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 146 of file hal_lld.c.
Variable Documentation
SystemCoreClock
uint32_t SystemCoreClock = STM32_HCLK
CMSIS system core clock variable.
Note
It is declared in system_stm32f4xx.h.
Definition at line 39 of file hal_lld.c.