ChibiOS/HAL: WDG Driver
WDG Driver
HAL » Normal Drivers
Generic WDG Driver.
Detailed Description
Generic WDG Driver.
This module defines an abstract interface for a watchdog timer.
Precondition
In order to use the WDG driver the HAL_USE_WDG option must be enabled in halconf.h.
Macros
#define wdgResetI(wdgp) wdg_lld_reset(wdgp)
Resets WDG's counter.
RLR register definitions
#define STM32_IWDG_RL_MASK (0x00000FFF << 0)
#define STM32_IWDG_RL(n) ((n) << 0)
PR register definitions
#define STM32_IWDG_PR_MASK (7 << 0)
#define STM32_IWDG_PR_4 0U
#define STM32_IWDG_PR_8 1U
#define STM32_IWDG_PR_16 2U
#define STM32_IWDG_PR_32 3U
#define STM32_IWDG_PR_64 4U
#define STM32_IWDG_PR_128 5U
#define STM32_IWDG_PR_256 6U
WINR register definitions
#define STM32_IWDG_WIN_MASK (0x00000FFF << 0)
#define STM32_IWDG_WIN(n) ((n) << 0)
#define STM32_IWDG_WIN_DISABLED STM32_IWDG_WIN(0x00000FFF)
Configuration options
#define STM32_WDG_USE_IWDG FALSE
IWDG driver enable switch.
Typedefs
typedef struct WDGDriver WDGDriver
Type of a structure representing an WDG driver.
Data Structures
struct WDGConfig
Driver configuration structure.
struct WDGDriver
Structure representing an WDG driver.
Functions
void wdgInit (void)
WDG Driver initialization.
void wdgStart (WDGDriver *wdgp, const WDGConfig *config)
Configures and activates the WDG peripheral.
void wdgStop (WDGDriver *wdgp)
Deactivates the WDG peripheral.
void wdgReset (WDGDriver *wdgp)
Resets WDG's counter.
void wdg_lld_init (void)
Low level WDG driver initialization.
void wdg_lld_start (WDGDriver *wdgp)
Configures and activates the WDG peripheral.
void wdg_lld_stop (WDGDriver *wdgp)
Deactivates the WDG peripheral.
void wdg_lld_reset (WDGDriver *wdgp)
Reloads WDG's counter.
Enumerations
enum wdgstate_t { WDG_UNINIT = 0, WDG_STOP = 1, WDG_READY = 2 }
Driver state machine possible states.
Macro Definition Documentation
wdgResetI
#define wdgResetI (wdgp) wdg_lld_reset(wdgp)
Resets WDG's counter.
Parameters
[in] wdgp pointer to the WDGDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 68 of file wdg.h.
Referenced by wdgReset().
STM32_WDG_USE_IWDG
#define STM32_WDG_USE_IWDG FALSE
IWDG driver enable switch.
If set to TRUE the support for IWDG is included.
Note
The default is FALSE.
Definition at line 79 of file wdg_lld.h.
Typedef Documentation
WDGDriver
typedef struct WDGDriver WDGDriver
Type of a structure representing an WDG driver.
Definition at line 110 of file wdg_lld.h.
Enumeration Type Documentation
wdgstate_t
enum wdgstate_t
Driver state machine possible states.
Enumerator
WDG_UNINIT
Not initialized.
WDG_STOP
Stopped.
WDG_READY
Ready.
Definition at line 49 of file wdg.h.
Function Documentation
wdgInit()
void wdgInit (void)
WDG Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file wdg.c.
References wdg_lld_init().
wdgStart()
void wdgStart (WDGDriver * wdgp, const WDGConfig * config)
Configures and activates the WDG peripheral.
Parameters
[in] wdgp pointer to the WDGDriver object
[in] config pointer to the WDGConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 69 of file wdg.c.
References WDGDriver::config, WDGDriver::state, wdg_lld_start(), WDG_READY, and WDG_STOP.
wdgStop()
void wdgStop (WDGDriver * wdgp)
Deactivates the WDG peripheral.
Parameters
[in] wdgp pointer to the WDGDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 89 of file wdg.c.
References WDGDriver::state, wdg_lld_stop(), WDG_READY, and WDG_STOP.
wdgReset()
void wdgReset (WDGDriver * wdgp)
Resets WDG's counter.
Parameters
[in] wdgp pointer to the WDGDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 108 of file wdg.c.
References WDGDriver::state, WDG_READY, and wdgResetI.
wdg_lld_init()
void wdg_lld_init (void)
Low level WDG driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 67 of file wdg_lld.c.
References WDGDriver::state, WDGDriver::wdg, and WDG_STOP.
Referenced by wdgInit().
wdg_lld_start()
void wdg_lld_start (WDGDriver * wdgp)
Configures and activates the WDG peripheral.
Parameters
[in] wdgp pointer to the WDGDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 82 of file wdg_lld.c.
References WDGDriver::wdg.
Referenced by wdgStart().
wdg_lld_stop()
void wdg_lld_stop (WDGDriver * wdgp)
Deactivates the WDG peripheral.
Parameters
[in] wdgp pointer to the WDGDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 120 of file wdg_lld.c.
References WDGDriver::state, and WDG_STOP.
Referenced by wdgStop().
wdg_lld_reset()
void wdg_lld_reset (WDGDriver * wdgp)
Reloads WDG's counter.
Parameters
[in] wdgp pointer to the WDGDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 133 of file wdg_lld.c.
References WDGDriver::wdg.