image: python:3.5


server-tests:
    stage: test
    script: 
        - pip install -r requirements.txt
        - pip install -e .
        - initialize_db development.ini
        - pytest makahiya/tests.py -q
